### ISSUE TITLE
sarama is now in IBM not in Shopify

### ISSUE THREAD

**Issue by bearbearkeeper** [openimsdk/open-im-server#1030]
### What would you like to share?

sarama's ownership was transferred away from Shopify to IBM

### Additional information

https://github.com/IBM/sarama/issues/2626

**Comment by cubxxw** [comment]
@bearbearkeeper failure in link

**Comment by bearbearkeeper** [comment]
@cubxxw sorry, i've updated it

**Comment by bearbearkeeper** [comment]
@cubxxw IBM/sarama no longer depend on this package from v1.41.0
