### ISSUE TITLE
把短信服务改了自己的阿里云配置 运行不了

### ISSUE THREAD

**Issue by 1452479141** [OpenIMSDK/Open-IM-Server#106]
![图片](https://user-images.githubusercontent.com/50287498/146502467-ca36e697-b058-4edf-b3e6-c4853b269309.png)
![图片](https://user-images.githubusercontent.com/50287498/146502483-1194e5bb-7a21-48ee-92e6-25da494ec746.png)

**Comment by skiffer-git** [comment]
demoswitch: true

**Comment by 1452479141** [comment]
改了 还是不行，客户端有时候会提示服务端未配短信服务，有时候会发短信，大部分提示的是 未配置

**Comment by skiffer-git** [comment]
check config or communicate with alicloud customer service

**Comment by skiffer-git** [comment]
use v2.2.0
