### ISSUE TITLE
Ubuntu16.04 docker 安装启动失败

### ISSUE THREAD

**Issue by liumingsongning** [OpenIMSDK/Open-IM-Server#107]
etcd is up-to-date
zookeeper is up-to-date
redis is up-to-date
mongo is up-to-date
mysql is up-to-date
kafka is up-to-date
Starting open_im_server ... error

ERROR: for open_im_server  Cannot start service open_im_server: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./docker_start_all.sh\": permission denied": unknown

ERROR: for open_im_server  Cannot start service open_im_server: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./docker_start_all.sh\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by skiffer-git** [comment]
cd script; chmod +x *.sh

**Comment by blisssayyid** [comment]
我这边直接是 `ERROR: for open_im_server  Cannot start service open_im_server: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./docker_start_all.sh": stat ./docker_start_all.sh: no such file or directory: unknown`找不到，我是这样解决的：

1. 将script内容手动粘贴到挂载映射的script目录中
2. 然后会发生上述问题，look https://github.com/OpenIMSDK/Open-IM-Server/issues/107#issuecomment-996503449
3. 重新 docker-compose up -d 解决

**Comment by qiushuitian** [comment]
我这边用centOS部署的没问题，但是用macOS部署的就有这个问题。

**Comment by striveQiao** [comment]
> 我这边直接是 `ERROR: for open_im_server Cannot start service open_im_server: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "./docker_start_all.sh": stat ./docker_start_all.sh: no such file or directory: unknown`找不到，我是这样解决的：
> 
> 1. 将script内容手动粘贴到挂载映射的script目录中
> 2. 然后会发生上述问题，look [Ubuntu16.04 docker 安装启动失败 #107 (comment)](https://github.com/OpenIMSDK/Open-IM-Server/issues/107#issuecomment-996503449)
> 3. 重新 docker-compose up -d 解决

大哥，遇到同样问题了，第一步怎么操作 将script内容手动粘贴到挂载映射的script目录中，映射目录不是在镜像内吗，镜像的容器都没启动怎么手动粘贴
