### ISSUE TITLE
支持分库分表

### ISSUE THREAD

**Issue by metaroad** [OpenIMSDK/Open-IM-Server#109]
支持分库分表吗？

**Comment by ClockworkChen** [comment]
目前不支持，你可以直接上tidb之类的，兼容性应该还是可以，对于分库分表中间件有其本身的问题，更建议使用tidb类似的方案，或者mysql_proxy等组件来实现也是可以的，社区后面也不知道会不会支持。

**Comment by skiffer-git** [comment]
Messages are not stored in mysql
