### ISSUE TITLE
Feature: better config handling for kube deploy

### ISSUE THREAD

**Issue by charles-chenzz** [openimsdk/open-im-server#1105]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

while I tried to containerize the whole project into kube. I found out that there're few issues.

1. every images/dockerfile that I build out and run in docker / kube need to configure hard deps in middleware or volumes. and it seems like hard-coded in the code base. which the best practice is we should separate config and code logic. (at least not copy config into images then read it directly, instead, we should obtain config in remote-repos or kube env)

2. every component I build can't run individually due to the middleware issues in 1, which should consider same problem and resolve it together.

3. when using local build in server, because we using multi stages build, it will leave out an middle images which size around 1 gb.

4. the potential log collection. the current component logs are all mixed up which is not easy and separate when we running in kube/containerize environment.

### Solution Description

1. get rip of directly copy config.yaml or something into images and refactor code to adapt it
2. found out a better way to handle log collection

### Benefits

make every component can deploy in micro-service way

### Additional Information

@cubxxw

**Comment by cubxxw** [comment]
make image
