### ISSUE TITLE
[Other]: Why notification creates a  single chat conversations ? feature or bug?

### ISSUE THREAD

**Issue by yudoutingle** [openimsdk/open-im-server#1121]
### What would you like to share?

the conversation named "si_A_B" is created when I send a notification message( session_type = 4 ) with sendId = 'A' and recvId = 'B' ., which really consuing me .

When the client starts, it gets all the conversations and the max seq. In this way, when the client starts,  it gets error conversations, and then it cannot pull correct messages. 

I think "sn_A_B" shoule be create when a notification send . 

### Additional information

no other.

**Comment by FGadvancer** [comment]
The messages with conversation type 4 have not been processed yet. I will submit a pull request later to fix this issue.
