### ISSUE TITLE
Bug: Changing the MYSQL_ADDRESS in environment.sh does not work in.env

### ISSUE THREAD

**Issue by LiJoeAllen** [openimsdk/open-im-server#1123]
### What would you like to share?

**系统环境**

- 发行版本 rocky-9.2
- 内核版本 5.14.0-284.11.1.el9_2.x86_64
- 系统类型 x86_64

按照https://doc.rentsoft.cn/guides/gettingStarted/dockerCompose

openim-web跑起来没问题，但是openim-server后台的数据库连接没连上，更新environment.sh内数据库配置重新执行make init后.env虽然重新生成了，但是内容并不是更改后的内容
  
openim-chat log 
![image](https://github.com/openimsdk/open-im-server/assets/49467845/09f8d797-3c79-4e87-b97f-d9788f985c4e)
openim-server log 
![image (1)](https://github.com/openimsdk/open-im-server/assets/49467845/3f913b10-79f1-452b-9c72-4a17f3caac2f)
environment.sh 
![image (2)](https://github.com/openimsdk/open-im-server/assets/49467845/91423e00-b71f-4417-88db-f71e022919ab)
make init 
![image (3)](https://github.com/openimsdk/open-im-server/assets/49467845/f49e54b0-960a-45bb-97b3-07890d4f9cb0)
.env 
![image (4)](https://github.com/openimsdk/open-im-server/assets/49467845/f3a3d232-7333-46aa-8228-ac4eead3eeaa)
我没给环境变量优先级更改是根据environment.sh来的呀
生成出来的为什么是$(generate_ip)？

**Comment by cubxxw** [comment]
Mark: Resolved, modified network segment
