### ISSUE TITLE
How to modify the code to use PostgreSQL instead of MySQL

### ISSUE THREAD

**Issue by fi-ecavc** [openimsdk/open-im-server#1138]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

We mentioned this requirement at the previous biweekly meeting, when experts said that it was possible, that the default database part of the code needed to be modified, and for the sake of caution, we asked experts for advice on how to make changes and adjustments, and we planned to experiment with it to reduce the database components. 

### Solution Description

Of course, if OpenIM can be modified into a database with optional MySQL or PG, the current performance and stability reliability of PG have been greatly improved, and users have grown greatly in recent times.

### Benefits

Support multiple databases to meet the needs of different customers, which is more conducive to the value creation of OpenIM.

**Comment by skiffer-git** [comment]
We plan to replace MySQL with MongoDB and hope that interested contributors will join in the community development.
