### ISSUE TITLE
服务启动了  10700没正常启动  客户端发消息 A发给B   B收不到

### ISSUE THREAD

**Issue by yangtianshi** [OpenIMSDK/Open-IM-Server#114]
启动服务的时候：

### 

> __

![微信图片_20220102130244](https://user-images.githubusercontent.com/24701342/147866750-cc53e07d-58b4-40cf-8ddd-02826b5071c0.png)

发送消息：

![微信图片_20220102130445](https://user-images.githubusercontent.com/24701342/147866793-356315bf-1c13-4ba2-9626-f5eb25823486.jpg)

消息错误日志：

![1641098673(1)](https://user-images.githubusercontent.com/24701342/147866798-80a1bb68-74db-4abc-9bda-26f3dad23026.jpg)

websocket日志：

![1641098706(1)](https://user-images.githubusercontent.com/24701342/147866803-7362dc1e-0b9a-47b6-8168-4e5e10270085.jpg)

**Comment by skiffer-git** [comment]
Use the latest image
