### ISSUE TITLE
[BUG] 自己添加自己的账号后报错无法进入系统

### ISSUE THREAD

**Issue by hxnets** [OpenIMSDK/Open-IM-Server#117]
PC Demo 自己添加自己的账号发送了一条聊天信息后就无法登陆了一直报错，无法进入页面

![image](https://user-images.githubusercontent.com/32917172/148000707-a97e0551-d4e0-4e77-9f61-0d522d65cc1a.png)

**Comment by skiffer-git** [comment]
Use new version
