### ISSUE TITLE
[Other]: make init      scripts/../scripts/lib/color.sh: line 23: conditional binary operator expected

### ISSUE THREAD

**Issue by xsm818** [openimsdk/open-im-server#1182]
### What would you like to share?

git clone https://github.com/openimsdk/open-im-server && cd open-im-server 
make init

When I deployment component

===========> Initializing openim server project
/Users/*****/open-im-server/scripts/../scripts/lib/color.sh: line 23: conditional binary operator expected
make[1]: *** [gen.init] Error 2
make: *** [init] Error 2

### Additional information

**OS：** macOS Monterey 12.6.1
**Shell：** /bin/zsh (version 5.8.1)
**go version：** go1.21.1 darwin/amd64

**Comment by cubxxw** [comment]
```bash
bash version
```
The script interpreter uses the #! /usr/bin/env bash, I need to know the bash version

**Comment by cubxxw** [comment]
The -v operator may not be available in some older versions of Bash. You provide your system information, which indicates that the shell you use is zsh, not bash. While the two have a lot in common, there are also some differences. -v may not be available in some zsh versions or some older versions of bash.

**Comment by xsm818** [comment]
Thanks! Upgrading to the new version was successful. 

Upgrade from 3.2.57(1)-release to **bash 5.2.15**
