### ISSUE TITLE
Bug: 3.3.0 source code deployment

### ISSUE THREAD

**Issue by liumingsongning** [openimsdk/open-im-server#1195]
### What happened?

3.3.0 Source code deployment，mysql not link，172.28.0.1:13306

### What did you expect to happen?

can success start

### How can we reproduce it (as minimally and precisely as possible)?

after I use docker-compose deployment to I use Source code deployment

### version

<details>
go version go1.20.10 linux/amd64

 docker Version:           20.10.21

</details>

### Cloud provider

<details>
阿里云
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux iZ2ze7oih8je700gqfydy9Z 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
</details>


### Install tools

<details>
apt-get
</details>

**Comment by cubxxw** [comment]
You can read: https://github.com/openimsdk/open-im-server/issues/1107

**Comment by liumingsongning** [comment]
Another possibility is that the network segment of the eth0 server conflicts with the network segment of the docker virtual network adapter. Therefore, change the default 172.28.0.
