### ISSUE TITLE
配置文件config.yaml中multiloginpolicy的定义和config.go的结构定义不同

### ISSUE THREAD

**Issue by hxnets** [OpenIMSDK/Open-IM-Server#120]
配置文件config.yaml中multiloginpolicy的定义和config.go的结构定义不同，一个是结构体一个是int，导致编译不通过
文件路径：/pkg/common/config/config.go

<img width="980" alt="WeChat7f82c3f565d5cb23ff6e2d9811c7d61a" src="https://user-images.githubusercontent.com/32917172/148014344-d7ddef16-e3e9-4185-bce1-6dbb344c262f.png">

文件路径：/config/config.yaml
<img width="534" alt="WeChatc1e1ccaa3719050718e1fe327efd5e68" src="https://user-images.githubusercontent.com/32917172/148014425-a3910fe8-8f9c-4ed2-a6a4-7d7284104b24.png">

**Comment by skiffer-git** [comment]
fixed
