### ISSUE TITLE
[Other]: Regarding the storage of chat image files

### ISSUE THREAD

**Issue by duola297** [openimsdk/open-im-server#1208]
### What would you like to share?

"By default, Minio storage is used, but it can also be configured to use COS (Tencent Cloud Object Storage) or OSS (Alibaba Cloud Object Storage Service). Recently, my colleague implemented storage using Huawei Cloud OBS (Object Storage Service). I attempted to add the relevant configuration information to the configuration file and changed 'enable' to 'obs.' After compiling and starting the service, I noticed that image files could still be sent successfully. However, when viewing the related chat records, I found that the file paths remained the same as before. Could you please advise on how to address this issue?"
![f26aaad2fb2cc293a401e679d67b57e](https://github.com/openimsdk/open-im-server/assets/99168066/1d977c1b-edf7-411b-b5ac-bb82ff955ff4)

**Comment by withchao** [comment]
The URL returned by uploading is API specific and will be redirected to the real path during access.

**Comment by duola297** [comment]
So, if I've switched to OBS, and I'm able to send image files successfully, does that mean it's a success? Is there a way for me to view the actual path?

**Comment by withchao** [comment]
Access the returned URL and reset it to the real address.

**Comment by lovemianhuatang** [comment]
@duola297 Hello, I also want to change to Huawei Cloud OBS. Can I use it normally by following the configuration in the picture you mentioned above?
