### ISSUE TITLE
Bug: Minio connection is abnormal in centos 7.9

### ISSUE THREAD

**Issue by fx10007** [openimsdk/open-im-server#1209]
### What happened?

docker compose had an accident while deploying openIM

### What did you expect to happen?

The Minio connection failed

### How can we reproduce it (as minimally and precisely as possible)?

```
git clone https://github.com/openim-sigs/openim-docker openim/openim-docker && export openim=$(pwd)/openim && cd $openim/openim-docker && make init && docker compose up -d
```

### Anything else we need to know?

Query the log information to get a conclusion.
Minio failed to automatically obtain a public IP address during deployment. The actual IP address obtained was a private IP address. Procedure

### version

version:
export CHAT_BRANCH="release-v1.3"
SERVER_BRANCH="release-v3.3"

### Cloud provider

aliyun

### OS version

On Linux: CentOs 7.9_x64
Internal Storage: 4GB
Disk : 40GB
Bandwidth : 100M

### Install tools

ngnix 1.18

**Comment by cubxxw** [comment]
To ensure a successful deployment using the "make init" script, it is essential to have the "dig" tool installed. However, it is worth noting that the "dig" tool is not pre-installed in CentOS 7.9, which may result in obtaining only the internal IP address. To resolve this issue, you can install the "dig" tool by running the command "yum install dig". Once the installation is complete, you can proceed with the deployment using the "make init" script. If you have any further questions, please do not hesitate to ask. Thank you.
