### ISSUE TITLE
[BUG] 如图mysql/mongo等一直restarting，启动不了

### ISSUE THREAD

**Issue by jy05568536** [OpenIMSDK/Open-IM-Server#121]
centos7 虚拟机环境

![image](https://user-images.githubusercontent.com/5037606/148734088-2b9ddc96-4e68-4001-ba27-bd19829a1824.png)

**Comment by xiusl** [comment]
`docker logs` 看一下具体什么原因

**Comment by jy05568536** [comment]
我看都是Permission denied

**Comment by jy05568536** [comment]
> `docker logs` 看一下具体什么原因

我看都是Permission denied

**Comment by xiusl** [comment]
![image](https://user-images.githubusercontent.com/14972655/149736389-ff4f6f72-0147-4e03-ac0b-6166bd8a0405.png)
会不会挂在卷的问题，当前的工作目录是否有权限

**Comment by jy05568536** [comment]
怪了，我是用root用户运行，也没有改过什么配置
![image](https://user-images.githubusercontent.com/5037606/149739561-f3742fb2-5432-443c-a1d4-bc3e1a528dad.png)

**Comment by xiusl** [comment]
docker在centos7下的一些坑，供参考
https://www.cnblogs.com/yddmax/p/6184100.html

**Comment by jy05568536** [comment]
> docker在centos7下的一些坑，供参考 https://www.cnblogs.com/yddmax/p/6184100.html

感谢耐心回答，原因是selinux，关闭即可
