### ISSUE TITLE
[BUG] docker部署，初步估计是kafka，导致open_im_user启动不了

### ISSUE THREAD

**Issue by jy05568536** [OpenIMSDK/Open-IM-Server#125]
折腾了好久，open_im_user就是起不起来
![image](https://user-images.githubusercontent.com/5037606/153829404-6a691e38-8568-4f19-94bb-b787ee0a70ac.png)

日志里报kafka问题，换了几个版本还是不行
![image](https://user-images.githubusercontent.com/5037606/151141380-fb68c916-f3f5-46c5-9890-aa6f131c3d13.png)

zookeeper里报错
![image](https://user-images.githubusercontent.com/5037606/153829098-3e0235ff-ecae-4e88-9698-4f7882301c6f.png)

**Comment by meichengkeji** [comment]
我也遇到了  别用docker部署， kafka ，我手动安装的正常了

话说问题太多了，我这倒腾两天 有希望跑起来了， 官方能不能重新整理一下项目很多 小毛病

**Comment by jy05568536** [comment]
> 我也遇到了 别用 docker部署 kafka ，我手动安装的正常了
> 
> 话说问题太多了，我这倒腾两天 有希望跑起来了， 官方能不能重新整理一下项目很多 小毛病

谢谢，看来坑还很多呀

**Comment by xyctruth** [comment]
我更新了一下docker-compose，我在我本机 mac 使用成功了。你可以尝试下。#138

"docker-compose up -d" 之前先运行 "docker-compose down" ,确保环境被清理掉。

**Comment by jy05568536** [comment]
> 我更新了一下docker-compose，我在我本机 mac 使用成功了。你可以尝试下。#138
> 
> "docker-compose up -d" 之前先运行 "docker-compose down" ,确保环境被清理掉。

你的docker和docker-compose分别是什么版本

**Comment by xyctruth** [comment]
我的意思是我更新了一下 docker-compose.yaml 在#138中，应该和docker和docker-compse 版本没关系。

**Comment by jy05568536** [comment]
> 我的意思是我更新了一下 docker-compose.yaml 在 #138 中，应该和docker和docker-compose 版本没关系。

亲测无效，centos系统，注释了network_mode，10000端口都起不起来，不过还是感谢回复

**Comment by skiffer-git** [comment]
Take a screenshot of the operation process: 



git clone https://github.com/OpenIMSDK/Open-IM-Server.git --recursive

cd Open-IM-Server/script ; chmod +x *.sh ; ./env_check.sh

cd .. ; docker-compose up -d

cd script ; ./docker_check_service.sh

**Comment by ShanDongChenGuanXi** [comment]
楼主怎么解决的 一样的问题

**Comment by skiffer-git** [comment]
use v2.2.0
