### ISSUE TITLE
[BUG] 服务启动一段时间后（几个小时至一两天），就会出现RPC ERROR

### ISSUE THREAD

**Issue by 39499740** [OpenIMSDK/Open-IM-Server#127]
![image](https://user-images.githubusercontent.com/29425312/151200393-8dd77018-0810-4568-8354-f22308043b1b.png)
![image](https://user-images.githubusercontent.com/29425312/151200421-b8cef7f1-a5a1-445a-bb23-add08596eb3c.png)

使用的Docker部署，系统4C8G，刚装好Centos7，Docker及Docker-compose都是最新版

**Comment by 89trillion-feiyang** [comment]
我这边也出现了这种情况，兄弟。解决了吗兄弟

**Comment by 89trillion-feiyang** [comment]
可能是etcd续约没续上吧？解决了吗

**Comment by 39499740** [comment]
> 可能是etcd续约没续上吧？解决了吗

没解决，不知道怎么回事，不过现在更重要的是另一个问题……api日志每秒2MB大小，直接把硬盘填满了……改了日志level也没用

**Comment by 89trillion-feiyang** [comment]
> > 可能是etcd续约没续上吧？解决了吗
> 
> 没解决，不知道怎么回事，不过现在更重要的是另一个问题……api日志每秒2MB大小，直接把硬盘填满了……改了日志level也没用

api日志这么多？修改这里不行吗？
https://github.com/OpenIMSDK/Open-IM-Server/blob/fb1871b979606ec9c453d1fd2746d034483da727/pkg/common/log/file_line_hk.go#L22-L24

**Comment by 39499740** [comment]
> 

没改源码，改的config，改完以后其他log都没了，就这个不好使……

**Comment by 89trillion-feiyang** [comment]
> > 
> 
> 没改源码，改的config，改完以后其他log都没了，就这个不好使……

刚试了下，level改成2可以

**Comment by 39499740** [comment]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/29425312/153987360-b4d615eb-7bb8-4ede-bbbc-9cf85035a7fe.png">
一直是……

**Comment by skiffer-git** [comment]
Use new version
