### ISSUE TITLE
如果考虑基于该框架实现阅后即焚，难度如何呢？

### ISSUE THREAD

**Issue by guchensmile** [OpenIMSDK/Open-IM-Server#13]
是否底层可以很好的实现无痕销毁等能力？

**Comment by bigdong89** [comment]
国内法律规定要保存3-6个月的...所以....当我没说。。。

**Comment by lfgogogo** [comment]
这个功能，懂得都懂

**Comment by skiffer-git** [comment]
You can use OpenIM to implement this function, but the server also keeps historical chat records.
