### ISSUE TITLE
建议取消自动创建数据库的逻辑

### ISSUE THREAD

**Issue by gh1st** [OpenIMSDK/Open-IM-Server#133]
自动创建数据库需要给比较高的权限，建议这个步骤还是留给用户自己处理比较好

https://github.com/OpenIMSDK/Open-IM-Server/blob/7accffd7cd024c20b4660856d8691159e45eefd7/pkg/common/db/mysql.go#L21

**Comment by skiffer-git** [comment]
Easier deployment
