### ISSUE TITLE
mac panic: yaml: unmarshal errors:

### ISSUE THREAD

**Issue by meichengkeji** [OpenIMSDK/Open-IM-Server#135]
panic: yaml: unmarshal errors:
  line 133: cannot unmarshal !!int `1` into struct { OnlyOneTerminalAccess bool "yaml:\"onlyOneTerminalAccess\""; MobileAndPCTerminalAccessButOtherTerminalKickEachOther bool "yaml:\"mobileAndPCTerminalAccessButOtherTerminalKickEachOther\""; AllTerminalAccess bool "yaml:\"allTerminalAccess\"" }

goroutine 1 [running]:
Open_IM/pkg/common/config.init.0()
	/Users/bao-mac/Open-IM-server/pkg/common/config/config.go:172 +0x7a

**Comment by meichengkeji** [comment]
解决了  原因 	Secret           string `yaml:"secret"`
	MultiLoginPolicy struct {
		OnlyOneTerminalAccess                                  bool `yaml:"onlyOneTerminalAccess"`
		MobileAndPCTerminalAccessButOtherTerminalKickEachOther bool `yaml:"mobileAndPCTerminalAccessButOtherTerminalKickEachOther"`
		AllTerminalAccess                                      bool `yaml:"allTerminalAccess"`
	}

**Comment by tong424** [comment]
请问下你是如何解决的？

**Comment by peter56191884** [comment]
注意修改配置的地方是否有格式错误。可能少一个空格都会导致错误。
