### ISSUE TITLE
Bug: Use Linux system for production deployment

### ISSUE THREAD

**Issue by huangzhengwang** [openimsdk/open-im-server#1379]
### What happened?

./scripts/install/install.sh -i
/root/open-im-server/scripts/install/test.sh: line 112: syntax error in conditional expression
!!! Error in ./scripts/install/install.sh:56 
  Error in ./scripts/install/install.sh:56. '${OPENIM_ROOT}/scripts/install/test.sh' exited with status 2
Call stack:
  1: ./scripts/install/install.sh:56 main(...)
Exiting with status 1

### What did you expect to happen?

git clone https://github.com/openimsdk/open-im-server && cd open-im-server
./scripts/install/install.sh -i  

### How can we reproduce it (as minimally and precisely as possible)?

git clone https://github.com/openimsdk/open-im-server && cd open-im-server
./scripts/install/install.sh -i  

### version

commit 686fa80800d54ab7992359d60c33e392c7790ba7 (HEAD -> main, origin/main, origin/HEAD)
Author: fengyun.rui <rfyiamcool@163.com>
Date:   Fri Nov 10 17:55:50 2023 +0800

### Cloud provider

<details>
</details>

### OS version

NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
you can look https://github.com/openimsdk/open-im-server/issues/1380

**Comment by cubxxw** [comment]
https://github.com/openimsdk/open-im-server/blob/d1af343b136e8d4fa5edbb5e497acd0cd9455220/scripts/install/install.sh#L108C1-L114C2

Could you please consider removing the lines "errexit +x" and "errexit -x" from the code? I believe it would greatly improve the overall quality and readability of the code. Thank you for your attention to this matter.

**Comment by huangzhengwang** [comment]
I don’t know how it works again. I did the following operations and I’m not sure which one took effect.
1.git pull
2.source ~/.bashrc
