### ISSUE TITLE
how to transfer the old version data to another server?

### ISSUE THREAD

**Issue by yhuaqiang** [openimsdk/open-im-server#1404]
### What happened?

the old server version is 2.3.1, the new server is 2.3.1 or  the latest on another ecs,
how to transfer the old data, 

### What did you expect to happen?

the old server version is 2.3.1, the new server is 2.3.1 or  the latest on another ecs,
how to transfer the old data, 

### How can we reproduce it (as minimally and precisely as possible)?

the old server version is 2.3.1, the new server is 2.3.1 or  the latest on another ecs,
how to transfer the old data, 

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
I am not sure if you have deployed openim using Docker compose or source code. Could you please clarify?

**Comment by cubxxw** [comment]
## Migrating OpenIM: A Step-by-Step Guide

### Understanding the Challenge

In the realm of server management and data migration, one common challenge is moving data from an older server to a new one. This is particularly relevant when working with applications like OpenIM, a popular instant messaging solution. Let's consider a specific scenario: you have OpenIM version 2.3.1 running on an old server and intend to migrate it to a new server, which could either be the same version or the latest one on another Elastic Compute Service (ECS).

### The Problem at Hand

+ **Current Situation**: OpenIM version 2.3.1 is operational on an old server.
+ **Objective**: To transfer all existing data to a new server with the same or the latest version of OpenIM.

### Methodology for Migration

If your deployment of OpenIM is Docker-based, the migration process involves several key steps, focusing mainly on data directories and Docker compositions. Here’s a detailed breakdown:

1. **Identify the Data Directory**:
   + In Docker deployments, the `.env` file plays a crucial role. Particularly, the `DATA_DIR` field within this file indicates the location of your data directory.
   + Commonly, your data resides in the `components/` directory, which is located within the `$DATA_DIR` directory.
2. **Data Migration Steps**:
   + **Backup**: The first and most crucial step is to backup the `components/` directory from your old server. This directory is vital as it contains all your OpenIM data.
   + **Transfer**: Once backed up, you need to transfer this directory to your new server. This can be done via various methods like SCP (Secure Copy Protocol), FTP (File Transfer Protocol), or any other secure file transfer method you prefer.
3. **Setting Up the New Server**:
   + After transferring the data, you need to set up the new server. This involves installing OpenIM (either the same version 2.3.1 or the latest one, as per your requirement).
   + **Restoring Data**: On the new server, restore the backup of the `components/` directory to the designated data directory as indicated in the new server's `.env` file.
4. **Docker Compose and Middleware Mounting**:
   + It’s essential to understand the middleware mounting methods within Docker Compose. Docker Compose utilizes the variables defined in the `.env` file.
   + Ensure that the new server's Docker Compose setup correctly references and mounts the restored `components/` directory. This is crucial for OpenIM to access and use the migrated data.
5. **Final Checks and Testing**:
   + Once everything is set up, it's important to conduct thorough testing to ensure that the OpenIM instance on the new server is functioning correctly and all the data has been migrated successfully.

### Conclusion

Migrating OpenIM, especially in Docker environments, requires careful attention to data directories and proper handling of Docker Compose configurations. By following the steps outlined above, you can ensure a smooth transition of your OpenIM data from an old server to a new one, maintaining continuity and integrity of your instant messaging
