### ISSUE TITLE
faid to Migrate v2 data to v3. the go file return no reponse

### ISSUE THREAD

**Issue by yhuaqiang** [openimsdk/open-im-server#1426]
### What happened?

<img width="911" alt="60cd847c4868e0a4cd0bbc363c68c4c" src="https://github.com/openimsdk/open-im-server/assets/5283803/8d81714d-8d39-44c4-95a8-f2a53301c6f6">

the print never print

mysql can be connected in shell but failed in go file

### What did you expect to happen?

mysql can be connected in shell but failed in go file

### How can we reproduce it (as minimally and precisely as possible)?

mysql can be connected in shell but failed in go file

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
Could you please check if there are any errors in the username and password, and also verify if the username and password in the config.yaml file correspond correctly? Thank you for your assistance.

**Comment by yhuaqiang** [comment]
finally, migrating ok!
but how to migrate chat messages? mysql table : chat_logs 
and if the mongodb need to be migrated?

**Comment by cubxxw** [comment]
@withchao
