### ISSUE TITLE
[功能建议]希望新增消息记录拉取API与违禁词功能

### ISSUE THREAD

**Issue by zjttfs** [OpenIMSDK/Open-IM-Server#143]
### 1.违禁词
```
管理员可以设定某些词语禁止发出 或者 服务器直接替换为****
政治正确还是必要的
```

### 2.消息记录拉取API
```
管理员使用两个用户的UID获取两人的聊天记录
应用于如:网站两用户交易发生纠纷,需要管理人员判定的时候.就需要有历史聊天记录作为证据来判断
```

---

> 临时解决方案
```
所有消息发到[应用服务器],由[应用服务器]将消息处理与记录备份,再使用API[manager/send_msg]发送到[OpenImServer]
```
这样做流程增多,且需要重复记录聊天信息,希望还是能在`OpenImServer`里面一次解决掉

**Comment by FGadvancer** [comment]
1、The next version will build a complete message's callback plan. OpenImServer will callback the business server. Currently, there is a simple callback in the server's config that can be used to modify the message before sending message. The specific document is being  written.
![image](https://user-images.githubusercontent.com/46924906/155290871-66c3a368-6603-481f-822c-83d6f4293239.png)
2、The newest version has been launched, and the management system can  see it.The specific document is being  written.
