### ISSUE TITLE
how to set the password of  manager ids

### ISSUE THREAD

**Issue by yhuaqiang** [openimsdk/open-im-server#1435]
### What happened?

in v2 config file, 
![image](https://github.com/openimsdk/open-im-server/assets/5283803/7307e807-d6a6-4b7f-9fd4-2de28d8fc089)
 in v3 config file
<img width="454" alt="f4f2bb27ec7aeb7d3f82f120eec329f" src="https://github.com/openimsdk/open-im-server/assets/5283803/ec2fb48d-e7b1-477e-9bea-6efa716e73d6">

how to set password of manager accounts?

### What did you expect to happen?

set the password of manager

### How can we reproduce it (as minimally and precisely as possible)?

set the password of manager

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
thx，can u use is v2 or v3？

**Comment by yhuaqiang** [comment]
now i'm using v2, and plan to migrate to v3, how to deal this situation?

**Comment by cubxxw** [comment]
> now i'm using v2, and plan to migrate to v3, how to deal this situation?

@withchao
