### ISSUE TITLE
大量客户端连接，严重问题（无任何业务，cpu很高）

### ISSUE THREAD

**Issue by situnan** [OpenIMSDK/Open-IM-Server#146]
分析：ws_server.go文件中，维护的map（wsUserToConn ，wsConnToUser ），当存储很多client信息（200w）的时候，内存很高，这样gc间隔扫描全部大内存，导致耗时费cpu，请修正。（这样的client不做任何业务，只是保活）

type WServer struct {
	wsAddr       string
	wsMaxConnNum int
	wsUpGrader   *websocket.Upgrader
	wsConnToUser map[*UserConn]map[string]string
	wsUserToConn map[string]map[string]*UserConn
}

**Comment by skiffer-git** [comment]
What is your optimization plan?

**Comment by situnan** [comment]
Need to customize a map implementation.for golang, map value has no pointer, gc is not scanned, and slices are not scanned (the tube has a pointer)   etc:

type LMap struct {
	objSlice []LMapObj
	idxMap   map[int]int
	maxIdx   int
}

**Comment by circlestriker** [comment]
hi [situnan](https://github.com/situnan), did you just guess without real test?

**Comment by situnan** [comment]
This is an obvious problem and is a limitation of golang, map usage. You can test the small units yourself

**Comment by circlestriker** [comment]
in your design, you make more than 100,000 clients connect to one server?

**Comment by circlestriker** [comment]
"当存储很多client信息（200w）的时候", this wouldn't happen in a server in practice, I think this issue could be closed. @situnan
