### ISSUE TITLE
Feature: Redis is unreliable, and I would like to receive an alert notification when there is an error inserting data into Redis.

### ISSUE THREAD

**Issue by xuexihuang** [openimsdk/open-im-server#1475]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Solution Description

1，retry sometimes when redis sdk return error
2，send alerts when redis crash

### Benefits

can receive notifications promptly when Redis experiences exceptions

**Comment by cubxxw** [comment]
Sure, 
Based on the issue description, the user is requesting an alert notification when there is an error inserting data into Redis. To resolve this issue, you can implement the following solutions:

1. Implement a retry mechanism: Sometimes Redis SDK returns errors when inserting data. You can implement a retry mechanism to retry inserting data when Redis SDK returns an error.

2. Send alerts when Redis crashes: You can set up a monitoring system to detect when Redis crashes and send alerts to the user when it happens.
