### ISSUE TITLE
Bug: Network open-in-server server Error

### ISSUE THREAD

**Issue by luhaoling** [openimsdk/open-im-server#1486]
### What happened?

I have encountered the following issue and have been attempting to resolve it. I would like to bring this issue to your attention.

```
## Check OpenIM service name
!!! [1128 17:46:32] Call tree:
!!! [1128 17:46:32]  1: /openim/openim-server/scripts/install/openim-msgtransfer.sh:145 openim::msgtransfer::check(...)
!!! [1128 17:46:32]  2: /openim/openim-server/scripts/check-all.sh:82 source(...)
[31m!!! Error in /openim/openim-server/scripts/install/openim-msgtransfer.sh:64 [0m
  Error in /openim/openim-server/scripts/install/openim-msgtransfer.sh:64. 'PIDS=$(pgrep -f "${OPENIM_OUTPUT_HOSTBIN}/openim-msgtransfer")' exited with status 1
Call stack:
  1: /openim/openim-server/scripts/install/openim-msgtransfer.sh:64 openim::msgtransfer::check(...)
  2: /openim/openim-server/scripts/install/openim-msgtransfer.sh:145 source(...)
  3: /openim/openim-server/scripts/check-all.sh:82 main(...)
Exiting with status 1
```

[root@dev open-im-server]# docker compose up -d
[+] Building 0.0s (0/0)                                                                                                            
[+] Running 1/0
 ✘ Network open-im-server_server  Error                                                                                            
failed to create network open-im-server_server: Error response from daemon: Pool overlaps with other one on this address space

### What did you expect to happen?

none

### How can we reproduce it (as minimally and precisely as possible)?

none

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by luhaoling** [comment]
When you met the error, you should kill the network.
In this case, you may met the component error, such as kafaka disconnected. The 
best way is try to restart the disconnected component.

**Comment by luhaoling** [comment]
Kill the network command here:
>docker network ls
>docker network inspect "the network name"

If display the error: "Error response from daemon: error while removing network: network my-network id f4e637839398a11549ff8a187f41ec90351f65d35c1c09d32561db6e19471335 has active endpoints."
I hope this commands can help you.
>docker network inspect my-network
>docker network disconnect -f "network name" "the component name"

**Comment by cubxxw** [comment]
It is possible that the issue may be related to your network segment or other middleware that has been activated elsewhere. To resolve this, we suggest closing all middleware and restarting your system. We apologize for any inconvenience this may have caused and appreciate your patience as we work towards a solution.

**Comment by AndrewZuo01** [comment]
Running 'docker-compose down' in the conflicting server's folder and then restarting the server can resolve the issue.

**Comment by cubxxw** [comment]
> > Kill the network command here:
> > > docker network ls
> > > docker network inspect "the network name"
> > 
> > 
> > If display the error: "Error response from daemon: error while removing network: network my-network id f4e637839398a11549ff8a187f41ec90351f65d35c1c09d32561db6e19471335 has active endpoints." I hope this commands can help you.
> > > docker network inspect my-network
> > > docker network disconnect -f "network name" "the component name"
> 
> 是要把网络全删除了，然后在启动吗

是的，不然网络会冲突。docker network ls   查看网络
