### ISSUE TITLE
底层的另外一个问题：net库

### ISSUE THREAD

**Issue by situnan** [OpenIMSDK/Open-IM-Server#149]
1.看到底层使用net库，这样模式：goroutine-per-connection。当用户上到十几万连接的时候，内存消耗极大。go也会限制goroutine个数。所以大量连接情况下，这块底层一定是要改的。请参考：

https://github.com/panjf2000/gnet

**Comment by lesismal** [comment]
related: https://github.com/OpenIMSDK/Open-IM-Server/issues/116

可以试试我这个 
https://github.com/lesismal/nbio

**Comment by situnan** [comment]
thanks~我看看。

**Comment by skiffer-git** [comment]
thank you
That sounds like a pretty good idea.
