### ISSUE TITLE
注册问题

### ISSUE THREAD

**Issue by quan1065** [OpenIMSDK/Open-IM-Server#150]
打开体验demo，将配置ip 修改成自己服务器，成功注册一个手机号。之后退出登录再注册其它手机号时，填写密码之后点击下一步直接提示注册失败。 现在注册获取验证码 提示获取失败 请使用超级验证码
![image](https://user-images.githubusercontent.com/24366434/156277607-c1c7ac6a-3cb5-4e94-818d-ee7b5fad0946.png)

**Comment by skiffer-git** [comment]
Apply for mobile verification code service
