### ISSUE TITLE
Feature: add GetConversationList API

### ISSUE THREAD

**Issue by luhaoling** [openimsdk/open-im-server#1542]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Solution Description

Get the list of conversation according to whether they are top or not, and the order of the time they were sent.

### Benefits

Get the list of conversation.

**Comment by cubxxw** [comment]
+ [ ] add api code
+ [ ] add api docs
+ [ ] add api auto test
