### ISSUE TITLE
GroupOwner quit group cause panic

### ISSUE THREAD

**Issue by shungo2020** [OpenIMSDK/Open-IM-Server#155]
6081 [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xda0bbf]
   6082 
   6083 goroutine 208 [running]:
   6084 Open_IM/pkg/common/utils.GroupDBCopyOpenIM(0xc0002403c0, 0xc000428140)
   6085         /data/openim/Open_IM/pkg/common/utils/utils.go:94 +0x5f
   6086 Open_IM/internal/rpc/msg.setGroupInfo({0xc00019e0e0, 0xc000990480}, 0x0)
   6087         /data/openim/Open_IM/internal/rpc/msg/group_notification.go:58 +0x39
   6088 Open_IM/internal/rpc/msg.MemberQuitNotification(0xc000a84660)
   6089         /data/openim/Open_IM/internal/rpc/msg/group_notification.go:263 +0x10f
   6090 Open_IM/internal/rpc/group.(*groupServer).QuitGroup(0x10eed40, {0xc000a84660, 0x5003e6}, 0xc000a84660)
   6091         /data/openim/Open_IM/internal/rpc/group/group.go:556 +0x45e
   6092 Open_IM/pkg/proto/group._Group_QuitGroup_Handler({0x116cf80, 0xc0002f81c0}, {0x13e24e0, 0xc0004ba6c0}, 0xc000a84600, 0x0)
   6093         /data/openim/Open_IM/pkg/proto/group/group.pb.go:5046 +0x173
   6094 google.golang.org/grpc.(*Server).processUnaryRPC(0xc00053c820, {0x13f5210, 0xc000210000}, 0xc000788000, 0xc0001ba270, 0x1c223d0, 0x0)
   6095         /data/gopkg/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0xc8f
   6096 google.golang.org/grpc.(*Server).handleStream(0xc00053c820, {0x13f5210, 0xc000210000}, 0xc000788000, 0x0)
   6097         /data/gopkg/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0x9f3
   6098 google.golang.org/grpc.(*Server).serveStreams.func1.1()
   6099         /data/gopkg/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0x98
   6100 created by google.golang.org/grpc.(*Server).serveStreams.func1
   6101         /data/gopkg/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xef

**Comment by skiffer-git** [comment]
Upgrade to  v2.0.2
