### ISSUE TITLE
启动成功后，跑程序30000端口挂掉

### ISSUE THREAD

**Issue by FanZongZhi** [OpenIMSDK/Open-IM-Server#156]
ws_wrapper/ws_local_server/handle_func.go:61 启动后挂掉

![image](https://user-images.githubusercontent.com/72588784/156693318-6f0b2a2e-3505-4c5c-8046-8982c241f407.png)
![image](https://user-images.githubusercontent.com/72588784/156693327-dca93215-90c4-4e93-af37-0f3bfd84e175.png)
[openIM (1).log](https://github.com/OpenIMSDK/Open-IM-Server/files/8182829/openIM.1.log)

**Comment by C-isCoder** [comment]
服务端版本是多少，看日志参数如果是新版的话可能传参有问题，uid -> userID。另外，代码健壮性也有问题，动不动就 panic。

**Comment by FanZongZhi** [comment]
服务端版本2.0.0

**Comment by C-isCoder** [comment]
> 服务端版本2.0.0

那就是参数有问题 uid 改成 userID，也就是前端也要升级到2.0.0+
