### ISSUE TITLE
Docs: How to Compile the Latest Version of OpenIM 3.5 Based on Source Code <如何基于源代码编译openim3.5最新版本>

### ISSUE THREAD

**Issue by zisequkuai** [openimsdk/open-im-server#1597]
### Description

How to Compile the Latest Version of OpenIM 3.5 Based on Source Code

Step 1: Download the latest source code by cloning the Git repository.

Command:
# git clone https://github.com/openimsdk/open-im-server.git

Step 2: Navigate to the directory and modify the check-all.sh file after downloading.

After downloading, go to the downloaded package folder:

bash
Copy code
cd openim
[root@openim]# ls
open-im-server
cd open-im-server
Before proceeding, modify the 36th and 37th lines in the scripts/check-all.sh file by removing the '-n' after 'local' to avoid errors during 'make check'. Otherwise, you may encounter errors similar to the following:

!!! Error in /openim/openim/open-im-server/scripts/check-all.sh:37 
  Error in /openim/openim/open-im-server/scripts/check-all.sh:37.
  1))' exited with status 2
Call stack:

Step 3: Execute the following commands to compile:

(1) make init
(2) docker-compose up -d
(3) make build
During this step, you might encounter a security error related to go.sum. To resolve this, update the Go dependencies by setting the GOPROXY environment variable:

export GOPROXY=https://goproxy.cn,direct
Then continue with:

(4) make start
(5) make check
At this point, you have successfully compiled the latest version of OpenIM 3.5.

If you have any questions, feel free to reach out on WeChat: zeroknowledgevc.

中文版本：
如何基于源代码编译openim3.5最新版本

第一步：先现在最新的源代码，git clone出来
命令如下：
# git clone https://github.com/openimsdk/open-im-server.git 

第二步：切换到目录，修改check-all.sh文件
下载后
切换到下载包文件夹下
 cd openim/
[root@openim]# ls
open-im-server

cd open-im-server

要先修改scripts/check-all.sh 里的 36，37行，把local 后面的-n去掉，后面make check才不会出错

不然会出现下面类似的错误

!!! Error in /openim/openim/open-im-server/scripts/check-all.sh:37 
  Error in /openim/openim/open-im-server/scripts/check-all.sh:37.
  1))' exited with status 2
Call stack:

第三步：make
（1）make init
（2）docker-compose up -d
（3）make build

这一步有可能会出现错误消息如下
go.sum:     h1:HKqjLZSMjD7dafsfasdfafec59VV694Yfqnj9SIVotzDSPWgAei2Tg=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
make[1]: *** [go.build.linux_amd64.openim-msgtransfer] Error 1
make: *** [build] Error 2
错误。

这个错误是因为go要更新一些依赖包，需要下载更新，但海外代理可能有问题，有更换下才行

export GOPROXY=https://goproxy.cn,direct
设置该环境变量即可。

（4）make start
（5）make check

到此已经编译成功最新版本openim 3.5

如果有任何微信欢迎wechat咨询WeChat：zeroknowledgevc

**Comment by cubxxw** [comment]
Thank you for keeping a record. I believe it is necessary.

**Comment by cubxxw** [comment]
The issue has been successfully resolved.
