### ISSUE TITLE
群成员数量限制/默认公共只读频道来推送消息/自动（批准）入群可配置

### ISSUE THREAD

**Issue by bigdong89** [OpenIMSDK/Open-IM-Server#16]
首先谢谢作者的工作，结合实际，提下我的问题
1. 文档里没有展示测试结果，群组人数限制、单机服务人群上线等没有测试结果可参考
2. 需要一个默认“消息”频道，用来群发给所有用户消息
3. 入群分为自动入群和批准入群，目前好像只有批准才能入群
拉个分支咱们搞吧

**Comment by jankuo** [comment]
自动入群可以自己调用管理员服务器端 API 把用户拉入群

**Comment by skiffer-git** [comment]
SetGroupVerification modify join group verification
