### ISSUE TITLE
token签发逻辑有误  有很大的安全性问题  ！ _, err := imdb.GetUserByUserID(req.FromUserID) 这句没意义

### ISSUE THREAD

**Issue by YitianJiang** [OpenIMSDK/Open-IM-Server#161]
//首先，是用户登录时签发token，用户之后拿着token进行各种需要鉴权的操作，token标识着用户是张三而不是李四，且让张三不能冒充李四
func (rpc *rpcAuth) UserToken(_ context.Context, req *pbAuth.UserTokenReq) (*pbAuth.UserTokenResp, error) {
	log.NewInfo(req.OperationID, "UserToken args ", req.String())
//其次
//1.如果是手机短信登录，应该在用户请求验证码时就校验用户是否存在，如果不存在，则提示用户注册，存在，则发送验证码到用户手机, 并把校验码缓存到redis，key为用户手机号，用户填完验证码并让前端把验证码发到后端让其签发token，后端根据手机号从redis中取出之前发过的校验码并和前端刚刚发过来的校验码进行对比，如果正确，则签发token
//2.如果是账号密码登录，应该到根据用户名到数据库里面查有没有那条记录，如果没有，则提示用户注册，如果有，则还要校验密码是否正确，密码正确才给用户签发token
//3.无论是那种方式，校验手机校验码或者校验密码，都是确认"用户确实是数据库里面那条记录的所有者"才能签发token，而不是根据用户id，到数据库里面查一下记录是否存在就够了，如果是这样的话，只要知道任何注册用户的id就能签发该用户的token，代表该用户进行其能进行的任何操作，安全性何在？
	_, err := imdb.GetUserByUserID(req.FromUserID)
	if err != nil {
		log.NewError(req.OperationID, "GetUserByUserID failed ", err.Error(), req.FromUserID)
		return &pbAuth.UserTokenResp{CommonResp: &pbAuth.CommonResp{ErrCode: constant.ErrDB.ErrCode, ErrMsg: constant.ErrDB.ErrMsg}}, nil
	}

**Comment by skiffer-git** [comment]
Generate token with secret
