### ISSUE TITLE
yaml配置文件的读取在那个地方调用的

### ISSUE THREAD

**Issue by YitianJiang** [OpenIMSDK/Open-IM-Server#162]
func init() {
	//path, _ := os.Getwd()
	//bytes, err := ioutil.ReadFile(path + "/config/config.yaml")
	// if we cd Open-IM-Server/src/utils and run go test
	// it will panic cannot find config/config.yaml

	cfgName := os.Getenv("CONFIG_NAME")
	if len(cfgName) == 0 {
		cfgName = Root + "/config/config.yaml"
	}

	viper.SetConfigFile(cfgName)
	err := viper.ReadInConfig()
	if err != nil {
		panic(err.Error())
	}
	bytes, err := ioutil.ReadFile(cfgName)
	if err != nil {
		panic(err.Error())
	}
	if err = yaml.Unmarshal(bytes, &Config); err != nil {
		panic(err.Error())
	}
	fmt.Println("load config: ", Config)
}

**Comment by skiffer-git** [comment]
init
