### ISSUE TITLE
db failed

### ISSUE THREAD

**Issue by YitianJiang** [OpenIMSDK/Open-IM-Server#163]
token获取：
post {{openIM-api}}/auth/user_token
 {
  "secret": "tuoyun",
  "platform": 1,
  "userID": "openIM1111",
  "operationID": "asdfasdfsadf"
}
返回：
{
    "errCode": 802,
    "errMsg": "db failed",
    "data": {
        "userID": "openIM1111",
        "token": "",
        "expiredTime": 0
    }
}

**Comment by skiffer-git** [comment]
grep asdfasdfsadf  logs/*

**Comment by ShanDongChenGuanXi** [comment]
这个应该是im服务的mysql 数据库没有你这个用户
