### ISSUE TITLE
image can not be sened

### ISSUE THREAD

**Issue by jamesdurant** [openimsdk/open-im-server#1633]
### What happened?

F12 can be found 

http://ip:10005/openim/openim/temp/2023/12/29/

### What did you expect to happen?

1

### How can we reproduce it (as minimally and precisely as possible)?

1

### version

<details>
```console
$ {name} version
# paste output here
```
</details>
1

### Cloud provider

<details>
</details>
1

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
Please note that there are several ways to configure this. Firstly, you need to check if the local 'dig' is set up correctly. If it is not installed, please install it and redeploy. Secondly, you need to set the 'OPENIM_IP' environment variable. This variable represents the public IP address through which you provide services externally.

To obtain this IP, you can use the following command:
```
export OPENIM_IP="your public IP"
curl ifconfig.me
```

Thank you for your attention to these details.

**Comment by skiffer-git** [comment]
https://docs.openim.io/guides/gettingstarted/imsourcecodedeployment
