### ISSUE TITLE
服务器打印大量错误日志

### ISSUE THREAD

**Issue by 39499740** [OpenIMSDK/Open-IM-Server#165]
服务器版本2.0，客户端版本2.0

日志级别2

服务器打印大量日志。
错误原因未知

<img width="734" alt="image" src="https://user-images.githubusercontent.com/29425312/156961108-83f82bd7-55b2-4b8e-b87f-47abff1415d8.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/29425312/156961124-628f21d1-30db-4d10-8cf4-12b3a593d193.png">
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/29425312/156961140-d0157fa6-7adb-4d66-a1ba-1c0da939caca.png">
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/29425312/156961167-caab2aed-4da9-40db-96fb-c23e788c9e9e.png">
<img width="607" alt="image" src="https://user-images.githubusercontent.com/29425312/156961199-ab4ef6a2-182b-4bf8-982e-05b52e31c8e5.png">
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/29425312/156961215-b36e9602-6e66-4b1c-8e0a-07f762f5f150.png">

**Comment by 39499740** [comment]
![image](https://user-images.githubusercontent.com/29425312/156987688-8f496c12-4b7c-46cd-bc64-c5138ee9bd5c.png)
这是出错前的最后一个请求

**Comment by 39499740** [comment]
![QQ20220307-152541-HD](https://user-images.githubusercontent.com/29425312/156987739-ba9606c1-cd0e-40b9-bfe6-b705485a7a7b.gif)

**Comment by 39499740** [comment]
今天早上目睹了这样的错误，没有任何请求，直接开始报错

推测报错前发生了一次错误

![image](https://user-images.githubusercontent.com/29425312/157145430-3bb05216-c920-4740-8e66-b192472d4126.png)

**Comment by skiffer-git** [comment]
Update image this Friday
