### ISSUE TITLE
Bug: update mongo password error

### ISSUE THREAD

**Issue by luhaoling** [openimsdk/open-im-server#1659]
### What happened?

I have successful start the project( IM & Chat).When I change the mongo.password in .env and config/config.yaml, I met the follow error.

Starting component...
Checking components Round 1...
Starting Mongo failed, connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.;ths addr is:172.28.0.1:37017
Checking components Round 2...
Starting Mongo failed, connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.;ths addr is:172.28.0.1:37017
Checking components Round 3...
Starting Mongo failed, connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.;ths addr is:172.28.0.1:37017
Checking components Round 4...
Starting Mongo failed, connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.;ths addr is:172.28.0.1:37017
Checking components Round 5...
Starting Mongo failed, connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.;ths addr is:172.28.0.1:37017
Checking components Round 6...
Starting Mongo failed, connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.;ths addr is:172.28.0.1:37017

The excute commands as follow:
# Before change the password
>make init
>docker compose up -d
>make build
>make start
>make check
# Change the password of .env and config/config.ymal. Change the mongo.password to "openIM123456"
# After change the password
>docker compose down
>docker compose up -d
>make build
>make start

### What did you expect to happen?

none

### How can we reproduce it (as minimally and precisely as possible)?

none

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

### What did you expect to happen?

none

### How can we reproduce it (as minimally and precisely as possible)?

none

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
The issue has been successfully resolved. For instructions on modifying the username, please refer to the corresponding deployment documentation for both the source code and Docker deployment. Thank you for your attention to this matter.
