### ISSUE TITLE
Bug: cannot change API_OPENIM_PORT

### ISSUE THREAD

**Issue by AndrewZuo01** [openimsdk/open-im-server#1669]
### What happened?

afterI changed API_OPENIM_PORT according to file, I got error 
```
{
    "errCode": 500,
    "errMsg": "Post \"http://172.28.0.1:40002/auth/user_token\": read tcp 172.28.0.9:59842-\u003e172.28.0.1:40002: read: connection reset by peer",
    "errDlt": ""
}
```

### What did you expect to happen?

It should work for log in

### How can we reproduce it (as minimally and precisely as possible)?

Modify .env and config files to change API_OPENIM_PORT to 40002 then docker compose up -d, build, start, and check. All checks will pass. After that, try creating an account and logging in

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
The issue has been resolved. In order to modify the internal and external ports of the existing docker-compose, we need to address the lack of Nginx for both the ws and api web services. As a result, the web service is currently inaccessible and requires testing on a PC.
