### ISSUE TITLE
关于连接数的测试问题

### ISSUE THREAD

**Issue by cocoyes** [OpenIMSDK/Open-IM-Server#170]
请问是否做过2核16G最大并发连接数（即真实客户端数）的相关测试呢？

**Comment by ilovesusu** [comment]
非常期待能发布压力测试的结果

**Comment by skiffer-git** [comment]
Use the latest code for test 
1. main.exe -on 10000 -sn 0 -mn 0 -t 0
2. 2、main.exe -on 10000 -sn 100 -mn 1000 -t 10
