### ISSUE TITLE
Bug: macOS source code deployment anomaly.

### ISSUE THREAD

**Issue by skiffer-git** [openimsdk/open-im-server#1700]
### What happened?

<img width="673" alt="226597b8602c1fafd2ff949d06365ea" src="https://github.com/openimsdk/open-im-server/assets/72860476/33e7c477-6c38-45cf-a116-0769e7a6a324">

<img width="1458" alt="5839bba08207e5a40a46200c522b189" src="https://github.com/openimsdk/open-im-server/assets/72860476/ac14fb49-f06b-406d-8f58-80bef242691e">
<img width="1263" alt="246df33afe467102362d8c97872b57d" src="https://github.com/openimsdk/open-im-server/assets/72860476/6fd4a90c-48b9-477d-8f08-d8c05c1d56e3">

### What did you expect to happen?

normal

### How can we reproduce it (as minimally and precisely as possible)?

1) MongoDB cannot connect; 
2) 'make start' (IM and Chat) throws an error.

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
Hello,

It seems that there might be a slight difference between the Docker network on macOS and Linux, possibly due to the kernel version. To troubleshoot this, it's worth considering changing the IP address from 172.28.0.1 to 127.0.0.1 on the macOS machine. This adjustment could help in resolving the issue.

**Comment by cubxxw** [comment]
The issue has been successfully resolved, and you can find the documentation for your reference at: https://docs.openim.io/zh-Hans/guides/gettingStarted/mac-deployment-guide.
