### ISSUE TITLE
[Other]: The installation of mongodb in the old version of Docker failed to connect in the latest version.

### ISSUE THREAD

**Issue by withchao** [openimsdk/open-im-server#1732]
### What would you like to share?

Starting Mongo failed, connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.;

**Comment by skiffer-git** [comment]
The instructions translate to English as follows:

(1) Enter the MongoDB container;
(2) Execute `./docker-entrypoint-initdb.d/mongo-init.sh`;
(3) Change the username and password
mongo:
  uri: ''
  username: openIM
  password: openIM123456

**Comment by skiffer-git** [comment]
Remember to first perform a 'git pull' to update the 'mongo-init.sh' script

**Comment by darrennong** [comment]
# /docker-entrypoint-initdb.d/mongo-init.sh
Current Mongosh Log ID: 65c1f930a72865cab0571936
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.6.0
Using MongoDB:          6.0.2
Using Mongosh:          1.6.0

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

test> use admin
switched to db admin
admin> db.auth('root', 'openIM123')
MongoServerError: Authentication failed.
admin>
