### ISSUE TITLE
get_user_info请求400

### ISSUE THREAD

**Issue by lmj2001** [OpenIMSDK/Open-IM-Server#175]
![Screen Shot 2022-03-14 at 7 16 16 PM](https://user-images.githubusercontent.com/73374331/158161999-0092c283-0d99-4403-b810-fed0a763f31f.png)
我想问问,我的服务器部署成功了,注册接口测试没问题,但是登录出现了错误,我发现就是get_user_info出错了
是我没有注意到什么细节吗

**Comment by QnFFF** [comment]
+1

**Comment by skiffer-git** [comment]
userID->userIDList
