### ISSUE TITLE
jssdk 服务端内存占用太高，建议官方优化下。

### ISSUE THREAD

**Issue by mwf564** [OpenIMSDK/Open-IM-Server#176]
运行环境：docker 独立部署open-im-server服务，4G内存的运行环境，启动不久open_im_sdk_ser占用总内存的92%以上。导致前端业务卡顿。

**Comment by skiffer-git** [comment]
Memory leak on user exit

**Comment by skiffer-git** [comment]
your suggestion have been incorporated in the plan
