### ISSUE TITLE
Docs: <description>openim-server 3.5 cannot send image, audio, video and other file information

### ISSUE THREAD

**Issue by chengzhitaotao** [openimsdk/open-im-server#1765]
### Description

openim-server 3.5 | docker部署  需要怎么配置才能发送图片消息

**Comment by cubxxw** [comment]
I'm having trouble sending images after the deployment. Could you please take a look at this document about configuration: https://github.com/openimsdk/open-im-server/blob/main/docs/contrib/environment.md.

**Comment by skiffer-git** [comment]
Please refer to this English document and follow the procedure accordingly.
https://docs.openim.io/guides/gettingStarted/imSourceCodeDeployment
