### ISSUE TITLE
Feature:  Merge Deployment Scripts from main to release-v3.5 Branch

### ISSUE THREAD

**Issue by cubxxw** [openimsdk/open-im-server#1773]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

✅ Yes

### Problem Description

I would like to propose merging certain deployment scripts currently in the `main` branch into the `release-v3.5` branch. The aim is to enhance the deployment quality of the `release-v3.5` branch.

### Solution Description

1. **Scripts to Merge:** Identify and list the specific deployment scripts in `main` that are candidates for merging.
2. **Quality Assurance:** Ensure that these scripts improve or at least maintain the current deployment quality in `release-v3.5`.
3. **Testing Before Merging:** It's crucial that our testing team conducts extensive verification tests on the proposed changes before the merge. This includes functional testing, compatibility checks, and performance assessments to ensure stability and efficiency.

### Benefits

I believe this step will significantly contribute to the robustness and reliability of our `release-v3.5` deployments. Looking forward to your thoughts and feedback on this proposal.

### Potential Drawbacks

no

### Additional Information

no

**Comment by longyuqing112** [comment]
There is no Milestone setup for v3.5
