### ISSUE TITLE
Feature: add a webhook example that send a message and return this message

### ISSUE THREAD

**Issue by luhaoling** [openimsdk/open-im-server#1782]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Solution Description

Add a webhook message that send a message and return this message.

### Benefits

Add a webhook example that is benefit to let user know how to use webhook.

**Comment by cubxxw** [comment]
The issue has been resolved, but it has not been properly linked.
