### ISSUE TITLE
Bug: the callback of  CallbackSingleMsgRead unuse

### ISSUE THREAD

**Issue by luhaoling** [openimsdk/open-im-server#1785]
### What did you expect to happen?

the callback of  CallbackSingleMsgRead unuse

### How can we reproduce it (as minimally and precisely as possible)?

fix it

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by AndrewZuo01** [comment]
test

**Comment by longyuqing112** [comment]
Milestone is not set, please add v3.5
