### ISSUE TITLE
argsValidate  bug?

### ISSUE THREAD

**Issue by TQCasey** [OpenIMSDK/Open-IM-Server#179]
本地mac系统搭建调试系统，怎么发消息都不会push，看log发现一路都是 invalidate msg ,看到这里
是不是写错了？ 我改成下面那样就OK了

```
func (ws *WServer) argsValidate(m *Req, r int32) (isPass bool, errCode int32, errMsg string, returnData interface{}) {
	switch r {
	case constant.WSSendMsg | constant.WSSendSignalMsg: // 这里是不是有有问题呀，
```

这里是不是应该是 

```
	case constant.WSSendMsg:
		fallthrough
	case constant.WSSendSignalMsg:
```

**Comment by junkeWu** [comment]
mac搭建调试环境，首先，ws服务的10003接口应该修改，其次那个服务有bug, 以下是我修改的一些东西：
目录：Open-IM-Server/cmd/Open-IM-SDK-Core/ws_wrapper/cmd/open_im_sdk_server.go
1. 注释 // var openIMWsAddress, openIMApiAddress *string ，这俩个变量没有赋值，会空指针。
2. switch sysType {

	case "darwin":
		// ws_local_server.InitServer(&sdk_struct.IMConfig{ApiAddr: *openIMApiAddress,
		// 	WsAddr: *openIMWsAddress, Platform: utils.OSXPlatformID, DataDir: "./"})    // 开源方所写的
		ws_local_server.InitServer(&sdk_struct.IMConfig{ApiAddr: "http://127.0.0.1:10002",
			WsAddr: "http://127.0.0.1:10001", Platform: utils.OSXPlatformID, DataDir: "./"}) // 我本地修改
			
我想，如果没有其他问题，同是mac，应该没有其他问题。

**Comment by skiffer-git** [comment]
Version 3.0 has been updated, and older versions are no longer maintained. We welcome you to use the new version, and if you encounter any problems, please provide feedback. We will respond actively.
