### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shungo2020** [OpenIMSDK/Open-IM-Server#180]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xf54367]

goroutine 1066 [running]:
Open_IM/internal/rpc/msg.(*rpcChat).SendMsg(0x1141020, {0xc0000aa5f0, 0x500d86}, 0xc0000aa5f0)
	/data/openim/openim203/Open_IM/internal/rpc/msg/send_msg.go:248 +0x2187
Open_IM/pkg/proto/chat._Chat_SendMsg_Handler({0x112a880, 0xc0000aa320}, {0x1443118, 0xc00046ef00}, 0xc0000a10e0, 0x0)
	/data/openim/openim203/Open_IM/pkg/proto/chat/chat.pb.go:895 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005811e0, {0x1456e10, 0xc000010000}, 0xc0005b8600, 0xc00046e5d0, 0x1cc3548, 0x0)
	/data/gopkg/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0005811e0, {0x1456e10, 0xc000010000}, 0xc0005b8600, 0x0)
	/data/gopkg/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0x9f3
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/data/gopkg/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/data/gopkg/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xef

version: v2.0.3

**Comment by shungo2020** [comment]
不存在的groupid造成，msgToMQ.MsgData会为空
需要检查一下msgToMQ.MsgData是否为空

**Comment by skiffer-git** [comment]
Use the latest image
