### ISSUE TITLE
Bug: EOF when register but passed all check

### ISSUE THREAD

**Issue by AndrewZuo01** [openimsdk/open-im-server#1801]
### What happened?

I got EOF error when register, fixed after changing all 172 address to 127.0.0.1

### What did you expect to happen?

since I passed all check (both openim and chat), all components were started, and grep showed openim and chat are running, it should be able to register

### How can we reproduce it (as minimally and precisely as possible)?

Just normally deploy. server version is v3.5 chat is v1.5

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
Dear @AndrewZuo01 ,

I recall that the solution involved configuring the chat and server components to achieve the desired outcome. However, the underlying issue stemmed from the previous use of Docker, which resulted in network contamination within the operating system. As a result, attempting to launch this network segment in a new project led to complications. Therefore, I believe the correct approach would be to establish a new network segment and then proceed with the startup process as follows:

```bash
export DOCKER_BRIDGE_SUBNET=172.29.0.0/16
make init #y
```

Your attention to this matter is greatly appreciated, and I am confident that implementing the suggested steps will lead to a successful outcome.

Thank you for your cooperation.

Sincerely,
@cubxxw
