### ISSUE TITLE
最新版启动后,openImSdkWsPort 30000这个始终无法启动, #183

### ISSUE THREAD

**Issue by yhuaqiang** [OpenIMSDK/Open-IM-Server#184]
自从官方更新至2.0之后,就在默认配置基础上修改了配置,主要是数据库名和密码,已经managerUID等安全方面的配置,2.0是运行没问题.
现在使用2.0.4的,在默认配置基础上进行了同样的修改,去无法启动30000,等了很久,check也是未启动, web端无法连接.
服务端报错:
openImSdkWsPort service does not start normally,not initiated port is 30000
please check ../logs/openIM.log
sdk端报错
WebSocket connection to 'xxx' failed: Error during WebSocket handshake: Unexpected response code: 502

配置文件已经检查过,和默认的相比,除了更改了几个字段,其他的都一致.
麻烦测试下吧

**Comment by yhuaqiang** [comment]
配置文件也经过BeyondCompare的比对,除了字段内容,其他完全一致

**Comment by yhuaqiang** [comment]
docker-copos

**Comment by KissSt** [comment]
你好这个问题怎么解决的
