### ISSUE TITLE
Calling the http://x.x.x.x:10002/auth/user_token API returns a 404 page not found

### ISSUE THREAD

**Issue by heminghaoa** [openimsdk/open-im-server#1964]
### Description

When I call the [API](http://x.x.x.x:10002/auth/user_token) it returns 404 page not found，but other apis can return normally.

### Screenshots

<img width="628" alt="image" src="https://github.com/openimsdk/open-im-server/assets/124542011/285550bc-5d29-4e31-9c18-3ef24156b9d1">

<img width="621" alt="image" src="https://github.com/openimsdk/open-im-server/assets/124542011/56036a60-1b01-46ba-ae19-d3305f548408">

**Comment by skiffer-git** [comment]
Which version? It can be upgraded to the latest version.

**Comment by cubxxw** [comment]
Could you please confirm if the API requests are being handled correctly? Thank you.
