### ISSUE TITLE
Bug: delay in sending messages after enable the callback

### ISSUE THREAD

**Issue by luhaoling** [openimsdk/open-im-server#2008]
### What happened?

When callback is enabled, there is a delay in sending messages. such as send message，create group。

### What did you expect to happen?

fix it.

### How can we reproduce it (as minimally and precisely as possible)?

Enable the callback, and send message.

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by skiffer-git** [comment]
this issue has fixed in release-v3.8, I recommend you update to new version. If you run into any new issues, please reopen this issue or create a new one.
