### ISSUE TITLE
[BUG] MarkMessage没有具体实现

### ISSUE THREAD

**Issue by YitianJiang** [OpenIMSDK/Open-IM-Server#202]
你这个mongodb 和mysql消费消息的时候，为了避免重复消费消息，你写了个
history_msg_handler.go 97行  sess.MarkMessage(msg, "")
**但是saram提供的这个接口是让你自己去实现 
saram 并没有实现这MarkMessage个接口**
我觉得你想做的应该是：消费完消息后把消息的唯一标识写进redis里面
然后，每次消费消息前都去redis里面查这条消息的标识，有，就被消费过，会导致重复消费
![Snipaste_2022-04-07_15-54-41](https://user-images.githubusercontent.com/36124775/162149926-8aa05ad1-1736-4b0b-aa61-93242927e060.png)

**Comment by fananchong** [comment]
https://github.com/Shopify/sarama/blob/main/examples/consumergroup/main.go

**Comment by fananchong** [comment]
@YitianJiang 楼主，你大概没用过 sarama 库的消费组，见上链接 example 。
网上例子也很多，搜几篇文章看下即可，就会懂，，，

**Comment by fananchong** [comment]
https://github.com/OpenIMSDK/Open-IM-Server/issues/205 这个问题，帮忙鉴定下，感觉这里是这个 IM 框架的硬伤，牛逼吹不起来了

**Comment by yiippee** [comment]
> #205 这个问题，帮忙鉴定下，感觉这里是这个 IM 框架的硬伤，牛逼吹不起来了

我看源码有好多硬伤啊，你可以看看mysql操作那块，都是for 循环操作mysql，且多个操作没有事务保证

**Comment by yiippee** [comment]
没感觉这里的 sess.MarkMessage(msg, "") 做法有啥问题

**Comment by YitianJiang** [comment]
sess.MarkMessage(msg, "") 这个 saram确实有实现，之前没看到，但是saram的实现并没有进行消息提交
![3](https://user-images.githubusercontent.com/36124775/164147485-9b41e712-8ec7-4cec-bc25-feaf19a51e15.png)
_**但是好像作者用错了**_

因为配置文件里面写的是自动提交
这样会有一个问题
如果offset提交后，消费者并没有把offset前的消息处理完就crash了
下次消费者起来时，会从之前提交的offset处拉取消息
这就导致了一部分消息的丢失

为了避免消息丢失
应该采用手动提交
作者认为 sess.MarkMessage(msg, "")会把offset提交到kafka
所以就在自动提交模式下用了MarkMessage

但是：
### **sess.MarkMessage(msg,** "") 到底会不会把offset提交到kafka ?**

我做了个实验验证了下
实验过程：
在MarkMessage处打个断点
再在MarkMessage后return处打个断点
![4](https://user-images.githubusercontent.com/36124775/164148205-595c88fe-aff1-41b8-a48f-de23b4f82f8a.png)

先在前端发个消息，比如发个 5
![6](https://user-images.githubusercontent.com/36124775/164148269-9f854f26-591a-4b3c-b954-408470af116a.png)

这时第一个断点命中，看下offset是多少
![1 1](https://user-images.githubusercontent.com/36124775/164146010-6812344d-b34c-47a6-adde-38f8b3a3bf22.png)
![1 2](https://user-images.githubusercontent.com/36124775/164146020-9a1da47a-3f22-4337-8947-92b97542faab.png)
offset是22
resume
命中第二个断点时，再看下offset是多少
![2 1](https://user-images.githubusercontent.com/36124775/164146190-e6801b89-cc86-4428-b5df-924aecedc602.png)
![2 2](https://user-images.githubusercontent.com/36124775/164146200-8cd3f479-8697-475a-8af7-a07613708947.png)

如果命中第二个断点时offset增加了，就能得出结论：### **会发送offset**
如果没有增加 就不会发送offset
这里看到，MarkMessage被调用后，offset没有改变，还是22
所以：
我认为
sess.MarkMessage(msg, "") 这个写法是有问题的，应该改成手动提交

**Comment by youmisun** [comment]
> **_sess.MarkMessage(msg, "") 这个 saram确实有实现，之前没看到，但是saram的实现并没有进行消息提交_** ![3](https://user-images.githubusercontent.com/36124775/164147485-9b41e712-8ec7-4cec-bc25-feaf19a51e15.png) _**但是好像作者用错了**_
> 
> 因为配置文件里面写的是自动提交 这样会有一个问题 如果offset提交后，消费者并没有把offset前的消息处理完就crash了 下次消费者起来时，会从之前提交的offset处拉取消息 这就导致了一部分消息的丢失
> 
> 为了避免消息丢失 应该采用手动提交 作者认为 sess.MarkMessage(msg, "")会把offset提交到kafka 所以就在自动提交模式下用了MarkMessage
> 
> 但是：
> 
> ### **sess.MarkMessage(msg,** "") 到底会不会把offset提交到kafka ?**
> 我做了个实验验证了下 实验过程： 在MarkMessage处打个断点 再在MarkMessage后return处打个断点 ![4](https://user-images.githubusercontent.com/36124775/164148205-595c88fe-aff1-41b8-a48f-de23b4f82f8a.png)
> 
> 先在前端发个消息，比如发个 5 ![6](https://user-images.githubusercontent.com/36124775/164148269-9f854f26-591a-4b3c-b954-408470af116a.png)
> 
> 这时第一个断点命中，看下offset是多少 ![1 1](https://user-images.githubusercontent.com/36124775/164146010-6812344d-b34c-47a6-adde-38f8b3a3bf22.png) ![1 2](https://user-images.githubusercontent.com/36124775/164146020-9a1da47a-3f22-4337-8947-92b97542faab.png) offset是22 resume 命中第二个断点时，再看下offset是多少 ![2 1](https://user-images.githubusercontent.com/36124775/164146190-e6801b89-cc86-4428-b5df-924aecedc602.png) ![2 2](https://user-images.githubusercontent.com/36124775/164146200-8cd3f479-8697-475a-8af7-a07613708947.png) 这里看到，MarkMessage被调用后，offset没有改变，还是22
> 
> 如果命中第二个断点时offset增加了，就能得出结论：**MarkMessage会向kafka发送offset** 如果没有增加 就不会发送offset 所以： 作者调用的MarkMessage根本就没有向kafka提交offset 我认为 sess.MarkMessage(msg, "") 这个写法是有问题的，应该改成手动提交
> 
> 参考：[Golang中如何正确的使用sarama包操作Kafka？](https://cdmana.com/2021/08/20210812104319088e.html)

文章不是说自动提交不是要等1秒钟吗？你两次查看offset界面里的last commit那一列时间好像都是一样的哦，是不是要刷新一下界面？有没有一种可能打断点会影响自动提交的线程运行呢
