### ISSUE TITLE
if !isSenderSync && msgKey == msgFromMQ.MsgData.SendID  这种情况什么时候会出现

### ISSUE THREAD

**Issue by YitianJiang** [OpenIMSDK/Open-IM-Server#203]
history_msg_handler.go 67行
![Snipaste_2022-04-07_21-33-45](https://user-images.githubusercontent.com/36124775/162211476-03e7bd82-60ce-4da4-ac65-8d34aa567ea9.png)

**Comment by showurl** [comment]
同步推送给发送方，可能发送方同时登录了多台设备。
if !isSenderSync && msgKey == msgFromMQ.MsgData.SendID {
  // 不做任何处理；是指如果设置改消息不同步推送给发送方，则不需要做任何处理；否则推送给该用户
}
