### ISSUE TITLE
submodule 拉不下来

### ISSUE THREAD

**Issue by fananchong** [OpenIMSDK/Open-IM-Server#204]
D:\github>git clone https://github.com/OpenIMSDK/Open-IM-Server.git --recursive
Cloning into 'Open-IM-Server'...
remote: Enumerating objects: 12763, done.
remote: Counting objects: 100% (2122/2122), done.
remote: Compressing objects: 100% (510/510), done.
remote: Total 12763 (delta 1787), reused 1733 (delta 1571), pack-reused 10641
Receiving objects: 100% (12763/12763), 3.59 MiB | 3.14 MiB/s, done.
Resolving deltas: 100% (8317/8317), done.
Submodule 'cmd/Open-IM-SDK-Core' (https://github.com/OpenIMSDK/Open-IM-SDK-Core.git) registered for path 'cmd/Open-IM-SDK-Core'
Cloning into 'D:/github/Open-IM-Server/cmd/Open-IM-SDK-Core'...
remote: Enumerating objects: 9036, done.
remote: Counting objects: 100% (1593/1593), done.
remote: Compressing objects: 100% (803/803), done.
remote: Total 9036 (delta 1179), reused 1149 (delta 768), pack-reused 7443
Receiving objects: 100% (9036/9036), 2.02 MiB | 2.17 MiB/s, done.
Resolving deltas: 100% (6422/6422), done.
fatal: remote error: upload-pack: not our ref 9d67999cec3e4a9792c33a95e5514a945df54052
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'cmd/Open-IM-SDK-Core', but it did not contain 9d67999cec3e4a9792c33a95e5514a945df54052. Direct fetching of that commit failed.

**Comment by skiffer-git** [comment]
use  v2.2.0
