### ISSUE TITLE
Bug: When a user has too many messages, fetching messages using the SDK will fail, and the entire interface will be unable to display any messages. 

### ISSUE THREAD

**Issue by duola297** [openimsdk/open-im-server#2138]
### What happened?

When a user has too many messages, fetching messages using the SDK will fail, and the entire interface will be unable to display any messages. I'm not sure if this is a limitation or an error. Where can I set this max value or resolve this issue
![image](https://github.com/openimsdk/open-im-server/assets/99168066/53d526ba-b3cb-45ad-b0e8-baf640cc9650)

### What did you expect to happen?

To solve this problem

### How can we reproduce it (as minimally and precisely as possible)?

Perhaps allow a user to receive a large number of messages, and then call the SDK to pull information?

### version

3.0

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
Would you kindly consider updating this version, as it seems a bit outdated? Thank you for your attention to this matter.
