### ISSUE TITLE
open_im_push 始终无法启动

### ISSUE THREAD

**Issue by he3210** [OpenIMSDK/Open-IM-Server#214]
从 openIM.log 报错上来看，是因为无法连接 kafka。报错的日志显示，服务 open_im_push 运行时，连接的 ip:port 是：127.0.0.1:9092，但我在 config.yaml 中配置的是 [192.168.3.8:19092]，

并且我在函数 NewMConsumerGroup 中打了 log，在日志中打印的 addr 为 [192.168.3.8:19092]
我不知道在 kafka 消费时，为啥连接的是 127.0.0.1:9092，导致open_im_push 服务无法启动

openIM.log 中打印的 addr 和报错分别为：
NewMConsumerGroup addr:  [192.168.3.8:19092]

panic: RegisterHandleAndConsumer err: dial tcp 127.0.0.1:9092: connect: connection refused

goroutine 58 [running]:
Open_IM/pkg/common/kafka.(*MConsumerGroup).RegisterHandleAndConsumer(0xc000531300, {0x1484f50, 0x1c4da70})
	/Open-IM-Server/pkg/common/kafka/consumer_group.go:52 +0xd4
created by Open_IM/internal/push/logic.Run
	/Open-IM-Server/internal/push/logic/init.go:38 +0xa5

报错的函数  consumer_group.go:52  是如下第二个函数 RegisterHandleAndConsumer 中的   panic 一行：
func NewMConsumerGroup(consumerConfig *MConsumerGroupConfig, topics, addr []string, groupID string) *MConsumerGroup {
	config := sarama.NewConfig()
	config.Version = consumerConfig.KafkaVersion
	config.Consumer.Offsets.Initial = consumerConfig.OffsetsInitial
	config.Consumer.Return.Errors = consumerConfig.IsReturnErr
	fmt.Println("NewMConsumerGroup addr: ", addr)   // 这里把 addr 打印出来了，是: [192.168.3.8:19092]
	client, err := sarama.NewClient(addr, config)
	if err != nil {
		panic(err.Error())
	}
	consumerGroup, err := sarama.NewConsumerGroupFromClient(groupID, client)
	if err != nil {
		panic(err.Error())
	}
	return &MConsumerGroup{
		consumerGroup,
		groupID,
		topics,
	}
}
func (mc *MConsumerGroup) RegisterHandleAndConsumer(handler sarama.ConsumerGroupHandler) {
	ctx := context.Background()
	for {
		err := mc.ConsumerGroup.Consume(ctx, mc.topics, handler)
		if err != nil {
			panic(fmt.Sprintf("RegisterHandleAndConsumer err: %s", err.Error()))
		}
	}
}

配置文件 config.yaml 的 kafka 配置如下：
kafka:
  ws2mschat:
    addr: [ 192.168.3.8:19092 ]      # kafka 配置，默认即可
    topic: "ws2ms_chat"
  ms2pschat:
    addr: [ 192.168.3.8:19092 ]      # kafka 配置，默认即可
    topic: "ms2ps_chat"
  consumergroupid:
    msgToMongo: mongo
    msgToMySql: mysql
    msgToPush: push

**Comment by Brooke9537** [comment]
sarama.NewClient会根据你的kafka更新元数据 (client *client) RefreshMetadata；检查一下kafka启动配置 KAFKA_ADVERTISED_HOST_NAME ，修改成对应的ip后重启kafka即可

**Comment by skiffer-git** [comment]
update please
