### ISSUE TITLE
Bug: Webhooks answer mechanism is abnormal

### ISSUE THREAD

**Issue by fx10007** [openimsdk/open-im-server#2166]
### What happened?

The response packet is abnormal. Procedure

If the status returned by the reply packet is not 0 and nextCode is 1, further execution should be refused.

Problem encountered: The execution actually continued. The message was sent to the recipient

### What did you expect to happen?

The expected message should not be delivered to the recipient

### How can we reproduce it (as minimally and precisely as possible)?

```
http://www.example.com/callbackBeforeSendSingleMsgCommand?contenttype=json

c.JSON(http.StatusOK, gin.H{
	"actionCode": 1,
	"errCode":    6001,
	"errMsg":     "内容违规",
	"errDlt":     "内容违规",
	"nextCode":   1,
})
```

### version

open-im-server : latest edition
open-im-chat: latest edition

### Cloud provider

ali Cloud

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by skiffer-git** [comment]
Please try using version 3.7, and if there are any issues, feel free to reopen the issue.
