### ISSUE TITLE
Bug: RESTful API /msg/send_msg delayed reception

### ISSUE THREAD

**Issue by Sylariam** [openimsdk/open-im-server#2172]
### What happened?

Version: v3.6.0
Problem: When using RESTful API /msg/send_msg, there is a random delay in message reception, ranging from 0 to over 10+ seconds. No delay when using native message sending.
Message body:

> {
  "sendID": "7289801396",
  "recvID": "8325462764",
  "groupID": "",
  "senderNickname": "",
  "senderFaceURL": "",
  "senderPlatformID": 1,
  "content": {
    "content": "hello!!"
  },
  "contentType": 101,
  "sessionType": 1,
  "isOnlineOnly": false,
  "notOfflinePush": false,
  "sendTime": 1712462465566,
  "offlinePushInfo": {
    "title": "send message",
    "desc": "",
    "ex": "",
    "iOSPushSound": "default",
    "iOSBadgeCount": true
  }
}

### What did you expect to happen?

RESTful API no message reception delay as using native

### How can we reproduce it (as minimally and precisely as possible)?

use RESTful API /msg/send_msg

### Anything else we need to know?

Deployed by Helm Charts

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by skiffer-git** [comment]
I recommend you update to release-v3.8. If you encounter any new issues, please reopen this issue or create a new one.

**Comment by skiffer-git** [comment]
Let's wait to use it until after our Kubernetes deployment goes live.

**Comment by mo3et** [comment]
This problem is solve in latest version. But we don't ready to Helm. Plz wait to latest version in Helm. Thanks for your feedback.
