### ISSUE TITLE
消息的扩展字段 ex 未做处理

### ISSUE THREAD

**Issue by mgyop** [OpenIMSDK/Open-IM-Server#220]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/25583272/168317329-bdadbac8-3d29-41b7-970b-f474ccc9d048.png">

**Comment by sbiweeq** [comment]
确实是,文档差异太大了

**Comment by airib** [comment]
很需要这个ex字段的数据

**Comment by YanhuiZeng** [comment]
非常需要，麻烦尽快加一下
