### ISSUE TITLE
[BUG] <集群部署启动Open-IM-Sever报错>

### ISSUE THREAD

**Issue by guyueyan2013** [OpenIMSDK/Open-IM-Server#223]
服务器A使用官方镜像完全部署，包括所有服务。
![image](https://user-images.githubusercontent.com/20625852/168756939-8fa5b7a1-391d-450b-9a61-31dea24079cc.png)

服务器B单部署openim/open_im_server:v2.0.7 
服务器B中间件，连接A服务器。
### Environment:

-  OS: CentOS Linux release 7.6.1810 

### Physical Memory Capacity:

8G
### Docker Image:

openim/open_im_server:v2.0.7
### Code Version:

v2.0.7
### Component installation:

kafka、etcd、mysql、mongodb、redis、minio、zookeeper

### Log File:

open db ok  root:openIM@tcp(10.20.5.163:13306)/openIM_v2?charset=utf8mb4&parseTime=true&loc=Local
0 0 mongo driver client init success:  mongodb://10.20.5.163:37017/openIM/?maxPoolSize=20
create index success
start push rpc server, port:  10700
10.20.5.162
panic: dial tcp 127.0.0.1:9092: connect: connection refused

goroutine 9 [running]:
Open_IM/pkg/common/kafka.(*MConsumerGroup).RegisterHandleAndConsumer(0xc00017a180, {0x14e1d70, 0x1de2cb0})
	/usr/local/Open-IM-Server/pkg/common/kafka/consumer_group.go:50 +0x98
created by Open_IM/internal/push/logic.Run
	/usr/local/Open-IM-Server/internal/push/logic/init.go:38 +0xa9

### screenshot:

![image](https://user-images.githubusercontent.com/20625852/168755668-800cfce6-2d9e-4480-abc7-891be8707aef.png)
![image](https://user-images.githubusercontent.com/20625852/168756386-49d1511a-365d-4c0f-9f35-79ea604824b4.png)

**Comment by skiffer-git** [comment]
Compile the source code and deploy it

**Comment by guyueyan2013** [comment]
你好，邮件已收到，谢谢！。
