### ISSUE TITLE
[BUG] MarkConversationAsRead failed

### ISSUE THREAD

**Issue by Sylariam** [openimsdk/open-im-server#2235]
### OpenIM Server Version

3.6.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

sdk-core version 3.5.1

1. Send message by Restful API
2. Received Message. Open conversation
3. Exit from conversation **in a second**
4. Conversation remains unmarked. mark_conversation_as_read failed

android logcat logs(step 2-4):

> 2024-04-26 15:31:06.171  9316-9653  GoLog                   com.nimispace.app                    I  2024-04-26 07:31:06.171	[34mINFO[0m	[34m[PID:9316][0m	[open_im_sdk/caller.go:144]	func call req	{"operationID": "1714116666170", "function name": "github.com/openimsdk/openim-sdk-core/v3/internal/conversation_msg.(*Conversation).GetAdvancedHistoryMessageList-fm", "args": ["{\"conversationID\":\"si_love1zfp14ndkhs0_love249nqhki0feo\",\"count\":200,\"lastMinSeq\":1}"]}
> 
> 2024-04-26 15:31:06.172  9316-9653  GoLog                   com.nimispace.app                    I  2024-04-26 07:31:06.172	[37mDEBUG[0m	[37m[PID:9316][0m	[log/sql_logger.go:86]	sql exec detail	{"operationID": "1714116666170", "gorm": "github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/db/conversation_model.go:155", "elapsed time": "0.687500(ms)", "rows": 1, "sql": "SELECT * FROM `local_conversations` WHERE conversation_id = \"si_love1zfp14ndkhs0_love249nqhki0feo\" LIMIT 1"}
> 2024-04-26 15:31:06.176  9316-9653  GoLog                   com.nimispace.app                    I  2024-04-26 07:31:06.176	[37mDEBUG[0m	[37m[PID:9316][0m	[log/sql_logger.go:86]	sql exec detail	{"operationID": "1714116666170", "gorm": "github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/db/chat_log_model_v3.go:106", "elapsed time": "3.046875(ms)", "rows": 19, "sql": "SELECT * FROM `chat_logs_si_love1zfp14ndkhs0_love249nqhki0feo` ORDER BY send_time DESC LIMIT 200"}
> 2024-04-26 15:31:06.180  9316-10455 GoLog                   com.nimispace.app                    I  2024-04-26 07:31:06.180	[34mINFO[0m	[34m[PID:9316][0m	[open_im_sdk/caller.go:135]	fn call success	{"operationID": "1714116666170", "function name": "github.com/openimsdk/openim-sdk-core/v3/internal/conversation_msg.(*Conversation).GetAdvancedHistoryMessageList-fm", "resp": {"messageList":[{"clientMsgID":"4a547c6583aeeca59404db2f6f56fb51","serverMsgID":"a265dd72d3d79d39bebca127f027c031","createTime":1713346202914,"sendTime":1713346202563,"sessionType":1,"sendID":"love1zfp14ndkhs0","recvID":"love249nqhki0feo","msgFrom":200,"contentType":110,"senderPlatformID":2,"seq":1,"isRead":true,"status":2,"customElem":{"data":"{\"title\":\"text custom usersff\",\"text_msg\":\"text custom usersff xxfdsf\",\"pic\":\"\",\"pic_file_id\":\\",\"pic_ratio\":0,\"jump_route\":\"https://www.baidu.com\",\"button\":{\"jump_route\":\"https://www.baidu.com\
> 2024-04-26 15:31:07.005  9316-10455 GoLog                   com.nimispace.app                    I  2024-04-26 07:31:07.005	[34mINFO[0m	[34m[PID:9316][0m	[open_im_sdk/caller.go:144]	func call req	{"operationID": "1714116667004", "function name": "github.com/openimsdk/openim-sdk-core/v3/internal/conversation_msg.(*Conversation).MarkConversationMessageAsRead-fm", "args": ["si_love1zfp14ndkhs0_love249nqhki0feo"]}
> 2024-04-26 15:31:07.006  9316-10455 GoLog                   com.nimispace.app                    I  2024-04-26 07:31:07.006	[37mDEBUG[0m	[37m[PID:9316][0m	[log/sql_logger.go:86]	sql exec detail	{"operationID": "1714116667004", "gorm": "github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/db/conversation_model.go:155", "elapsed time": "0.947396(ms)", "rows": 1, "sql": "SELECT * FROM `local_conversations` WHERE conversation_id = \"si_love1zfp14ndkhs0_love249nqhki0feo\" LIMIT 1"}
> 2024-04-26 15:31:07.007  9316-9654  GoLog                   com.nimispace.app                    I  2024-04-26 07:31:07.007	[37mDEBUG[0m	[37m[PID:9316][0m	[log/sql_logger.go:86]	sql exec detail	{"operationID": "1714116667004", "gorm": "github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/db/chat_log_model_v3.go:337", "elapsed time": "0.764062(ms)", "rows": 1, "sql": "SELECT IFNULL(max(seq),0) FROM `chat_logs_si_love1zfp14ndkhs0_love249nqhki0feo` WHERE send_id != \"love249nqhki0feo\""}
> 2024-04-26 15:31:07.009  9316-9654  GoLog                   com.nimispace.app                    I  2024-04-26 07:31:07.009	[37mDEBUG[0m	[37m[PID:9316][0m	[log/sql_logger.go:86]	sql exec detail	{"operationID": "1714116667004", "gorm": "github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/db/chat_log_model_v3.go:331", "elapsed time": "0.591667(ms)", "rows": 1, "sql": "SELECT IFNULL(max(seq),0) FROM `chat_logs_si_love1zfp14ndkhs0_love249nqhki0feo`"}
> 2024-04-26 15:31:07.010  9316-9654  GoLog                   com.nimispace.app                    I  2024-04-26 07:31:07.010	[37mDEBUG[0m	[37m[PID:9316][0m	[log/sql_logger.go:86]	sql exec detail	{"operationID": "1714116667004", "gorm": "github.com/openimsdk/openim-sdk-core/v3@v3.0.0-00010101000000-000000000000/pkg/db/chat_log_model_v3.go:268", "elapsed time": "0.779688(ms)", "rows": 1, "sql": "SELECT * FROM `chat_logs_si_love1zfp14ndkhs0_love249nqhki0feo` WHERE send_id != \"love249nqhki0feo\" AND is_read = 0"}
> 2024-04-26 15:31:07.010  9316-9653  GoLog                   com.nimispace.app                    I  2024-04-26 07:31:07.010	[37mDEBUG[0m	[37m[PID:9316][0m	[util/post.go:89]	ApiRequest	{"operationID": "1714116667004", "url": "http://CONCEALED/api/msg/mark_conversation_as_read", "body": "{\"conversationID\":\"si_love1zfp14ndkhs0_love249nqhki0feo\",\"userID\":\"love249nqhki0feo\",\"hasReadSeq\":19,\"seqs\":[19]}"}
> 2024-04-26 15:31:37.250  9316-9484  GoLog                   com.nimispace.app                    I  2024-04-26 07:31:37.249	[37mDEBUG[0m	[37m[PID:9316][0m	[util/post.go:113]	ApiResponse	{"operationID": "1714116667004", "url": "http:/CONCEALED/api/msg/mark_conversation_as_read", "status": "554 Receive Timeout From Mid Origin", "body": ""}
> 2024-04-26 15:31:37.251  9316-9484  GoLog                   com.nimispace.app                    I  2024-04-26 07:31:37.250	[31mERROR[0m	[31m[PID:9316][0m	[open_im_sdk/caller.go:138]	fn call error	{"operationID": "1714116667004", "function name": "github.com/openimsdk/openim-sdk-core/v3/internal/conversation_msg.(*Conversation).MarkConversationMessageAsRead-fm", "cost time": "30245 ms", "error": "api /msg/mark_conversation_as_read json.Unmarshal(\"\", *util.ApiResponse) failed unexpected end of JSON input: 10006 SdkInternalError"}

If I open conversation, stay for awhile and exit. Message could be marked.

**Comment by skiffer-git** [comment]
The issue has been fixed. Please use the latest version.
