### ISSUE TITLE
openImSdkWsPort service does not start normally,not initiated port is 10003

### ISSUE THREAD

**Issue by liujiehaobang** [OpenIMSDK/Open-IM-Server#224]
runtime/cgo: pthread_create failed: Operation not permitted

**Comment by leon19910505** [comment]
i also have this problem:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/26701373/175008920-07d815b4-7f19-4b66-9f4b-c5605263832e.png">

<img width="858" alt="image" src="https://user-images.githubusercontent.com/26701373/175009037-d6bfaec7-fe35-47fb-9834-4a432b1b9f7c.png">

and i check the log ,find this error msg:

<img width="1981" alt="image" src="https://user-images.githubusercontent.com/26701373/175009281-6577eb62-7458-42dd-bbd9-92825fdc61e5.png">

**Comment by yuz11** [comment]
i also have this problem，any solution?

**Comment by yuz11** [comment]
> i also have this problem，any solution?

well,I try to upgrade my docker version to 20.10.14,problem solve
![image](https://user-images.githubusercontent.com/4083905/175784255-3bd8d09f-243d-4bef-a2f5-34eb45959968.png)

**Comment by leon19910505** [comment]
> > i also have this problem，any solution?
> 
> well,I try to upgrade my docker version to 20.10.14,problem solve ![image](https://user-images.githubusercontent.com/4083905/175784255-3bd8d09f-243d-4bef-a2f5-34eb45959968.png)

thanks, it worked !!!

**Comment by skiffer-git** [comment]
docke 20.10.14, docker-compose 1.24.1
