### ISSUE TITLE
检查服务./check_all.sh 报错No such file or directoryle_info.cfg

### ISSUE THREAD

**Issue by LIUYUEQUN1992** [OpenIMSDK/Open-IM-Server#226]
[root@iZ7xvadue53q6g75mn6wn5Z script]# ./check_all.sh 
: No such file or directory
[root@iZ7xvadue53q6g75mn6wn5Z script]# sh check_all.sh 
check_all.sh: line 2: $'\r': command not found
: No such file or directoryle_info.cfg
[root@iZ7xvadue53q6g75mn6wn5Z script]# sh check_all.sh

**Comment by skiffer-git** [comment]
dos2unix  *.sh
