### ISSUE TITLE
[BUG] <title>2.0.10版本发送@消息，报错key not in错误，errCode1001

### ISSUE THREAD

**Issue by mollych** [OpenIMSDK/Open-IM-Server#227]
错误描述："event":"CreateTextAtMessage","errCode":1001,"errMsg":"key not in","data":"","operationID":"atfl0va95l16534628437976000001492851204"

**Comment by mollych** [comment]
服务端 2.0.10    jssdk 2.0.3

**Comment by skiffer-git** [comment]
Please give the log of the input parameters
