### ISSUE TITLE
Commercial version licensing model announced

### ISSUE THREAD

**Issue by mingyangzhu** [openimsdk/open-im-server#2271]
### Why this feature?

目前在官网查不到任何商业版授权模式，完全不知道授权方式。

### Suggested Solution

建议公开商业版授权方式，让用户有更方便做决策。

### Additional Information

-

**Comment by skiffer-git** [comment]
This repository is under the Apache 2.0 license; it's free to use.

For the commercial version, please contact us at our email: contact@openim.io
