### ISSUE TITLE
[BUG] config.yaml自定义数据库账号密码报错（已反馈BUG一个月了）

### ISSUE THREAD

**Issue by XinZiIng** [OpenIMSDK/Open-IM-Server#229]
### Environment:
Contos 8

### Physical Memory Capacity:
8G

### Docker Image:
最新镜像

### Code Version:
最新版本

### Component installation:
相关组件都有安装且正常

### Log File:
goroutine 1 [running]:
Open_IM/pkg/common/db.initMysqlDB()
	/Open-IM-Server/pkg/common/db/mysql.go:34 +0x156e
Open_IM/pkg/common/db.init.0()
	/Open-IM-Server/pkg/common/db/model.go:43 +0x2e
0 Open failed  Error 1045: Access denied for user 'root'@'xxxxxx' (using password: YES) root:xxxxxx@tcp(127.0.0.1:13306)/mysql?charset=utf8mb4&parseTime=true&loc=Local
panic: Error 1045: Access denied for user 'root'@'172.21.0.1' (using password: YES)

该问题在微信群反馈了N次，群管理还说新版本改好了，结果也没改！！！现在这问题都一个月了，每个礼拜都在群里艾特你们官方的人员问情况，结果都是回复一两句，人就消失了，对问题跟进这方面做的太差了，如果这样，要微信群何在？在群里反馈不跟，在github之前也反馈问题，也没跟？对此很失望。

**Comment by OldKing-lion** [comment]
确实，微信群基本没人回复。可能是开源的项目，资金少吧。但是这样也不敢用啊。有bug不知道怎么处理

**Comment by HimiHL** [comment]
刚刚遇到，我用的子账号，用了超级账号root就可以了。

**Comment by XinZiIng** [comment]
> 刚刚遇到，我用的子账号，用了超级账号root就可以了。

你是没先去修改mysql、mongodb、redis这些数据库账号、密码后再构建的吧，你要是不改，等上线了，别人通过ip + 默认数据库账号密码就能操作你的库了

**Comment by HimiHL** [comment]
你想多了，Redis和MySQL都是在这之前就已经其他服务在使用了，他启动的时候一直在连那个`mysql`数据库，我才把他临时切到root了，这会儿还没换回去，谁也不会傻到用config.yaml里的默认参数吧

**Comment by XinZiIng** [comment]
> 你想多了，Redis和MySQL都是在这之前就已经其他服务在使用了，他启动的时候一直在连那个`mysql`数据库，我才把他临时切到root了，这会儿还没换回去，谁也不会傻到用config.yaml里的默认参数吧

凡事无绝对，就算如此，那也应该支持修改默认参数，例如现在所讲的数据库账号密码；

再者，你想说的是，直连了现有mysql、redis服务是吧？在哪里可以配置连接现有库？在哪里可以配置？

**Comment by HimiHL** [comment]
> > 你想多了，Redis和MySQL都是在这之前就已经其他服务在使用了，他启动的时候一直在连那个`mysql`数据库，我才把他临时切到root了，这会儿还没换回去，谁也不会傻到用config.yaml里的默认参数吧
> 
> 凡事无绝对，就算如此，那也应该支持修改默认参数，例如现在所讲的数据库账号密码；
> 
> 再者，你想说的是，直连了现有mysql、redis服务是吧？在哪里可以配置连接现有库？在哪里可以配置？

啊对对对
