### ISSUE TITLE
在外网编译好后，打包到内网环境，启动脚本报错

### ISSUE THREAD

**Issue by cloud66432** [OpenIMSDK/Open-IM-Server#231]
[root@localhost script]# ./start_all.sh 
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_api start success,port number:10002 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_cms_api start success,port number:10006 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_user start success,port number:10110 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_friend start success,port number:10120 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_group start success,port number:10150 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_auth start success,port number:10160 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_admin_cms start success,port number:10200 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_message_cms start success,port number:10190 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_statistics start success,port number:10180 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_msg start success,port number:10130 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_office start success,port number:10210 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_organization start success,port number:10220 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_conversation start success,port number:10230 pid:
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
open_im_cache start success,port number:10240 pid:
SERVICE START SUCCESS
SERVICE_NAME: open_im_msg_gateway
PID: 17432
LISTENING_PORT:  
SERVICE START SUCCESS 
SERVICE_NAME: open_im_push
PID: 17471
LISTENING_PORT: 
SERVICE START SUCCESS 
SERVICE_NAME: open_im_msg_transfer
PID: 17504 17505
LISTENING_PORT: 
open_im_sdk_serverSERVICE START ERROR PLEASE CHECK openIM.log
SERVICE START SUCCESS 
SERVICE_NAME: open_im_demo
PID: 17594
LISTENING_PORT:

**Comment by wangchuxiao-dev** [comment]
请检查你的二进制文件
