### ISSUE TITLE
极光推送，ios生产环境收不到推送[BUG] <title>

### ISSUE THREAD

**Issue by lyo1** [OpenIMSDK/Open-IM-Server#233]
极光推送，配置了appid和appkey之后，ios开发环境和安卓可以收到推送，ios生产环境收不到推送

**Comment by zhaoxin151** [comment]
go 服务端，/internal/push/jpush/push.go中，45行，改为“o.SetApnsProduction(true)” ，这样iOS生产环境推送，开发环境不推送了

**Comment by FGadvancer** [comment]
In the latest version，you can set production is true in config/config.yaml
