### ISSUE TITLE
[DOC]: missing `setConversationEx`

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-server#2357]
## Documentation Updates
Describe the documentation that needs to be updated or corrected. Please specify the files and sections if possible.

## Motivation
Explain why these updates are necessary. What is missing, misleading, or outdated?

## Suggested Changes
Detail the changes that you propose. If you are suggesting large changes, include examples or mockups of what the updated documentation should look like.

## Additional Information
Include any other information that might be relevant, such as links to discussions or related issues in the repository.

**Comment by skiffer-git** [comment]
This issue has been fixed in release-v3.8. I recommend updating to the new version. If you encounter any new issues, please reopen this issue or create a new one.
