### ISSUE TITLE
[BUG]An error occurred when I Create group by api  after set webhook 'callbackBeforeMemberJoinGroupCommand'

### ISSUE THREAD

**Issue by yanqinsc** [openimsdk/open-im-server#2364]
### OpenIM Server Version

3.7

### Operating System and CPU Architecture

Windows (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

An error occurred when I Create group by api  after set webhook 'callbackBeforeMemberJoinGroupCommand'。
Logs show that the error occurred before the webhook arrive.
Debug log as follows:

local.DEBUG: apiCall res: {"errCode":90004,"errMsg":"HTTP request failed: Post \"http://127.0.0.1/api/callback/callbackBeforeMemberJoinGroupCommand\": context deadline exceeded, post url=http://127.0.0.1/api/callback/callbackBeforeMemberJoinGroupCommand: 90004 NetworkError","errDlt":"HTTP request failed: Post \"http://127.0.0.1/api/callback/callbackBeforeMemberJoinGroupCommand\": context deadline exceeded, post url=http://127.0.0.1/api/callback/callbackBeforeMemberJoinGroupCommand: 90004 NetworkError"}  
[2024-06-26 15:23:22] local.INFO: webhook:callbackBeforeMemberJoinGroupCommand {"callbackCommand":"callbackBeforeMemberJoinGroupCommand","groupID":"56","userID":"9267410449","ex":null,"groupEx":"{\"niceId\":56}"}

**Comment by icey-yu** [comment]
Can you provide more details? For example, request parameters or more error information.

**Comment by skiffer-git** [comment]
Has the webhook URL been set up, and is the API functioning properly?

**Comment by yanqinsc** [comment]
> Can you provide more details? For example, request parameters or more error information. Please make sure that you have correctly set the webhook URL and that the corresponding service is enabled.

The webhook's config is correct. the webhook been called in 4 places. err occurred only in createGroup methond.  create group by   server api .

**Comment by icey-yu** [comment]
The correct command should be:`callbackBeforeJoinGroupCommand`
