### ISSUE TITLE
[DOC]: Webhook:callbackBeforeApplyMemberJoinGroupCommand's roleLevel type error

### ISSUE THREAD

**Issue by yanqinsc** [openimsdk/open-im-server#2365]
The type of response filed  'roleLevel' in  Webhook:callbackBeforeApplyMemberJoinGroupCommand should be int but string in server apis document.
[document link](https://docs.openim.io/zh-Hans/restapi/webhooks/group/applyJoinGroupBefore)

**Comment by icey-yu** [comment]
https://github.com/openimsdk/docs/pull/137
Fix it. Thanks.

**Comment by icey-yu** [comment]
@skiffer-git Close it.
