### ISSUE TITLE
[BUG] The rest api's token acquisition does not seem to meet the expected expiration time

### ISSUE THREAD

**Issue by 7FreezingPoint** [openimsdk/open-im-server#2399]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

The token obtained through the REST API is new each time and has the configured expiration duration. However, I noticed that Redis uses a hash data structure for storage, which seems to cause the subsequent tokens obtained by the same user to not reach the expected full expiration duration (configured expiration duration). Instead, they may expire prematurely along with the hash key.

### Screenshots Link

![eb92fcd5cf0446b3b811926537dd7b9](https://github.com/openimsdk/open-im-server/assets/47354200/b33e2de9-5567-46c1-b487-e2629723fc22)

**Comment by icey-yu** [comment]
The issue has been fixed. Thank you for pointing it out.
