### ISSUE TITLE
[FEATURE REQUEST] I need a callback to handle business before processing the message.

### ISSUE THREAD

**Issue by phpmaple** [openimsdk/open-im-server#2451]
### Why this feature?

I checked the code and found that when I sent a message to another user, the other user blocked me. After I sent the message, `callbackBeforeSendSingleMsgCommand` not be called

### Suggested Solution

I want to do some business logic when I sent a message to another user, but the other user blocked me.

**Comment by skiffer-git** [comment]
https://docs.openim.io/restapi/webhooks/msg/sendsinglemsgbefore

**Comment by skiffer-git** [comment]
Do you mean that if someone has blocked you, the callbackBeforeSendSingleMsgCommand will not work?

**Comment by phpmaple** [comment]
yes
