### ISSUE TITLE
[BUG] OpenIM-Admin user message page [sending time] query condition is invalid

### ISSUE THREAD

**Issue by 7FreezingPoint** [openimsdk/open-im-server#2464]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

问题位于OpenIM-Admin-Front项目的IM系统-消息管理-用户消息页面

**Comment by skiffer-git** [comment]
Please update to version 3.8 because the bug has been fixed.
The new version should work without the issues you experienced.
Let me know if you need help with the update process.
