### ISSUE TITLE
[FEATURE REQUEST] `multiLoginPolicy` supports parameter values ​​​​that cannot be used to log in on the mobile terminal and are allowed on the web terminal.

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-server#2469]
### Why this feature?

Currently, it can only be set to 0 or 1 to indicate multiple logins or disallow multiple logins. 
### Suggested Solution

It is recommended to support disallowing multiple logins on mobile devices while allowing multiple logins on the web. This is because multiple logins are more likely to occur on the web.

**Comment by skiffer-git** [comment]
This is a great suggestion; our team will consider it carefully and evaluate its potential implementation

**Comment by skiffer-git** [comment]
This feature is already supported in the commercial version.
