### ISSUE TITLE
[BUG] <搭建自己的服务，注册是设置密码报错>

### ISSUE THREAD

**Issue by sdksdk1986** [OpenIMSDK/Open-IM-Server#247]
在window10上搭建服务，通过客户端编译的web版连接服务，注册用户时发送验证码成功，但是设置密码的时候报错了。提示：register failed: 1657773489256 UserRegister failed rpc error: code = Unavailable desc = last resolver error: produced zero addressesUserInfo:<userID:"274206333" nickname:"15960******" > OperationID:"1657773489256"

**Comment by skiffer-git** [comment]
check svr
