### ISSUE TITLE
[BUG] Built-in PC Web authentication cannot switch paging

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-server#2470]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

gif:

![demo](https://github.com/user-attachments/assets/acebe789-0fb9-4c3e-85db-0f858bba70b8)

另：显示的内容应该按发送时间倒序的吧。

**Comment by skiffer-git** [comment]
This bug has been fixed in the 1.8 Docker image. Please update promptly to ensure optimal functionality and performance
