### ISSUE TITLE
[BUG] net/http.(*Server).Shutdown(panic: runtime error: invalid memory address or nil pointer dereferencepanic

### ISSUE THREAD

**Issue by volencez** [openimsdk/open-im-server#2471]
### OpenIM Server Version

main

### Operating System and CPU Architecture

Linux (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

1. cd open-im-server
2. docker compose up -d 启动组件
3. mage start 
4.nohup mage start >> _output/logs/openim.log 2>&1 &

### Screenshots Link

![image](https://github.com/user-attachments/assets/87fb8cf3-eb38-4e3d-b864-7bf9522c9c03)
![image](https://github.com/user-attachments/assets/992640f2-5b25-4b54-ab36-12a1a6194b9a)

**Comment by volencez** [comment]
[openim.log](https://github.com/user-attachments/files/16472628/openim.log)
The log is in the attachment, I hope it can help you

**Comment by skiffer-git** [comment]
first :mage start
then: nohup mage start >> _output/logs/openim.log 2>&1 &

**Comment by skiffer-git** [comment]
You just need to run one of the two commands.
