### ISSUE TITLE
[BUG] mage warning

### ISSUE THREAD

**Issue by volencez** [openimsdk/open-im-server#2478]
### OpenIM Server Version

main and release-3.8.0

### Operating System and CPU Architecture

Linux (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

1. update go.mod 
equire (
github.com/openimsdk/tools v0.0.49
)
2. go mod tidy
3. mage

### Screenshots Link

![1821722612812_ pic](https://github.com/user-attachments/assets/43b5c05d-8c74-419a-b954-c4ae87d4273c)

**Comment by icey-yu** [comment]
This is an error reported by one of our dependency packages, and currently, there is no good solution available. We may change the business logic in the future, thereby eliminating our dependency on this package.

**Comment by icey-yu** [comment]
We have updated the dependency package and removed the warning.
https://github.com/openimsdk/tools/pull/131
