### ISSUE TITLE
[DOC]: It is recommended to add a current version number to https://doc.rentsoft.cn/

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-server#2488]
## Documentation Updates
Describe the documentation that needs to be updated or corrected. Please specify the files and sections if possible.

## Motivation
Explain why these updates are necessary. What is missing, misleading, or outdated?

## Suggested Changes
Detail the changes that you propose. If you are suggesting large changes, include examples or mockups of what the updated documentation should look like.

## Additional Information
Include any other information that might be relevant, such as links to discussions or related issues in the repository.

**Comment by FGadvancer** [comment]
Thank you very much for your suggestion. We will next try to add version information to this [repository](https://github.com/openimsdk/docs).
