### ISSUE TITLE
[BUG] flutter_openim_sdk error Unhandled Exception: PlatformException(10303, 10303 unread count has zero, null, null)

### ISSUE THREAD

**Issue by LionYan-Coder** [openimsdk/open-im-server#2507]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(10303, 10303 unread count has zero, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>

### Screenshots Link

<img width="814" alt="截屏2024-08-12 15 17 10" src="https://github.com/user-attachments/assets/0e5c6ae1-3def-469c-b26d-e7feb703b0b6">

**Comment by LionYan-Coder** [comment]
Launching the app, going to chat and going back to conversation will result in this error and is only available on ios

**Comment by TheOneT1** [comment]
@LionYan-Coder  请问你如何解决的这个问题，我也遇到了这个问题

**Comment by TheOneT1** [comment]
@LionYan-Coder  How do you solve this problem, I also encountered this problem
