### ISSUE TITLE
克隆代码失败

### ISSUE THREAD

**Issue by YangShizhao** [OpenIMSDK/Open-IM-Server#251]
If you are deploying OpenIM for the first time

尝试按照教程流程克隆代码，但clone指令报错。

使用的clone指令为：

```
git clone https://github.com/OpenIMSDK/Open-IM-Server.git --recursive
```

报错信息为：

```
获取了子模组路径 'cmd/Open-IM-SDK-Core'，但是它没有包含 3cf486771bbe7ecb33f7e7c3cdf733f28b16d8b7。直接获取该提交失败。
```

截图如下：
![image](https://user-images.githubusercontent.com/13344900/180106433-b135feee-4897-47bf-a2e5-0c85b628761b.png)

**Comment by huainanzi** [comment]
同样遇到,应该不是网络问题

**Comment by cnlinjie** [comment]
@huainanzi  是的，刚试过。好像代码库问题。
<img width="802" alt="image" src="https://user-images.githubusercontent.com/3601638/180162950-34a3cf3f-b987-4b46-a50b-b6c10bdc4ae1.png">

**Comment by cnlinjie** [comment]
这个代码库404了

**Comment by huainanzi** [comment]
试下手动克隆submodule

**Comment by YangShizhao** [comment]
> 试下手动克隆submodule

这个是在报错后手动克隆吗，这里出错中断是最后一步不，会不会手动克隆了之后还有其他的步骤没有执行？

**Comment by clstech** [comment]
同样遇到此问题

**Comment by Liu-Peter** [comment]
我也遇到了

**Comment by skiffer-git** [comment]
fixed
