### ISSUE TITLE
[BUG] REST API /conversation/get_sorted_conversation_list error

### ISSUE THREAD

**Issue by caolixi** [openimsdk/open-im-server#2516]
### OpenIM Server Version

3.7

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

①query all conversations，response”1004 mongo find one: mongo: no documents in result mongo find one: mongo: no documents in result"“
![image](https://github.com/user-attachments/assets/34154d3f-d406-415b-a097-e2bc447fccf2)
②query single conversation，success
![image](https://github.com/user-attachments/assets/66902355-8d96-421e-9cd4-0a7f4c68c695)
③query MongoDB，response 60 conversations
![image](https://github.com/user-attachments/assets/baeeae44-a957-4d2a-b457-5498b4a76385)

**Comment by mo3et** [comment]
This problem is solve to latest version. Thanks for your feedback.
