### ISSUE TITLE
[BUG] When I send messages to certain accounts, the IM log shows an error that says  2024/08/13 17:51:43 ERROR: [core] [Server #1] grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil

### ISSUE THREAD

**Issue by jk030611** [openimsdk/open-im-server#2517]
### OpenIM Server Version

3.5

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

通过命令 docker logs -f openim-server 查看日志， 出错的截图如下
![image](https://github.com/user-attachments/assets/18c404d0-4114-4447-a4d4-8c99ee997c14)

**Comment by jk030611** [comment]
[](url)
[im.log](https://github.com/user-attachments/files/16597801/im.log)

**Comment by jk030611** [comment]
日志已经给了

**Comment by skiffer-git** [comment]
Hey, I noticed we’re still using the older version of the software.
Would you like to update to version 3.8?

**Comment by skiffer-git** [comment]
I recommend you update to release-v3.8. If you encounter any new issues, please reopen this issue or create a new one.
