### ISSUE TITLE
[Deployment] Kafka check failed: NewClient failed, config: =&{Username: Password: ProducerAck: CompressType:none Addr:[localhost:19094] TLS:{EnableTLS:false CACrt: ClientCrt: ClientKey: ClientKeyPwd: InsecureSkipVerify:false}}: kafka: client has run out of available brokers to talk to: read tcp [::1]:34736->[::1]:19094: read: connection reset by peer

### ISSUE THREAD

**Issue by tonypra** [openimsdk/open-im-server#2518]
### OpenIM Server Version

3.8

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Issue Description and Steps to Reproduce

Kafka check failed: NewClient failed, config: =&{Username: Password: ProducerAck: CompressType:none Addr:[localhost:19094] TLS:{EnableTLS:false CACrt: ClientCrt: ClientKey: ClientKeyPwd: InsecureSkipVerify:false}}: kafka: client has run out of available brokers to talk to: read tcp [::1]:34736->[::1]:19094: read: connection reset by peer

![690eee3e5c358295e00acb75c1c969b](https://github.com/user-attachments/assets/861a4946-4ffb-4aaa-b1da-9ab43de86b92)

### Screenshots Link

![690eee3e5c358295e00acb75c1c969b](https://github.com/user-attachments/assets/9d50e8bd-12ee-46bc-b002-2e31b93c3a0a)

**Comment by skiffer-git** [comment]
What changes did you make to the settings

**Comment by skiffer-git** [comment]
It looks like Kafka didn't start properly from what I can see.
Could you provide the Kafka logs so we can troubleshoot the issue?

**Comment by tonypra** [comment]
but can't see any logs in logs folder.
 
![image](https://github.com/user-attachments/assets/53971cb1-d5ce-465b-85ef-4387f034cb41)
![image](https://github.com/user-attachments/assets/d585c8ed-6d6e-4814-812f-3dd4a042abe7)

**Comment by tonypra** [comment]
![1723620390262](https://github.com/user-attachments/assets/dc8d7e2a-3fb0-471a-9bf4-933b98f029bf)
![1723620434083](https://github.com/user-attachments/assets/038b178e-0138-44bc-99c7-b4011e7919b4)
![1723620351827](https://github.com/user-attachments/assets/e3265eec-a3a5-4955-a3ac-b0a4e6f7816f)

**Comment by tonypra** [comment]
pls help to take a look first. thanks a lot

**Comment by skiffer-git** [comment]
1. docker logs kafka
2. ls scripts/create-topic.sh -al

**Comment by skiffer-git** [comment]
chmod +x scripts/*.sh

**Comment by skiffer-git** [comment]
docker exec -it mongo bash /docker-entrypoint-initdb.d/mongo-init.sh

**Comment by skiffer-git** [comment]
or 
chmod +x scripts/*.sh
rm components -rf
docker  compose up -d
