### ISSUE TITLE
[BUG] After 3.8.0, webhooks cannot receive user online status callback and user offline status callback

### ISSUE THREAD

**Issue by Xiaobai-1024** [openimsdk/open-im-server#2520]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

3.8.0后webhooks收不到用户在线状态回调和用户离线状态回调

**Comment by jiangzc16** [comment]
升级到v3.8后，确实收不到OnUserStatusChanged回调。

**Comment by jiangzc16** [comment]
Thanks a lot


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openimsdk/open-im-server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月14日(星期一) 中午11:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openimsdk/open-im-server] [BUG] After 3.8.0, webhooks cannot receive user online status callback and user offline status callback (Issue #2520)





 
Closed #2520 as completed via #2716.
