### ISSUE TITLE
[DOC]: Reality synchronization failed after logging in

### ISSUE THREAD

**Issue by zilinyo** [openimsdk/open-im-server#2523]
## Documentation Updates
Describe the documentation that needs to be updated or corrected. Please specify the files and sections if possible.

## Motivation
Explain why these updates are necessary. What is missing, misleading, or outdated?

## Suggested Changes
Detail the changes that you propose. If you are suggesting large changes, include examples or mockups of what the updated documentation should look like.
![image](https://github.com/user-attachments/assets/f1c7bf74-43e1-4d17-bcb9-146f811fd297)

## Additional Information
Include any other information that might be relevant, such as links to discussions or related issues in the repository.

**Comment by skiffer-git** [comment]
The latest version doesn't have this issue. Please go ahead and use it.
