### ISSUE TITLE
[BUG] 404 error: blob/main/example/callback/callback.go 

### ISSUE THREAD

**Issue by tonypra** [openimsdk/open-im-server#2535]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

 404 error: blob/main/example/callback/callback.go 

### Screenshots Link

![1](https://github.com/user-attachments/assets/c080036d-e76b-41a9-8d3c-5f6083638133)
![2](https://github.com/user-attachments/assets/de25de37-2d55-4bde-93c0-176bdedc2e94)

**Comment by skiffer-git** [comment]
https://github.com/openimsdk/chat/blob/release-v1.7/internal/rpc/chat/callback.go
