### ISSUE TITLE
openim thumbnail sent cannot be displayed

### ISSUE THREAD

**Issue by 17674100338** [openimsdk/open-im-server#2536]
### OpenIM Server Version

v3.5

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

openim是docker安装的但是因为服务器CPU问题所以minio和mongodb是安装在别的服务器上的，然后通过修改docker-compose.yaml 和server的config文件进行连接，现在openim可以登录发送图片文字视屏但是另一个用户登录无法查看到该用户发出略缩图片。
![Uploading 1.jpg…]()

**Comment by 17674100338** [comment]
![1](https://github.com/user-attachments/assets/9c45e12a-71bd-4206-b105-9bc3cbe1ee07)
![2](https://github.com/user-attachments/assets/e0c32408-7cf9-48c8-8825-ded9ede176b1)

**Comment by 17674100338** [comment]
![3](https://github.com/user-attachments/assets/5c12e2e8-f313-42f1-8024-752ab99b4638)

**Comment by skiffer-git** [comment]
https://github.com/openimsdk/openim-docker/issues/136

**Comment by 17674100338** [comment]
![11](https://github.com/user-attachments/assets/0a7fe4b2-0c17-43cd-acc0-fd14382af103)
openim上传的文件无法进行预览

**Comment by Bloomingg** [comment]
Please check your minio configuration. It is recommended to upgrade to version 3.8.

**Comment by skiffer-git** [comment]
this issue has fixed in release-v3.8, I recommend you update to new version. If you run into any new issues, please reopen this issue or create a new one.
