### ISSUE TITLE
After executing the command docker compose up - d, Prom/prometheus has been in Restarting state, and after forcibly starting openim, the imAdmin token cannot be obtained through the API

### ISSUE THREAD

**Issue by xiaobeiy** [openimsdk/open-im-server#2539]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Issue Description and Steps to Reproduce

源码部署时，执行部署组件命令docker compose up -d后，prom/prometheus一直处于Restarting状态，强行启动openim后，通过api无法获取到imAdmin的token，这是怎么回事，该如何处理？
prom/prometheus的日志如下：
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0x7ffd38053f79, 0xb}, 0x14, {0x3cd2480, 0xc0008638b0})
        /app/promql/query_logger.go:121 +0x3bb
main.main()
        /app/cmd/prometheus/main.go:640 +0x7352
ts=2024-08-20T09:08:58.022Z caller=main.go:534 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2024-08-20T09:08:58.022Z caller=main.go:578 level=info msg="Starting Prometheus Server" mode=server version="(version=2.45.6, branch=HEAD, revision=9bc0e4af7d3b55c376a089ec1bc384e61c3ce28d)"
ts=2024-08-20T09:08:58.022Z caller=main.go:583 level=info build_context="(go=go1.21.11, platform=linux/amd64, user=root@5079853c7156, date=20240621-13:49:51, tags=netgo,builtinassets,stringlabels)"
ts=2024-08-20T09:08:58.022Z caller=main.go:584 level=info host_details="(Linux 3.10.0-1160.102.1.el7.x86_64 #1 SMP Tue Oct 17 15:42:21 UTC 2023 x86_64 a3517e409f52 (none))"
ts=2024-08-20T09:08:58.022Z caller=main.go:585 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2024-08-20T09:08:58.022Z caller=main.go:586 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2024-08-20T09:08:58.022Z caller=query_logger.go:91 level=error component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: permission denied"

**Comment by icey-yu** [comment]
The launch of the Prometheus container requires configuring your own internal IP in the settings and setting the permissions for the relevant files. Prometheus is used only for monitoring purposes; if not needed, it can be turned off without affecting the normal operation of OpenIM.

**Comment by icey-yu** [comment]
https://docs.openim.io/zh-hans/guides/gettingstarted/admin
