### ISSUE TITLE
Latest version installation failure

### ISSUE THREAD

**Issue by 17674100338** [openimsdk/open-im-server#2546]
### OpenIM Server Version

3.8

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Issue Description and Steps to Reproduce

官网下载3.8版本然后直接运行报错
![图片](https://github.com/user-attachments/assets/04d4eeae-0992-4181-87e8-ff1a5ee15277)
![图片](https://github.com/user-attachments/assets/04bec4bf-ba52-4930-858c-db437a3fd14c)

**Comment by FGadvancer** [comment]
Find a server where the network can pull Docker images normally, or transfer the images using the docker save method. Ensure that the component images are correctly downloaded locally.
