### ISSUE TITLE
[Other]: Data Migration from v3.4.0 to v3.8.0 Post-MySQL Deprecation

### ISSUE THREAD

**Issue by zhaolibo1989** [openimsdk/open-im-server#2554]
### What would you like to share?

I am currently merging the second development branch based on version v3.4.0 with version v3.8.0. Upon reviewing the Release Notes, I found that the use of MySQL has been discontinued since version v3.5.0. How can I migrate data from the old version, and is there a corresponding tool available?

### Additional information

@OpenIM-Blooming said: "The upgrade to 3.5 will automatically migrate," but how can I achieve this?

**Comment by zhaolibo1989** [comment]
In Android APP development, besides upgrading the openim-sdk-core, what else needs to do?

**Comment by FGadvancer** [comment]
To upgrade from version 3.4.0 to 3.8.0, first update your server code from 3.4.0 to 3.5.0. Once the server is started, it will automatically perform the data migration from MySQL to MongoDB. Then, upgrade from 3.5.0 to 3.8.0, which will automatically handle the conversion of the sequence data. Of course, make sure to back up your data beforehand to ensure a safe operation.

**Comment by zhaolibo1989** [comment]
> To upgrade from version 3.4.0 to 3.8.0, first update your server code from 3.4.0 to 3.5.0. Once the server is started, it will automatically perform the data migration from MySQL to MongoDB. Then, upgrade from 3.5.0 to 3.8.0, which will automatically handle the conversion of the sequence data. Of course, make sure to back up your data beforehand to ensure a safe operation.

In this way, do I have to merge the code twice?

Is there a way to directly merge and publish the code of 3.8 on that branch, and after publishing and running, automatically complete the data migration?

**Comment by zhaolibo1989** [comment]
I found a tool bin [up35](https://github.com/openimsdk/open-im-server/blob/v3.6.0/tools/up35/up35.go#L25) to perform the data migration, it was added in v3.5.0 and then removed in v3.7.0.
