### ISSUE TITLE
请问社区 有Java 语言版本的服务端么？

### ISSUE THREAD

**Issue by pengpengno** [OpenIMSDK/Open-IM-Server#256]
本人有一个之前大学期间做个一个很基本的IM 小系统 十分 简陋，希望能借鉴OpenIM社区的经验对自己的小demo进行重构，对自己额能力沉淀的同时完善这个小demo，望OpenIM社区 各位develops 如果存在Java版本，请告知。
感谢！~

**Comment by wangchuxiao-dev** [comment]
还没有java版本

**Comment by cnlinjie** [comment]
啊这...，不可能再开发一个Java版本的，用了Go语言就是看中Go语言的性能，而且同样是有GC的语言，不可能再用Java实现一套。

**Comment by pengpengno** [comment]
感谢各位的回复，目前在开始学习IM设计，参考社区的sdk，完善 Demo了，这个issue 就close了
