### ISSUE TITLE
[BUG] FCM iOS push failed

### ISSUE THREAD

**Issue by AntaoCai** [openimsdk/open-im-server#2572]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

1、openim-server openim-push.yml配置如下：
<img width="1120" alt="image" src="https://github.com/user-attachments/assets/26e863c4-b94a-48ce-9b93-dac4db34046f">
2、filePath路径中的service_account_key.json 跟 openim-push.yml 是在同一个目录下面，如图：
<img width="1138" alt="image" src="https://github.com/user-attachments/assets/2507b410-6bd3-488a-80c4-bc25bd4fcb35">
3、iOS端口已经更新了FcmToken 到 openim中，并在redis中可以查看到，如图：
<img width="799" alt="image" src="https://github.com/user-attachments/assets/485e65ae-db41-442f-99d6-e015f9431fbf">
<img width="791" alt="image" src="https://github.com/user-attachments/assets/47c1b789-2ecd-4be3-87a0-a197244f305e">
4、在进行离线推送的时候 openim 日志出现错误，如图：
<img width="1866" alt="image" src="https://github.com/user-attachments/assets/6308fe26-368e-4621-bb51-d3dc31353047">
5、xcode 中的GoogleService-Info 如图：
<img width="1479" alt="image" src="https://github.com/user-attachments/assets/f1c6aadd-b14e-4f5f-a93a-a5d3a3d25bd8">
6、openim中的service_account_key.json 如图：
<img width="1151" alt="image" src="https://github.com/user-attachments/assets/53773a10-e3be-496d-9fb1-3a55820656f5">

**Comment by AntaoCai** [comment]
我这边使用JAVA后端代码测试推送是没有问题。也就说Firebase那块的配置是没有问题的。如图：
![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-29 at 16 09 14](https://github.com/user-attachments/assets/97a280d4-7827-46dc-aa06-6616320cc363)

**Comment by AntaoCai** [comment]
我这边使用JAVA后端代码测试推送是没有问题。也就说Firebase那块的配置是没有问题的。如图：
![WechatIMG1154](https://github.com/user-attachments/assets/7a6999e8-becd-4d5b-b583-76159b2ec1ba)

**Comment by AntaoCai** [comment]
解决方案：
<img width="1129" alt="image" src="https://github.com/user-attachments/assets/ef6f8fa5-ecc1-4bc1-877c-46c40484fb5a">

**Comment by buiphukhuyen** [comment]
Hi @AntaoCai. 

I have the same problem as you, now I can't send fcm messages. Have you fixed this problem? Please help me! Thank you very much!

[](https://github.com/openimsdk/openim-docker/issues/194)
