### ISSUE TITLE
error(s) decoding

### ISSUE THREAD

**Issue by 17674100338** [openimsdk/open-im-server#2576]
### OpenIM Server Version

3.8

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

我docker打包镜像和文件到内网环境运行docker-compose up -d 发现报错，我在本地运行成功了，但是内网环境失败了，这是为什么。

### Screenshots Link

![图片](https://github.com/user-attachments/assets/c4f6a818-eaea-47e2-bf9c-cdde21a1a7dd)

**Comment by FGadvancer** [comment]
It might be an issue with the Docker version. You can refer to the Docker version recommended by the [OpenIM official website.](https://docs.openim.io/guides/gettingstarted/dockercompose#62-about-docker-versions-)

**Comment by 17674100338** [comment]
> 这可能是 Docker 版本的问题。可以参考 [OpenIM 官网 ](https://docs.openim.io/guides/gettingstarted/dockercompose#62-about-docker-versions-)
好像并不行，我刚升级了docker到27版本还是不行，之前是25版本
![图片](https://github.com/user-attachments/assets/7d2ec5db-e0c6-4a6f-97f6-9686bb415663)

**Comment by 17674100338** [comment]
> It might be an issue with the Docker version. You can refer to the Docker version recommended by the [OpenIM official website.](https://docs.openim.io/guides/gettingstarted/dockercompose#62-about-docker-versions-)

是的，确实是这个问题，我升级了版本后重新运行不会报这个错误了。
