### ISSUE TITLE
web access failure

### ISSUE THREAD

**Issue by 17674100338** [openimsdk/open-im-server#2585]
### OpenIM Server Version

3.8

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

docker运行后web页面访问一直转圈圈，但是可以接受好友发出来的信息

### Screenshots Link

![图片](https://github.com/user-attachments/assets/d4eeffe4-7df4-4d85-a1f7-8487a2ab11a1)
![图片](https://github.com/user-attachments/assets/4a93c6a3-4fce-48bc-be46-80260226138b)

**Comment by skiffer-git** [comment]
I recommend you update to the latest version. If the issue persists, you can post it here.
