### ISSUE TITLE
error": "The specified key does not exist

### ISSUE THREAD

**Issue by 17674100338** [openimsdk/open-im-server#2592]
### OpenIM Server Version

3.8

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

docker 运行后发现openim-server运行不健康报错，请问这个是什么原因？

### Screenshots Link

![图片](https://github.com/user-attachments/assets/485a1545-828c-4a5f-b00a-99d9132fd23f)
![图片](https://github.com/user-attachments/assets/7cae99f2-278f-4832-a46c-606e64b15c79)

**Comment by skiffer-git** [comment]
What did you do to the program? If you changed any settings, it seems like it might have crashed

**Comment by 17674100338** [comment]
> 您对该计划做了什么？如果您更改了任何设置，它似乎已经崩溃了

我只给给.env里的MINIO_EXTERNAL_ADDRESS和GRAFANA_URL配置了本地ip地址，然后给openim-docker/scripts下的脚本给了执行权限，其他就没有其他操作了

**Comment by skiffer-git** [comment]
There’s a crash; can you check it? @withchao

**Comment by withchao** [comment]
This error is usually caused by a key configuration error in minio.
