### ISSUE TITLE
[BUG] User login and logout callback issues

### ISSUE THREAD

**Issue by 13353668075** [openimsdk/open-im-server#2594]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

1.在open-im-server webhooks 开启
afterUserOnline:
  enable: true
  timeout: 5
afterUserOffline:
  enable: true
  timeout: 5

2.进行用户的登录和退出
3.回调接收端无法获取回调信息

**Comment by simayubo** [comment]
![微信截图_20240909173405](https://github.com/user-attachments/assets/4b354fe2-3d46-427b-8480-93054383b422)
![微信截图_20240909173339](https://github.com/user-attachments/assets/ff0bb76a-1919-413b-80a7-a151dc1bcfbb)
不知道为什么，3.8把这个给注释了，我去掉注释重新编译有通知了

**Comment by icey-yu** [comment]
#2520
