### ISSUE TITLE
服务使用nginx代理，怎么配置

### ISSUE THREAD

**Issue by Larry-Arun** [OpenIMSDK/Open-IM-Server#260]
使用这个文档里的nginx配置，App登录不上啊
https://doc.rentsoft.cn/#/v2/server_deploy/nginx_config

报错截图
![image](https://user-images.githubusercontent.com/23025910/183033393-f505a7db-3dd4-4f10-b20b-0721ce39e187.png)

使用nginx，10001、10002和10004端口号是不是都改成443

**Comment by wangchuxiao-dev** [comment]
我们用443是因为使用了https，你根据自己的情况来

**Comment by Larry-Arun** [comment]
嗯，我使用443端口登录报错，我又改成了别的端口，改成http的，但是使用https://doc.rentsoft.cn/#/v2/server_deploy/nginx_config这里的配置，登录还是报错，我看nginx的日志，接收到了/auth/parse_token  这个post请求，但是/auth开头的请求并没有对应的location呀

**Comment by skiffer-git** [comment]
https://doc.rentsoft.cn/#/v2/server_deploy/nginx_config
