### ISSUE TITLE
[FEATURE REQUEST] Send a message to the specified member in the group, other members will not receive this message

### ISSUE THREAD

**Issue by zengyun261** [openimsdk/open-im-server#2605]
### Why this feature?

I’d like to use the Server API to send a message (event notification) to specific members within a group, but it seems there isn't an ideal method available. If I use private messaging, it creates a new conversation. The /msg/send_business_notification endpoint is closer to what I need, but it doesn't seem to support persistence, meaning if the user is offline, the message is lost.

### Suggested Solution

。。。

**Comment by zengyun261** [comment]
能否给/msg/send_business_notification增加个选项，用来支持离线分发

**Comment by Hookers** [comment]
@zengyun261 兄弟 我是一个读过源码的路人，看你说的这个方法里的实现是
sendMsgReq := msg.SendMsgReq{
		MsgData: &sdkws.MsgData{
			SendID: req.SendUserID,
			RecvID: req.RecvUserID,
			Content: []byte(jsonutil.StructToJsonString(&sdkws.NotificationElem{
				Detail: jsonutil.StructToJsonString(&struct {
					Key  string `json:"key"`
					Data string `json:"data"`
				}{Key: req.Key, Data: req.Data}),
			})),
			MsgFrom:     constant.SysMsgType,
			ContentType: constant.BusinessNotification,
			SessionType: constant.SingleChatType,
			CreateTime:  timeutil.GetCurrentTimestampByMill(),
			ClientMsgID: idutil.GetMsgIDByMD5(mcontext.GetOpUserID(c)),
			Options: config.GetOptionsByNotification(config.NotificationConfig{
				IsSendMsg:        false,
				ReliabilityLevel: 1,
				UnreadCount:      false,
			}),
		},
	}
	respPb, err := m.Client.SendMsg(c, &sendMsgReq)

我觉得你要是着急解决的话，可以试着自己手动调用 send_msg，传参和上面的类似，然后只用把 ReliabilityLevel 改成 2 就行了

**Comment by skiffer-git** [comment]
This feature is already supported in the commercial version.
