### ISSUE TITLE
[BUG] webhooks did not call back

### ISSUE THREAD

**Issue by larryhjl** [openimsdk/open-im-server#2629]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

按照 https://docs.openim.io/zh-Hans/restapi/webhooks/example 教程文档配置，回调服务器接口是用java写的，配置了beforeSendSingleMsg和afterSendSingleMsg的enable为true，但发送单聊消息之前和之后都没有回调接口，用的web端发送消息

### Screenshots Link

![openim1](https://github.com/user-attachments/assets/49b331fd-b20e-4d05-be5f-13e4105abdea)
![openim2](https://github.com/user-attachments/assets/1bdb71e8-c654-44b7-8203-e6339c302c58)

**Comment by LionYan-Coder** [comment]
![image](https://github.com/user-attachments/assets/dbd0d168-f378-4d07-8b23-311a32801429)
从 open-im-server  webhook模块源代码来看，你的路径需要配置为 /callbackExample/:command

**Comment by LionYan-Coder** [comment]
![image](https://github.com/user-attachments/assets/2b91bada-a48e-42a8-96b6-61a2b913fcc2)
并且你的配置不对，应该没有callback这个最外层的key， 从代码上来看 “https://docs.openim.io/zh-Hans/restapi/webhooks/example ” 文档已经过时了

**Comment by larryhjl** [comment]
> ![image](https://private-user-images.githubusercontent.com/162566948/368457947-dbd0d168-f378-4d07-8b23-311a32801429.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQwODMsIm5iZiI6MTcyNjY0Mzc4MywicGF0aCI6Ii8xNjI1NjY5NDgvMzY4NDU3OTQ3LWRiZDBkMTY4LWYzNzgtNGQwNy04YjIzLTMxMWEzMjgwMTQyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzE2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGNhMDU0OTQ2YzMzOGRiMmFkNzE2Y2I2ZjNiZjk3ZjY3MjY5NDFhNWMwMmI1NjhhZmUyMjIxZTlmYTljZGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dLKJeKXWrTpSX9BNL9w08oCr-PnmcEYwlms-pYGPiyg) 从 open-im-server webhook模块源代码来看，你的路径需要配置为 /callbackExample/:command

这个command是beforeSendSingleMsg或afterSendSingleMsg吗

**Comment by larryhjl** [comment]
是这样吗？
![openim1](https://github.com/user-attachments/assets/8afdd1a6-de10-47ab-98e8-07946653b142)
![openim2](https://github.com/user-attachments/assets/a40378d8-781d-43fd-a6a5-7d208165b8aa)

**Comment by LionYan-Coder** [comment]
> 是这样吗？ ![openim1](https://private-user-images.githubusercontent.com/126366186/368463830-8afdd1a6-de10-47ab-98e8-07946653b142.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ4MTksIm5iZiI6MTcyNjY0NDUxOSwicGF0aCI6Ii8xMjYzNjYxODYvMzY4NDYzODMwLThhZmRkMWE2LWRlMTAtNDdhYi05OGU4LTA3OTQ2NjUzYjE0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q1MWFjZDVjOWRhMGE0NGU0MGFlYTBkYjI5NDNjZmU4ODc5Y2E2M2I5MzM0NzQzMTQyMWVkZmZhYjI3MWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kgkLwQcVFEnb9DCRGCjbiPdLSceuVNEVdqxKe4teKWU) ![openim2](https://private-user-images.githubusercontent.com/126366186/368463841-a40378d8-781d-43fd-a6a5-7d208165b8aa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ4MTksIm5iZiI6MTcyNjY0NDUxOSwicGF0aCI6Ii8xMjYzNjYxODYvMzY4NDYzODQxLWE0MDM3OGQ4LTc4MWQtNDNmZC1hNmE1LTdkMjA4MTY1YjhhYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWM3Zjk5OTJkYzFjY2NiODY3MDAwNjY0MTI3NTUyYWNiNjBlZjhkZGQ4ZTcxYzVkMDNiN2JkZWYzOTQ0MDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mjaGeDQVTOmQ4X643vbR6vXu7BCHp-AAb4GfQTwMcD4)

应该不是，我记得前面有callback啥的。可以看看open-im-server原代码，不确定就弄成动态即可

**Comment by larryhjl** [comment]
> > 是这样吗？ ![openim1](https://private-user-images.githubusercontent.com/126366186/368463830-8afdd1a6-de10-47ab-98e8-07946653b142.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ4MTksIm5iZiI6MTcyNjY0NDUxOSwicGF0aCI6Ii8xMjYzNjYxODYvMzY4NDYzODMwLThhZmRkMWE2LWRlMTAtNDdhYi05OGU4LTA3OTQ2NjUzYjE0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q1MWFjZDVjOWRhMGE0NGU0MGFlYTBkYjI5NDNjZmU4ODc5Y2E2M2I5MzM0NzQzMTQyMWVkZmZhYjI3MWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kgkLwQcVFEnb9DCRGCjbiPdLSceuVNEVdqxKe4teKWU) ![openim2](https://private-user-images.githubusercontent.com/126366186/368463841-a40378d8-781d-43fd-a6a5-7d208165b8aa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ4MTksIm5iZiI6MTcyNjY0NDUxOSwicGF0aCI6Ii8xMjYzNjYxODYvMzY4NDYzODQxLWE0MDM3OGQ4LTc4MWQtNDNmZC1hNmE1LTdkMjA4MTY1YjhhYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWM3Zjk5OTJkYzFjY2NiODY3MDAwNjY0MTI3NTUyYWNiNjBlZjhkZGQ4ZTcxYzVkMDNiN2JkZWYzOTQ0MDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mjaGeDQVTOmQ4X643vbR6vXu7BCHp-AAb4GfQTwMcD4)
> 
> 应该不是，我记得前面有callback啥的。可以看看open-im-server原代码，不确定就弄成动态即可

你这里有webhooks.yaml配置正确的示例看看吗

**Comment by LionYan-Coder** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > > 是这样吗？ ![openim1](https://private-user-images.githubusercontent.com/126366186/368463830-8afdd1a6-de10-47ab-98e8-07946653b142.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ4MTksIm5iZiI6MTcyNjY0NDUxOSwicGF0aCI6Ii8xMjYzNjYxODYvMzY4NDYzODMwLThhZmRkMWE2LWRlMTAtNDdhYi05OGU4LTA3OTQ2NjUzYjE0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q1MWFjZDVjOWRhMGE0NGU0MGFlYTBkYjI5NDNjZmU4ODc5Y2E2M2I5MzM0NzQzMTQyMWVkZmZhYjI3MWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kgkLwQcVFEnb9DCRGCjbiPdLSceuVNEVdqxKe4teKWU) [OpenIM2] IISINR5CCI6IKPXVCj9.Eyjpc3MIIIJNAXRDWIY29TIIIWIYXVKIJOICMF3LMDDGH1 II6MTCYNJY0DUXOSWICOGF0ACI6I8XMJYZNJYXODYVMIZY4NDYZODQXLWE0MDM3O GHTPUFXUZQTSE1BQY1TSEYNTYMWC1BXOQQ3JLZVUDGLHBD1BS0LBKNPRFRFLMUMUMU0E1M1BRSZRAQSUYRJIWMHQWOTE4JTJGDXMTZWFZDCDC0XJTJGCMLMKHD3M0X 3jlcxvlc3qmwc1bxotrgf0ztttdi0mdkxofqwnzi4mzlajlgttw16luv4cgly 0mti3ntuyywninjblzjhkgggtcxyzvkmdnin2jkwyzotqqq0mdhjlgtttw16lvn .Mjageedqvtomq4x643vbr6vxu7bchp-ab4gfqtwmcd4)
> > 
> > 
> > Callback
> 
> 你这里有webhooks.yaml配置正确的示例看看吗

你现在webhooks.yaml配置是正确的， 
![image](https://github.com/user-attachments/assets/3dfc59e9-2262-4d62-b4c8-d38e7679109a)
这是我业务服务器的路由

**Comment by larryhjl** [comment]
> > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > 
> > 
> > > > 是这样吗？ ![openim1](https://private-user-images.githubusercontent.com/126366186/368463830-8afdd1a6-de10-47ab-98e8-07946653b142.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ4MTksIm5iZiI6MTcyNjY0NDUxOSwicGF0aCI6Ii8xMjYzNjYxODYvMzY4NDYzODMwLThhZmRkMWE2LWRlMTAtNDdhYi05OGU4LTA3OTQ2NjUzYjE0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q1MWFjZDVjOWRhMGE0NGU0MGFlYTBkYjI5NDNjZmU4ODc5Y2E2M2I5MzM0NzQzMTQyMWVkZmZhYjI3MWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kgkLwQcVFEnb9DCRGCjbiPdLSceuVNEVdqxKe4teKWU) [OpenIM2] IISINR5CCI6IKPXVCj9.Eyjpc3MIIIJNAXRDWIY29TIIIWIYXVKIJOICMF3LMDDGH1 II6MTCYNJY0DUXOSWICOGF0ACI6I8XMJYZNJYXODYVMIZY4NDYZODQXLWE0MDM3O GHTPUFXUZQTSE1BQY1TSEYNTYMWC1BXOQQ3JLZVUDGLHBD1BS0LBKNPRFRFLMUMUMU0E1M1BRSZRAQSUYRJIWMHQWOTE4JTJGDXMTZWFZDCDC0XJTJGCMLMKHD3M0X 3jlcxvlc3qmwc1bxotrgf0ztttdi0mdkxofqwnzi4mzlajlgttw16luv4cgly 0mti3ntuyywninjblzjhkgggtcxyzvkmdnin2jkwyzotqqq0mdhjlgtttw16lvn .Mjageedqvtomq4x643vbr6vxu7bchp-ab4gfqtwmcd4)
> > > 
> > > 
> > > Callback
> > 
> > 
> > 你这里有webhooks.yaml配置正确的示例看看吗
> 
> 你现在webhooks.yaml配置是正确的， ![image](https://private-user-images.githubusercontent.com/162566948/368473540-3dfc59e9-2262-4d62-b4c8-d38e7679109a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDk1NzcsIm5iZiI6MTcyNjY0OTI3NywicGF0aCI6Ii8xNjI1NjY5NDgvMzY4NDczNTQwLTNkZmM1OWU5LTIyNjItNGQ2Mi1iNGM4LWQzOGU3Njc5MTA5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwODQ3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDE4NWI5YmVjODAxYWQxZjRiNWM0NDEzZmFmNTVlZGExN2UzYTNiZGZkY2E2ZGMxNjI4ZTljZGI1MjAxNjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ph0DykY1izt9Bm5BMfMBO-pcSRT371d5RhIzEgVeGig) 这是我业务服务器的路由

我看了日志，都没调用配置的URL

**Comment by LionYan-Coder** [comment]
> > > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > > 
> > > 
> > > > > 是这样吗？ ![openim1](https://private-user-images.githubusercontent.com/126366186/368463830-8afdd1a6-de10-47ab-98e8-07946653b142.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ4MTksIm5iZiI6MTcyNjY0NDUxOSwicGF0aCI6Ii8xMjYzNjYxODYvMzY4NDYzODMwLThhZmRkMWE2LWRlMTAtNDdhYi05OGU4LTA3OTQ2NjUzYjE0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q1MWFjZDVjOWRhMGE0NGU0MGFlYTBkYjI5NDNjZmU4ODc5Y2E2M2I5MzM0NzQzMTQyMWVkZmZhYjI3MWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kgkLwQcVFEnb9DCRGCjbiPdLSceuVNEVdqxKe4teKWU) [OpenIM2] IISINR5CCI6IKPXVCj9.Eyjpc3MIIIJNAXRDWIY29TIIIWIYXVKIJOICMF3LMDDGH1 II6MTCYNJY0DUXOSWICOGF0ACI6I8XMJYZNJYXODYVMIZY4NDYZODQXLWE0MDM3O GHTPUFXUZQTSE1BQY1TSEYNTYMWC1BXOQQ3JLZVUDGLHBD1BS0LBKNPRFRFLMUMUMU0E1M1BRSZRAQSUYRJIWMHQWOTE4JTJGDXMTZWFZDCDC0XJTJGCMLMKHD3M0X 3jlcxvlc3qmwc1bxotrgf0ztttdi0mdkxofqwnzi4mzlajlgttw16luv4cgly 0mti3ntuyywninjblzjhkgggtcxyzvkmdnin2jkwyzotqqq0mdhjlgtttw16lvn .Mjageedqvtomq4x643vbr6vxu7bchp-ab4gfqtwmcd4)
> > > > 
> > > > 
> > > > Callback
> > > 
> > > 
> > > 你这里有webhooks.yaml配置正确的示例看看吗
> > 
> > 
> > 你现在webhooks.yaml配置是正确的， ![image](https://private-user-images.githubusercontent.com/162566948/368473540-3dfc59e9-2262-4d62-b4c8-d38e7679109a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDk1NzcsIm5iZiI6MTcyNjY0OTI3NywicGF0aCI6Ii8xNjI1NjY5NDgvMzY4NDczNTQwLTNkZmM1OWU5LTIyNjItNGQ2Mi1iNGM4LWQzOGU3Njc5MTA5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwODQ3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDE4NWI5YmVjODAxYWQxZjRiNWM0NDEzZmFmNTVlZGExN2UzYTNiZGZkY2E2ZGMxNjI4ZTljZGI1MjAxNjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ph0DykY1izt9Bm5BMfMBO-pcSRT371d5RhIzEgVeGig) 这是我业务服务器的路由
> 
> 我看了日志，都没调用配置的URL

我这边是没有问题可以调用的。你应该去看 im 的日志，有没有发起webhook请求，发起了但是你业务服务器

**Comment by LionYan-Coder** [comment]
> > > > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> > > 
> > > 
> > > > > 是这样吗？ ![openim1](https://private-user-images.githubusercontent.com/126366186/368463830-8afdd1a6-de10-47ab-98e8-07946653b142.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQ4MTksIm5iZiI6MTcyNjY0NDUxOSwicGF0aCI6Ii8xMjYzNjYxODYvMzY4NDYzODMwLThhZmRkMWE2LWRlMTAtNDdhYi05OGU4LTA3OTQ2NjUzYjE0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwNzI4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2Q1MWFjZDVjOWRhMGE0NGU0MGFlYTBkYjI5NDNjZmU4ODc5Y2E2M2I5MzM0NzQzMTQyMWVkZmZhYjI3MWIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kgkLwQcVFEnb9DCRGCjbiPdLSceuVNEVdqxKe4teKWU) [OpenIM2] IISINR5CCI6IKPXVCj9.Eyjpc3MIIIJNAXRDWIY29TIIIWIYXVKIJOICMF3LMDDGH1 II6MTCYNJY0DUXOSWICOGF0ACI6I8XMJYZNJYXODYVMIZY4NDYZODQXLWE0MDM3O GHTPUFXUZQTSE1BQY1TSEYNTYMWC1BXOQQ3JLZVUDGLHBD1BS0LBKNPRFRFLMUMUMU0E1M1BRSZRAQSUYRJIWMHQWOTE4JTJGDXMTZWFZDCDC0XJTJGCMLMKHD3M0X 3jlcxvlc3qmwc1bxotrgf0ztttdi0mdkxofqwnzi4mzlajlgttw16luv4cgly 0mti3ntuyywninjblzjhkgggtcxyzvkmdnin2jkwyzotqqq0mdhjlgtttw16lvn .Mjageedqvtomq4x643vbr6vxu7bchp-ab4gfqtwmcd4)
> > > > 
> > > > 
> > > > Callback
> > > 
> > > 
> > > 你这里有webhooks.yaml配置正确的示例看看吗
> > 
> > 
> > 你现在webhooks.yaml配置是正确的， ![image](https://private-user-images.githubusercontent.com/162566948/368473540-3dfc59e9-2262-4d62-b4c8-d38e7679109a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDk1NzcsIm5iZiI6MTcyNjY0OTI3NywicGF0aCI6Ii8xNjI1NjY5NDgvMzY4NDczNTQwLTNkZmM1OWU5LTIyNjItNGQ2Mi1iNGM4LWQzOGU3Njc5MTA5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwODQ3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDE4NWI5YmVjODAxYWQxZjRiNWM0NDEzZmFmNTVlZGExN2UzYTNiZGZkY2E2ZGMxNjI4ZTljZGI1MjAxNjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ph0DykY1izt9Bm5BMfMBO-pcSRT371d5RhIzEgVeGig) 这是我业务服务器的路由
> 
> 我看了日志，都没调用配置的URL

我这边是没有问题可以调用的。你应该去看 im 的日志，有发起webhook请求的话，就去检查你的业务服务器是不是哪里不对

**Comment by printlin** [comment]
I handled callbacks this way in Java projects and successfully validated them in production environments. 
openim config:
```
callback:
  url: "http://xxxxx.com/webhook"
```

java controller:
```
    @RequestMapping("/webhook/{cmd}")
    public String openIMWebHook(@PathVariable("cmd") String cmd, HttpServletRequest request){
        String requestData = readRequestData(request);
        // WebHookType.AFTER_SEND_SINGLE_MSG value is "callbackAfterSendSingleMsgCommand"
        if(WebHookType.AFTER_SEND_SINGLE_MSG.equals(cmd)){
            return webHookService.afterSendSingleMsg(requestData);
        }
        return "not match cmd";
    }
    private String readRequestData(HttpServletRequest request){
        StringBuilder body = new StringBuilder(2048);
        try (BufferedReader reader = request.getReader()) {
            char[] chars = new char[1024];
            int read;
            while ((read = reader.read(chars)) != -1) {
                body.append(chars, 0, read);
            }
        } catch (Exception ignored) { }
        return body.toString();
    }
```

**Comment by icey-yu** [comment]
> 是这样吗？ ![openim1](https://private-user-images.githubusercontent.com/126366186/368463830-8afdd1a6-de10-47ab-98e8-07946653b142.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjAwMjMsIm5iZiI6MTcyODM1OTcyMywicGF0aCI6Ii8xMjYzNjYxODYvMzY4NDYzODMwLThhZmRkMWE2LWRlMTAtNDdhYi05OGU4LTA3OTQ2NjUzYjE0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwMzU1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Mjc5ZDA4ZTUwNGExMTQwMTQ3MWZhYTAyYzAxZmRkODllMjgwZDc5ZmEwNWNiZjJhYmQ5ZTA3NWVkODcwNjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5AnRu4YVu0IcfbBEOxfgX_5lS2Kkba5odgdKyeBX4Ws) ![openim2](https://private-user-images.githubusercontent.com/126366186/368463841-a40378d8-781d-43fd-a6a5-7d208165b8aa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNjAwMjMsIm5iZiI6MTcyODM1OTcyMywicGF0aCI6Ii8xMjYzNjYxODYvMzY4NDYzODQxLWE0MDM3OGQ4LTc4MWQtNDNmZC1hNmE1LTdkMjA4MTY1YjhhYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwMzU1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDU3NjdhMTcwZDMwNTRjYjkyYjdiYTM0NTBkOTdkMmM5Yjk2MGE2YTQ0NTZhYjZjZjA1YjQxZTExMjM3NTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.GKBWdtv_n-IowTNLpYZDeurNf9s6YwpZmCUdj0P2yDM)

According to this configuration, the webhook route for beforeSendSingleMsg is http://xxx/robot/callbackExample/callbackBeforeSendSingleMsgCommand. You can check if the open route path is correct. If the log level is above 4, you can filter the logs by the keyword “webhook” and the webhook URL to confirm whether the webhook has been called.

**Comment by WindRain20140210** [comment]
docker部署方式，在哪里修改webhooks的配置文件？

**Comment by icey-yu** [comment]
https://docs.openim.io/zh-Hans/guides/gettingStarted/dockerCompose

**Comment by WindRain20140210** [comment]
![image](https://github.com/user-attachments/assets/a4f0538e-0874-43fe-be85-055bff9bf521)
按以上文档在.env 文件中增加了

**Comment by icey-yu** [comment]
I'm sorry our documentation wasn't clear enough. The file that needs to be modified is the docker-compose.yml file, and the changes should be added under the environment section of openim-server. We will update the documentation to make this clearer.
