### ISSUE TITLE
openImMessagePort service does not start normally,not initiated port is 10130

### ISSUE THREAD

**Issue by icejd** [OpenIMSDK/Open-IM-Server#264]
用文档https://doc.rentsoft.cn/#/v2/server_deploy/docker_singe?id=%e4%b8%80%e9%94%ae%e9%83%a8%e7%bd%b2
的一键部署方式出现
![image](https://user-images.githubusercontent.com/56807705/184116531-81e186e8-a931-4353-96dd-615eb100baef.png)
****
日志里显示
start msg rpc server, port:  10130
panic: kafka: invalid configuration (You must provide at least one broker address)

VM虚拟机(Cenotos 7 64)部署,内存5G

**Comment by skiffer-git** [comment]
You must provide at least one broker addres

**Comment by icejd** [comment]
默认配置,啥都没动

**Comment by peter56191884** [comment]
降低版本即可解决。即：

1.搜索代码`wurstmeister/kafka`，改为`wurstmeister/kafka:2.13-2.8.1`；
2.关闭并删除原有的kafka容器，`docker stop 【容器ID】`，`docker rm 【容器ID】`；
3.`./install_im_server.sh`
