### ISSUE TITLE
When I send a message using the sendMessageNotOss function, I get the error message "10002 unexpected end of JSON input."

### ISSUE THREAD

**Issue by ttyob** [openimsdk/open-im-server#2651]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

IOS客户端创建createImageMessageByURL图片消息，通过sendMessageNotOss发送消息，报错10002  unexpected end of JSON input，服务器没有日志信息
安卓测试正常

IOS客户端sdk版本：3.8.0

**Comment by FGadvancer** [comment]
You need to check whether the result of createXXX is an empty string. If it is, make sure to fetch your own user information once after logging in, before createXXX.

**Comment by simayubo** [comment]
> 需要检查 createXXX 的结果是否为空字符串，如果是空字符串，请确保在登录后、createXXX 之前获取一次自己的用户信息。

`{
    "clientMsgID": "961296690b591a4a6e489b0f392948e9",
    "createTime": 1726817296151,
    "sendTime": 1726817296151,
    "sessionType": 0,
    "sendID": "1801542",
    "msgFrom": 100,
    "contentType": 102,
    "senderPlatformID": 1,
    "senderNickname": "遗世独立",
    "senderFaceUrl": "https://xxx.com/static_data/uploaddata/avatar/1/1801542.gif?_t=1683340236",
    "seq": 0,
    "isRead": false,
    "status": 1,
    "pictureElem": {
        "sourcePicture": {
            "uuid": "161a89049113f1bccad75c05aa9409",
            "type": "image/jpg",
            "size": 168453,
            "width": 3000,
            "height": 3000,
            "url": "https://xxx.com/static_data/uploaddata/im_file/20240920/82ff1402e0119f4a82a4a43c56efb815.jpg"
        },
        "bigPicture": {
            "uuid": "161a89049113f1bccad75c05aa9409",
            "type": "image/jpg",
            "size": 168453,
            "width": 3000,
            "height": 3000,
            "url": "https://xxx.com/static_data/uploaddata/im_file/20240920/82ff1402e0119f4a82a4a43c56efb815.jpg"
        },
        "snapshotPicture": {
            "uuid": "161a89049113f1bccad75c05aa9409",
            "type": "image/jpg",
            "size": 168453,
            "width": 3000,
            "height": 3000,
            "url": "https://xxx.com/static_data/uploaddata/im_file/20240920/82ff1402e0119f4a82a4a43c56efb815.jpg"
        }
    }
}`

**Comment by simayubo** [comment]
> You need to check whether the result of createXXX is an empty string. If it is, make sure to fetch your own user information once after logging in, before createXXX.

The returned data is normal, and Android can send it normally

`{
    "clientMsgID": "961296690b591a4a6e489b0f392948e9",
    "createTime": 1726817296151,
    "sendTime": 1726817296151,
    "sessionType": 0,
    "sendID": "1801542",
    "msgFrom": 100,
    "contentType": 102,
    "senderPlatformID": 1,
    "senderNickname": "遗世独立",
    "senderFaceUrl": "https://xxx.com/static_data/uploaddata/avatar/1/1801542.gif?_t=1683340236",
    "seq": 0,
    "isRead": false,
    "status": 1,
    "pictureElem": {
        "sourcePicture": {
            "uuid": "161a89049113f1bccad75c05aa9409",
            "type": "image/jpg",
            "size": 168453,
            "width": 3000,
            "height": 3000,
            "url": "https://xxx.com/static_data/uploaddata/im_file/20240920/82ff1402e0119f4a82a4a43c56efb815.jpg"
        },
        "bigPicture": {
            "uuid": "161a89049113f1bccad75c05aa9409",
            "type": "image/jpg",
            "size": 168453,
            "width": 3000,
            "height": 3000,
            "url": "https://xxx.com/static_data/uploaddata/im_file/20240920/82ff1402e0119f4a82a4a43c56efb815.jpg"
        },
        "snapshotPicture": {
            "uuid": "161a89049113f1bccad75c05aa9409",
            "type": "image/jpg",
            "size": 168453,
            "width": 3000,
            "height": 3000,
            "url": "https://xxx.com/static_data/uploaddata/im_file/20240920/82ff1402e0119f4a82a4a43c56efb815.jpg"
        }
    }
}`

**Comment by skiffer-git** [comment]
> You need to check whether the result of createXXX is an empty string. If it is, make sure to fetch your own user information once after logging in, before createXXX.

Should we optimize this so that if the user information is empty, the SDK retrieves it internally?
