### ISSUE TITLE
[BUG] Minio publicRead setting of true will cause the service to fail to start.

### ISSUE THREAD

**Issue by LionYan-Coder** [openimsdk/open-im-server#2662]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

My minio publick read was always false, after I changed it to true, restarting failed and reported error " MinIO check failed: Resource requested is unreadable, please reduce your request rate."

### Screenshots Link

![image](https://github.com/user-attachments/assets/614550ad-f149-4cee-bc58-5e08ad34b9ea)

**Comment by skiffer-git** [comment]
Which configuration item did you modify?

**Comment by skiffer-git** [comment]
How did you make the modification?

**Comment by LionYan-Coder** [comment]
> How did you make the modification?你是如何进行修改的？

<img width="1022" alt="截屏2024-09-29 18 34 14" src="https://github.com/user-attachments/assets/3c370980-8bc7-4087-9bba-eff213fc2383">

**Comment by mo3et** [comment]
externalAddress need to set true IP, not localhost or 127.0.0.1.

Need you use public network address.
