### ISSUE TITLE
[Deployment] When I deploy in the Tencent Cloud, an error occurred, as the step in the image show. How to solve it?

### ISSUE THREAD

**Issue by timothyzhao0507** [openimsdk/open-im-server#2665]
### OpenIM Server Version

v3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Issue Description and Steps to Reproduce

见贴图

### Screenshots Link

![openim_mage_error](https://github.com/user-attachments/assets/f3790991-ea9d-4f0f-ae8d-17b66881651d)

**Comment by FGadvancer** [comment]
It seems like a compilation error caused by a CI that wasn't properly detected. You can try to git pull and then attempt to compile and start again.

**Comment by skiffer-git** [comment]
![982db0b7e75093d7012e75ee76bcc7e](https://github.com/user-attachments/assets/ff77aced-8442-44b7-93a5-55e9ec8dd3e7)
I think it’s a network issue on your end. I just tried it myself, and it works fine.

**Comment by skiffer-git** [comment]
What version of Go are you using?

**Comment by timothyzhao0507** [comment]
> What version of Go are you using?

go 1.23.1

**Comment by timothyzhao0507** [comment]
> It seems like a compilation error caused by a CI that wasn't properly detected. You can try to git pull and then attempt to compile and start again.

What is the "CI"?

**Comment by skiffer-git** [comment]
You can try to git pull and then attempt to compile again.
