### ISSUE TITLE
[Deployment] Error while dialing: dial top 127.0.0.1:2379: connect: connection refused

### ISSUE THREAD

**Issue by timothyzhao0507** [openimsdk/open-im-server#2689]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Issue Description and Steps to Reproduce

I have deployed MongoDB, Redis, Kafka, MinIO. When I use "mage start", It occurred an error as title and the screenshot.

### Screenshots Link

![OpenIM_20240929](https://github.com/user-attachments/assets/771cb070-950c-4a03-b0f1-03a1f95f70aa)

**Comment by skiffer-git** [comment]
You need to deploy ETCD.

**Comment by timothyzhao0507** [comment]
> You need to deploy ETCD.

Thank you !
It works successfull.
