### ISSUE TITLE
[Other]: what is the initial password for the user imported by the Server API (/user/user_register) 

### ISSUE THREAD

**Issue by aningco** [openimsdk/open-im-server#2690]
### What would you like to share?

The Server API (/user/user_register) imports user without providing password parameter,so what is initial password for the user imported by this API ？

**Comment by skiffer-git** [comment]
The user's password is only stored in the Chat system; the IMServer does not store passwords.

**Comment by aningco** [comment]
The API only provide three parameter “userID”,“nickname”,“faceURL"  without password, how to know the password for user to login

**Comment by skiffer-git** [comment]
OpenIM is just a messaging system; all user information, including passwords, is stored in your business system.

**Comment by skiffer-git** [comment]
![image](https://github.com/user-attachments/assets/a9f4e608-ded0-4e39-8ee1-d9fbaaa63e0b)
