### ISSUE TITLE
[DOC]: Questions about modifying group information documents in server apis

### ISSUE THREAD

**Issue by ylx19931228** [openimsdk/open-im-server#2695]
Server Apis 修改群组信息中，请求参数实例与下面的请求字段名解释。存在请求参数实例中不存在。

文档地址：https://docs.openim.io/zh-Hans/restapi/apis/groupManagement/setGroupInfo

![Uploading 微信图片_20241007152121.png…]()

**Comment by icey-yu** [comment]
The image failed to load. Could you describe the issue in detail?
