### ISSUE TITLE
The large image displayed on the chat page cannot be loaded, but the small image can be loaded.

### ISSUE THREAD

**Issue by wzk-jiuyinghuo** [openimsdk/open-im-server#2704]
### What would you like to share?

在聊天页面显示的大图无法显示，而小图可以
![Snipaste_2024-10-09_17-51-08](https://github.com/user-attachments/assets/9f40e5be-7080-4f89-beea-c4e6e0594330)

**Comment by skiffer-git** [comment]
Which version are you using? Please try it with the 3.8 version.
