### ISSUE TITLE
[BUG] login api error: header must have token: 1001 ArgsError

### ISSUE THREAD

**Issue by knight0zh** [openimsdk/open-im-server#2707]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

macOS (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

前端使用open-im-flutter-demo，后端服务直接docker-composer部署。
直接在app上新用户注册，客户端返回报错：

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6720): │ [http-request] [POST] http://192.168.3.6:10002/account/code/send
I/flutter ( 6720): │ Data: {
I/flutter ( 6720): │   "areaCode": "+86",
I/flutter ( 6720): │   "phoneNumber": "13482509858",
I/flutter ( 6720): │   "email": null,
I/flutter ( 6720): │   "usedFor": 1,
I/flutter ( 6720): │   "invitationCode": null
I/flutter ( 6720): │ }
I/flutter ( 6720): │ Headers: {
I/flutter ( 6720): │   "operationID": "1728609583330",
I/flutter ( 6720): │   "content-type": "application/json"
I/flutter ( 6720): │ }
I/flutter ( 6720): └──────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6720): ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter ( 6720): │ [http-response] [POST] http://192.168.3.6:10002/account/code/send
I/flutter ( 6720): │ Status: 200
I/flutter ( 6720): │ Message: OK
I/flutter ( 6720): │ Data: {
I/flutter ( 6720): │   "errCode": 1001,
I/flutter ( 6720): │   "errMsg": "ArgsError",
I/flutter ( 6720): │   "errDlt": "header must have token: 1001 ArgsError"
I/flutter ( 6720): │ }
I/flutter ( 6720): │ Headers: {
I/flutter ( 6720): │   "access-control-allow-credentials": [
I/flutter ( 6720): │     "false"
I/flutter ( 6720): │   ],
I/flutter ( 6720): │   "access-control-allow-headers": [
I/flutter ( 6720): │     "*"
I/flutter ( 6720): │   ],
I/flutter ( 6720): │   "date": [
I/flutter ( 6720): │     "Fri, 11 Oct 2024 01:19:21 GMT"
I/flutter ( 6720): │   ],
I/flutter ( 6720): │   "access-control-allow-origin": [
I/flutter ( 6720): │     "*"
I/flutter ( 6720): │   ],
I/flutter ( 6720): │   "vary": [
I/flutter ( 6720): │     "Accept-Encoding"
I/flutter ( 6720): │   ],
I/flutter ( 6720): │   "access-control-allow-methods": [
I/flutter ( 6720): │     "*"
I/flutter ( 6720): │   ],
I/flutter ( 6720): │   "content-encoding": [
I/flutter ( 6720): │     "gzip"
I/flutter ( 6720): │   ],
I/flutter ( 6720): │   "content-length": [
I/flutter ( 6720): │     "96"
I/flutter ( 6720): │   ],
I/flutter ( 6720): │   "access-control-expose-headers": [
I/flutter ( 6720): │     "Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma,FooBar"
I/flutter ( 6720): │   ],
I/flutter ( 6720): │   "content-type": [
I/flutter ( 6720): │     "application/json"
I/flutter ( 6720): │   ],
I/flutter ( 6720): │   "access-control-max-age": [
I/flutter ( 6720): │     "172800"
I/flutter ( 6720): │   ]
I/flutter ( 6720): │ }
I/flutter ( 6720): └──────────────────────────────────────────────────────────────────────────────────────────────────────────────
[OpenIM-App] ** e:ArgsError s:, isError [false]

登录前的接口出现了token验证，属于预期效果吗，还是我哪里配置错了，客服端服务端代码都没改过只改了服务器ip

**Comment by skiffer-git** [comment]
http://192.168.3.6:10002/account/code/send->http://192.168.3.6:10008/account/code/send

**Comment by skiffer-git** [comment]
You only need to modify the IP in the demo; the port should not be changed.
