### ISSUE TITLE
[DOC]: Regarding the join group interface, it prompts parameter error

### ISSUE THREAD

**Issue by ylx19931228** [openimsdk/open-im-server#2711]
https://docs.openim.io/zh-Hans/restapi/apis/groupManagement/joinGroup

加入群组,请求参数如下
{"groupID":"1","inviterUserID":"490","joinSource":1}

 im服务器提示
异常code：1001,异常信息：ArgsError

**Comment by mo3et** [comment]
This issue need our check the problem. maybe is bug. Thanks for your feedback.

**Comment by ylx19931228** [comment]
The issue been solved?

**Comment by ylx19931228** [comment]
请问，这个问题。会修复在docker发布的版本中吗？

**Comment by mo3et** [comment]
> 请问，这个问题。会修复在docker发布的版本中吗？

Need to wait for the release of the new version before there will be a new docker Image release.
