### ISSUE TITLE
pc web端断网重连后，断网期间的消息没有恢复到前端页面

### ISSUE THREAD

**Issue by jaonzyx** [OpenIMSDK/Open-IM-Server#272]
我举个例子，用户登录pc端(windows/mac)客户端后，一版情况下是不会退出的，这时，合上笔记本或电脑休眠后，网络会断开。当再次打开笔记本或让主机退出休眠状态，im会重连，但是这期间其他用户发送的信息是不会同步到前端的。刷新页面后，才会同步

**Comment by tanght1994** [comment]
好像是的，我也遇到了这个问题，要不你提个pull，修复一下？我不会。。。
