### ISSUE TITLE
[Deployment] I can not access the port 11001, what is the problem?

### ISSUE THREAD

**Issue by timothyzhao0507** [openimsdk/open-im-server#2722]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Issue Description and Steps to Reproduce

[Deployment] I have deployed open-im-server & chat, and started successfully, but I can not access the port 11001, what is the problem?

### Screenshots Link

![openim-server-11001](https://github.com/user-attachments/assets/d0e1ad7d-a286-4cf4-96a5-46a5d72cb3d1)
![openim-chat-11001](https://github.com/user-attachments/assets/f4aef0b6-82da-4f9d-b0fa-1ce0a1a2f7e7)

**Comment by skiffer-git** [comment]
Run the docker ps command and take a screenshot to see the output.

**Comment by skiffer-git** [comment]
You need to start the *openim-web-front* container and open port 11001 to allow access.
