### ISSUE TITLE
[BUG] After upgrading to v3.8.1, I can no longer receive the OnUserStatusChanged callback.

### ISSUE THREAD

**Issue by jiangzc16** [openimsdk/open-im-server#2725]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (ARM)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

1、IMSDK.on(CbEvents.OnUserStatusChanged, userStatusChangeHandler);
I can no longer receive the OnUserStatusChanged callback.
2、data is [] ：
IMSDK.subscribeUsersStatus([userID]).then(({data}: WsResponse<UserOnlineState[]>) => {
        console.log('subscribeUsersStatus =>',data, userID)
});
![360截图20241015143547424](https://github.com/user-attachments/assets/833830ed-e40b-4f00-a901-4838282be335)

**Comment by icey-yu** [comment]
Based on our tests, both the OnUserStatusChanged callback and the return content from subscribeUsersStatus appear to be functioning correctly. If you could provide more detailed log information, we would be happy to assist in resolving the issue.

**Comment by skiffer-git** [comment]
The new version has removed all scripts, so this issue will no longer exist.
