### ISSUE TITLE
[BUG] OSS setting PUBLICREAD will cause inaccessibility

### ISSUE THREAD

**Issue by cipchk** [openimsdk/open-im-server#2727]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

事实上在 openimsdk/open-im-server#2317 已经有人报告过，但是被自动关闭了。

```
OPENIM_RPC_THIRD_OBJECT_ENABLE=oss
OPENIM_RPC_THIRD_OBJECT_OSS_ENDPOINT=https://xxxx.aliyuncs.com
OPENIM_RPC_THIRD_OBJECT_OSS_BUCKET=xxx-im
OPENIM_RPC_THIRD_OBJECT_OSS_BUCKETURL=https://xxxx.xxxx.xxxx
OPENIM_RPC_THIRD_OBJECT_OSS_ACCESSKEYID=xxxxx
OPENIM_RPC_THIRD_OBJECT_OSS_ACCESSKEYSECRET=xxxxx
OPENIM_RPC_THIRD_OBJECT_OSS_PUBLICREAD=true # 是否公开读取
```

Docker compose:

```
      - IMENV_OPENIM_RPC_THIRD_OBJECT_ENABLE=${OPENIM_RPC_THIRD_OBJECT_ENABLE}
      - IMENV_OPENIM_RPC_THIRD_OBJECT_OSS_ENDPOINT=${OPENIM_RPC_THIRD_OBJECT_OSS_ENDPOINT}
      - IMENV_OPENIM_RPC_THIRD_OBJECT_OSS_BUCKET=${OPENIM_RPC_THIRD_OBJECT_OSS_BUCKET}
      - IMENV_OPENIM_RPC_THIRD_OBJECT_OSS_BUCKETURL=${OPENIM_RPC_THIRD_OBJECT_OSS_BUCKETURL}
      - IMENV_OPENIM_RPC_THIRD_OBJECT_OSS_ACCESSKEYID=${OPENIM_RPC_THIRD_OBJECT_OSS_ACCESSKEYID}
      - IMENV_OPENIM_RPC_THIRD_OBJECT_OSS_ACCESSKEYSECRET=${OPENIM_RPC_THIRD_OBJECT_OSS_ACCESSKEYSECRET}
      - IMENV_OPENIM_RPC_THIRD_OBJECT_OSS_PUBLICREAD=${OPENIM_RPC_THIRD_OBJECT_OSS_PUBLICREAD}
```

图片的请求地址为：

```
https://im_api(port: 10002)/api/object/3/msg_picture_cc83598702168c07b2533b125b340f6d.jpg
```

会被 302 跳转到

```
请求网址:
https://xxx-im.oss-xxxx.aliyuncs.com/openim%2Fdata%2Fhash%2F14b34f8be36f792d0dc61c876df69129
请求方法:
GET
状态代码:
403 Forbidden
```

**另外一个细节就是BUCKETURL**

当我设置提自己的域名时（OSS已经绑定正确了），但是消息里面依然还是使用 OSS 域的址，就像 `https://xxx-im.oss-xxxx.aliyuncs.com/openim%2Fdata%2Fhash%2F14b34f8be36f792d0dc61c876df69129` ，依然使用的是 `aliyuncs.cm`，而不是我所配置的域名。

> 当然这一点我不确认是不是因为 `publicRead` 错误产生的并发症。

**Comment by WindRain20140210** [comment]
这个问题有人看下吗？

**Comment by WindRain20140210** [comment]
这个问题请问好了吗？

**Comment by WindRain20140210** [comment]
oss是没实现分片上传吗？没看到调用UploadPart方法

**Comment by WindRain20140210** [comment]
OSS 预签名url上传，如何让前端上传呢？

**Comment by withchao** [comment]
The returned URL is the API address and will be redirected to the corresponding S3
There is sharding, refer to SDK implementation, no OSS.
https://github.com/openimsdk/openim-sdk-core/blob/main/internal/third/file/upload.go

**Comment by cipchk** [comment]
@withchao 我觉得 BUCKETURL 的存在说明我们想走域名的流量（例如我们域名会通过 Cloudflare 来解决 CDN 问题），而不是再次重写向 aliyuncs.com 域名的吧。
