### ISSUE TITLE
图片上传cos的文件能否加个路径啊

### ISSUE THREAD

**Issue by lrxz789** [OpenIMSDK/Open-IM-Server#274]
文件全部在根目录，顶不住啦

**Comment by shoyu666** [comment]
是服务器的根目录顶不住么? 是否是本地部署了Minio？
图片上传是上传到对象存储(cos,oss,minio等)，im透传的只是对象存储后的回执。
如果是因为用了本地部署的Minio,参考Minio修改目录

**Comment by Mihoks** [comment]
估计是想问不方便清理删除，比如群消息删除群消息时删除对应文件夹图片，或者文档的归类这样吧
