### ISSUE TITLE
How to stop sending notifications to become friends

### ISSUE THREAD

**Issue by aningco** [openimsdk/open-im-server#2753]
### What would you like to share?

Open-im-server Version :  v3.8.1
ServerAPI :import_friend 
Request URL ：{API_ADDRESS}/friend/import_friend

When the business system imports friend relationships through the  above Server API , it will receive many "become friend" message notifications in web end. Is there any way to silently become a friend or not to send  "become friend"  notifications

**Comment by skiffer-git** [comment]
Modify the isSendMsg field to false in the notification.yml file.

**Comment by aningco** [comment]
it works ! appreciate for you help very much !
