### ISSUE TITLE
[Other]: Help me about authenticated users

### ISSUE THREAD

**Issue by vzenix** [openimsdk/open-im-server#2754]
### What would you like to share?

I find it, https://doc.rentsoft.cn/restapi/apis/authenticationManagement/getAdminToken

¿Can customize it?, I want to add into an app mobile this chat, but i need costomize the autentication for accept the session of this mobile app

¿Someone can help me?

**Comment by vzenix** [comment]
> [Join slack 🤖](https://join.slack.com/t/openimsdk/shared_invite/zt-22720d66b-o_FvKxMTGXtcnnnHiMqe9Q) to connect and communicate with our developers.

Link to slack doesn't work, ¿can share again?

**Comment by FGadvancer** [comment]
Hello, I saw your question regarding custom token verification. The getAdminToken mentioned in the documentation is one way for openimserver to obtain a verification token. If you want to customize the way you get the token, it falls under your own business logic. If you have your own server, there should be two tokens: one for your own server and one for openimserver. You can directly call the API in the documentation to get the admin token and then use it to call the IM interface to get the user token. If not, openim also provides an open-source chat repository that simulates user login ([chat](https://github.com/openimsdk/chat)), password input, and other operations in an app scenario. When your mobile app obtains the token, it should get two tokens: one for the business system and one for openimserver. As for the business system token, you are completely free to customize how it is generated. I hope this answers your question.
![Relationship Architecture Diagram](https://github.com/openimsdk/open-im-server/blob/main/docs/images/oepnim-design.png)

**Comment by skiffer-git** [comment]
https://github.com/openimsdk/open-im-server/blob/main/docs/images/oepnim-design.png

**Comment by skiffer-git** [comment]
![image](https://github.com/user-attachments/assets/651b3071-2b04-46ed-851c-33ebbc937540)

**Comment by skiffer-git** [comment]
Your own business system is represented as "Your App Server" in the diagram. User login, registration, and authentication are handled by your business system.
