### ISSUE TITLE
[BUG] markConversationMessageAsRead fail

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-server#2765]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

After the client successfully marks the message as read, it retrieves data from the server again, but it's still the previous data.

**Comment by OrrinHatch** [comment]
![WechatIMG225](https://github.com/user-attachments/assets/47907b4a-4f22-4cf3-806f-9c760678998d)

**Comment by OrrinHatch** [comment]
After refreshing the browser, IMSDK.getTotalUnreadMsgCount returns the original unread message count.

**Comment by OrrinHatch** [comment]
https://github.com/user-attachments/assets/748c3255-087a-4c80-b70d-4e1796d463c6

**Comment by Bloomingg** [comment]
Please collect the complete logs of the client console (including logs after removing unreads and refreshing the page), ensuring that all logs printed by wasm_exec.js are included.

**Comment by OrrinHatch** [comment]
In the video, the unread count for the conversation with '李四' can be cleared

**Comment by OrrinHatch** [comment]
> Please collect the complete logs of the client console (including logs after removing unreads and refreshing the page), ensuring that all logs printed by wasm_exec.js are included.
The code is fine, but some conversations cannot be cleared.

**Comment by Bloomingg** [comment]
Complete logs of the client console must be collected in order to troubleshoot the issue

**Comment by skiffer-git** [comment]
Which version are you using? Please try it with the latest version.

**Comment by skiffer-git** [comment]
The new version has removed all scripts, so this issue will no longer exist.
