### ISSUE TITLE
[BUG] openImSdkWsPort service does not start normally,not initiated port is 10003问题建议在安装脚本或者文档说明一下

### ISSUE THREAD

**Issue by jsonMark** [OpenIMSDK/Open-IM-Server#277]
openImSdkWsPort service does not start normally,not initiated port is 10003

建议脚本检查一下docker和docker-compose相关版本，首次安装就不成功，有点打击用户信心！

**Comment by Toursslivers** [comment]
macos 不行，用linux

**Comment by burndust** [comment]
Ubuntu版本同样有这个报错

**Comment by YiuTerran** [comment]
Ubuntu一样报错+1，按文档来都跑不通，尴尬

**Comment by Jaydar** [comment]
+1

**Comment by cisen** [comment]
centos 7 +1

**Comment by yktimes** [comment]
同样失败。

**Comment by niklaus111** [comment]
有解决办法么，
![image](https://user-images.githubusercontent.com/34758351/237023960-94b7973e-d109-4f02-a4c8-ffba9a828f8a.png)
