### ISSUE TITLE
[BUG] <title> 新建群聊后，群成员聊天信息相互正常，但是mysql conversions表项中无法查找到此群的会话？？

### ISSUE THREAD

**Issue by 4815180** [OpenIMSDK/Open-IM-Server#278]
### Environment:  

centos 7
### Physical Memory Capacity:

8G
### Code Version:

2.2.0
### screenshot:

![image](https://user-images.githubusercontent.com/80960957/186884698-3bb888ae-3bbf-497e-aa80-12c644b05deb.png)
![image](https://user-images.githubusercontent.com/80960957/186884424-3bdd5f0d-be2b-40c3-a0ff-309af43b3e8e.png)
![image](https://user-images.githubusercontent.com/80960957/186884455-b541964e-8195-44dd-8186-9b91dec75a80.png)

**Comment by jaonzyx** [comment]
目前是这样的，创建会话，这个表不会产生一条数据，当更新会话的某些设置的时候，就会插入一条记录，比如把会话置顶

**Comment by 4815180** [comment]
我已经通过修改app代码，让用户在进入群的时候，去修改群的设置，如调整接收消息为0， 这样会在会话表里去生成数据，野路子，献丑了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenIMSDK/Open-IM-Server"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月1日(星期四) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenIMSDK/Open-IM-Server] [BUG] <title&gt; 新建群聊后，群成员聊天信息相互正常，但是mysql conversions表项中无法查找到此群的会话？？ (Issue #278)





 
目前是这样的，创建会话，这个表不会产生一条数据，当更新会话的某些设置的时候，就会插入一条记录，比如把会话置顶

**Comment by skiffer-git** [comment]
The conversation is generated on the client sdk
