### ISSUE TITLE
[BUG] Use user token can not access /friend/search, but can access /get friend list. what is the matter?

### ISSUE THREAD

**Issue by timothyzhao0507** [openimsdk/open-im-server#2780]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

As Title

### Screenshots Link

![openim_getusertoken](https://github.com/user-attachments/assets/641d726e-92b4-4340-8509-874156ae2f62)
![openim_searchfriend](https://github.com/user-attachments/assets/ca30669e-af46-4019-b4f3-7d5803e470f3)

**Comment by icey-yu** [comment]
/friend/search is an API endpoint for the chat project, please use the chat token.
