### ISSUE TITLE
[Other]: The slack link has expired

### ISSUE THREAD

**Issue by lizzy-0323** [openimsdk/open-im-server#2787]
### What would you like to share?

First I want to say thanks for making such good software! 
And I hope the slack link will be updated, so that we can have communication with developers on slack.

**Comment by skiffer-git** [comment]
https://join.slack.com/t/openimsdk/shared_invite/zt-2ijy1ys1f-O0aEDCr7ExRZ7mwsHAVg9A

**Comment by lizzy-0323** [comment]
Thanks.
