### ISSUE TITLE
服务端部署时启动sdk_server失败

### ISSUE THREAD

**Issue by YangShizhao** [OpenIMSDK/Open-IM-Server#279]
If you are deploying OpenIM for the first time
sdk_server的启动脚本sdk_svr_start.sh中，包含了两条无法识别的参数，会导致服务端程序启动失败。分别是：
-openIM_ws_address
截图如下：
![image](https://user-images.githubusercontent.com/13344900/187331963-7bf745a6-faea-4bd5-acd5-b0ce84f9a32c.png)
和-openIM_api_address，
![image](https://user-images.githubusercontent.com/13344900/187332049-02edb57a-2da0-4bf2-8f93-eb18a005cbe9.png)

同时配置文件中的日志级别后面需加一个空格，否则读取日志级别时也会报错。
截图如下：
![image](https://user-images.githubusercontent.com/13344900/187331830-bd6aa6e9-a284-4dc2-aea2-4199b1b84b33.png)

**Comment by guipie** [comment]
无法识别 **openIM_ws_address**  解决了吗，也遇到了

**Comment by YangShizhao** [comment]
> 无法识别 **openIM_ws_address** 解决了吗，也遇到了

我直接把这两条参数删掉了，并不影响正常的启动

**Comment by goldencolor** [comment]
我也遇到了解决了吗?

**Comment by muyi137** [comment]
我也遇到了   怎么解决啊！！！

**Comment by YangShizhao** [comment]
> sdk_svr_start.sh

修改sdk_svr_start.sh文件，把里面的启动指令里的这个参数删掉

**Comment by YangShizhao** [comment]
> > > sdk_svr_start.sh
> > 
> > 
> > 修改sdk_svr_start.sh文件，把里面的启动指令里的这个参数删掉
> 
> 删除后服务全部启动得情况下 登录账号 wss 10003 报错 怎么回事啊 ![image](https://user-images.githubusercontent.com/2306500/195306453-84facab1-5962-40d0-b046-fdde63acaace.png)

那就不知道了，看代码吧

**Comment by juteman** [comment]
该问题我找到了解决办法

原因是子模组 cmd/Open-IM-SDK-Core 没有跟上项目更新导致的

可以手动切换子模组到v2.3.3版本，我这里提示go.mod还少两个依赖，装上去正常运行。

ps: 该项目在git提交和子模组管理上做的非常的烂

**Comment by YangShizhao** [comment]
> 该问题我找到了解决办法
> 
> 原因是子模组 cmd/Open-IM-SDK-Core 没有跟上项目更新导致的
> 
> 可以手动切换子模组到v2.3.3版本，我这里提示go.mod还少两个依赖，装上去正常运行。
> 
> ps: 该项目在git提交和子模组管理上做的非常的烂

如果是版本对不上的话，自己是怎么跑通的，他们自己不会用这个代码吗(╯︵╰)

**Comment by skiffer-git** [comment]
https://doc.rentsoft.cn/#/v2/server_deploy/easy_deploy_new
