### ISSUE TITLE
[BUG] When I quote-reply to my own message, why is the contentType of the quoted message of type revokeMessage (2101)?

### ISSUE THREAD

**Issue by OrrinHatch** [openimsdk/open-im-server#2791]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

<img width="593" alt="截屏2024-10-25 12 04 38" src="https://github.com/user-attachments/assets/772f679d-70b2-4426-82b9-e2444a509589">

**Comment by skiffer-git** [comment]
We'll be testing it soon. Thanks for bringing this up.

**Comment by withchao** [comment]
Is this question mandatory? Under what circumstances does it occur? Can you provide a log?
