### ISSUE TITLE
[BUG] openim/openim-web-front ，Failed to retrieve data after HTTPS login

### ISSUE THREAD

**Issue by Evangelove** [openimsdk/open-im-server#2795]
### OpenIM Server Version

release-v3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

The project deployed with Docker fails to retrieve data after HTTPS encrypted login via Nginx. I configured a custom HTTPS port 1443 with Nginx. Using the latest image, I can log in to the platform on port 11001 with the domain plus the custom port, send emojis, and upload files. The server has recorded these files, but when retrieving this data, it fails due to the missing custom port.
![image](https://github.com/user-attachments/assets/ac4af2b9-7455-4176-ba63-8233f28a1264)
![image](https://github.com/user-attachments/assets/d82e685d-7955-4ea3-b1e4-82f131ffa2e9)
Please take a look, thank you.

**Comment by withchao** [comment]
The image address is your api address, and it will redirect to the real address when it is queried. You need to configure the correct externalAddress in the configuration file minio.yml as your minio address.
