### ISSUE TITLE
[BUG] nginx(minio) config confirm or error?

### ISSUE THREAD

**Issue by anyex-net** [openimsdk/open-im-server#2799]
### OpenIM Server Version

3.7.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

<img width="794" alt="图片" src="https://github.com/user-attachments/assets/2810e65f-3e20-4704-a93c-06744ecaf634">

我们现在nginx端配置 没有参考文档那样 用同一个域名的模式

我们采用api是独立一个二级域名 ws也用到独立的二级域名  
目前碰到走imapi这个nginx请求的时候    这里必须要这样  proxy_pass http://121.41.XX.XX:10002/;      
这样 proxy_pass imapi; 就会导致minio的存储请求应答回来的地址不对  请问这里有啥说法嘛 谢谢

<img width="569" alt="图片" src="https://github.com/user-attachments/assets/29f0e878-6b7b-4818-afc7-caf6c8ad2e0f">
<img width="598" alt="图片" src="https://github.com/user-attachments/assets/eb0659a1-cebd-4a25-8b20-de7719342e4d">

**Comment by skiffer-git** [comment]
Does version 3.8 have a similar issue?
