### ISSUE TITLE
unit test is broken when run by vscode

### ISSUE THREAD

**Issue by Yaxian** [OpenIMSDK/Open-IM-Server#28]
https://github.com/OpenIMSDK/Open-IM-Server/blob/7c3aa7ee0b6321e7888d484ec87947dde671378e/src/common/config/config.go#L157

https://github.com/OpenIMSDK/Open-IM-Server/blob/7c3aa7ee0b6321e7888d484ec87947dde671378e/src/common/config/config.go#L158

```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^Test_UserRegister$ Open_IM/src/api/auth

panic: open $ROOT/Open-IM-Server/src/api/auth/config/config.yaml: no such file or directory

goroutine 1 [running]:
Open_IM/src/common/config.init.0()
	$ROOT/Open-IM-Server/src/common/config/config.go:156 +0x89
FAIL	Open_IM/src/api/auth	0.014s
FAIL
```

**Comment by wu-xian** [comment]
一个简单的解决办法就是把config文件夹拷贝到单元测试同级目录。

能提个建议吗，init函数不要对文件和网络依赖。

**Comment by Leon2012** [comment]
改代码吧，我的做法是加个环境变量来配置config文件，这样只要环境变量配置就可以测试
