### ISSUE TITLE
[FEATURE REQUEST] IMSDK.deleteConversationAndDeleteAllMsg Whether the real physical deletion can be realized

### ISSUE THREAD

**Issue by liserc** [openimsdk/open-im-server#2803]
### Why this feature?

IMSDK.deleteConversationAndDeleteAllMsg Whether the real physical deletion can be realized？

### Suggested Solution

I see that the SDK still calls clearConversationAndDeleteAllMsg for processing, there are too many sessions for customer service scenarios, and the session synchronization after each login is too time-consuming, and the system is also very difficult to use, although the new version now supports the incremental session synchronization mechanism, the messages in the session have been deleted but the session itself still exists, which is an additional storage and synchronization cost for the system.

### Additional Information

![image](https://github.com/user-attachments/assets/85d567b6-e516-425e-a167-184d010ce5d4)

**Comment by withchao** [comment]
This method does not physically delete the data, and can be considered a soft delete. The client will not be synchronized after the deletion.
