### ISSUE TITLE
The app cannot be connected, it seems that the IP is restricted

### ISSUE THREAD

**Issue by fuoko0** [openimsdk/open-im-server#2814]
### What would you like to share?

For the app chat, there are multiple IPs on the same server. Yesterday, it couldn't connect, but switching to a different IP worked fine. This morning, it didn't work again, and changing to another IP resolved the issue. What could be the reason for this?

**Comment by skiffer-git** [comment]
It's recommended to use a domain name and ports 80 and 443.
