### ISSUE TITLE
[BUG] The online status of the user in the management system is undefined

### ISSUE THREAD

**Issue by yang961226** [openimsdk/open-im-server#2832]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

The online status of all users is undefined
![8531730717799_ pic](https://github.com/user-attachments/assets/8c556062-2627-4718-affa-642b8d76ff3b)

**Comment by lgz5689** [comment]
This issue is a known one and will be fixed in the next update.
