### ISSUE TITLE
[Other]: <The server changes IP, some pictures seem to be saved with complete URLs>

### ISSUE THREAD

**Issue by zxcdydy** [openimsdk/open-im-server#2843]
### What would you like to share?

服务器换IP，某些图片存的好像是完整的url，能否把存储的url都统一成根据前端配置或者实际访问的（IP或域名）+图片的相对路由

### Additional information

希望能回复

**Comment by skiffer-git** [comment]
There are two solutions:
1. Use S3 cloud storage.
2. Use Nginx.
