### ISSUE TITLE
[BUG] endpoint /user/update_user_info_ex failed

### ISSUE THREAD

**Issue by supertobby** [openimsdk/open-im-server#2845]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

When I call the interface /user/update_user_info_ex, it triggers a panic in the backend service. The parameters and logs are as follows:
<img width="325" alt="image" src="https://github.com/user-attachments/assets/fbbed858-3200-49a0-a2bc-0067ed9ebbed">
<img width="1457" alt="image" src="https://github.com/user-attachments/assets/8a758b47-32e8-4d15-9886-7b132829f0ec">

**Comment by icey-yu** [comment]
正确的参数格式应为：
{
    "userInfo": {
        "userID": "CHARACTER_27084546379173888",
        "nickname": "Michelle",
        "faceURL": "/rolesCHARACTER_27084546379173888/avatar/2024102210465678399062067.webp"
    }
}
