### ISSUE TITLE
[Deployment] Redis cluster startup error

### ISSUE THREAD

**Issue by aningco** [openimsdk/open-im-server#2847]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (ARM)

### Deployment Method

Docker Deployment

### Issue Description and Steps to Reproduce

1. I have already set up a Redis cluster under docker environment in the servers 10.180.55.53, 10.180.55.54, 10.180.55.55 ,all these servers are in internal network. The Redis cluster mode is three master and three slave.

2. Related config file, config/redis.yml as below 

<img width="657" alt="截图" src="https://github.com/user-attachments/assets/12c830b7-e7b9-44bc-91b8-81c7445bab16">
 
3.The following errors occurred during the startup process

![截图4](https://github.com/user-attachments/assets/32742edc-c270-4088-be16-50c7b15cb214)

if anything wrong ,please give some advices,thanks!

**Comment by icey-yu** [comment]
Please try connecting to Redis using another method to confirm whether Redis has started correctly.
