### ISSUE TITLE
[Deployment]  open-im-server contaier restart takes lots of time

### ISSUE THREAD

**Issue by aningco** [openimsdk/open-im-server#2848]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (ARM)

### Deployment Method

Docker Deployment

### Issue Description and Steps to Reproduce

When the open-im-server container restarts, it always needs to be recompiled , and compilation takes more than ten minutes,Is there any way to prevent recompilation or shorten the time?

**Comment by skiffer-git** [comment]
Restarting the container won’t trigger a build.
