### ISSUE TITLE
建议将组件部署文档补充完整

### ISSUE THREAD

**Issue by wzhsh90** [OpenIMSDK/Open-IM-Server#285]
1、目前组件部署里面只有minio docker 方式，其他组件部署没有？

2、部署的mysql 只能用5.7 版本 还可以自己用更高

3、mongo 现在docker 里面的版本是4.0 是否可以部署更高

服务器上已经有部分组件了，只需要手动增加其他组件。

**Comment by shoyu666** [comment]
[docker image build windows script & helm support](https://github.com/OpenIMSDK/Open-IM-Server/pull/291/files#diff-ba66b531f5db27e2cb364be1b4cda073681f7447f088ac98139ca96c1609dc16)

**Comment by skiffer-git** [comment]
https://doc.rentsoft.cn/#/v2/server_deploy/code_singe_cluster
