### ISSUE TITLE
[BUG] WebSocket connection fail

### ISSUE THREAD

**Issue by alicesunhy** [openimsdk/open-im-server#2852]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

1.按照文档源码部署. 部署基础服务 和 open-im-server 
2.chat没有部署
操作流程
 1.通过 [Server APIs](https://docs.openim.io/zh-Hans/restapi/introduction)] api 导入用户 获取用户token 
 2.通过 [https://docs.openim.io/zh-Hans/sdks/api/initialization] 浏览器的方式链接
 3.使用通过 [Server APIs](https://docs.openim.io/zh-Hans/restapi/introduction)] api导入的用户  WebSocket 无法登录
 
web 日志
![WX20241113-115130](https://github.com/user-attachments/assets/fc068ef6-cf96-4de6-b0e8-a9b773d999af)
im-server 日志
![WX20241113-115359](https://github.com/user-attachments/assets/d2409932-42ae-43cd-96a1-aa74b08e12ee)

**Comment by skiffer-git** [comment]
![image](https://github.com/user-attachments/assets/efb84404-77d9-454d-9bfa-4b4041c4da5b)

**Comment by skiffer-git** [comment]
It's recommended to first understand the relationships between the different roles in this diagram.
