### ISSUE TITLE
[Deployment]

### ISSUE THREAD

**Issue by Houzi202488** [openimsdk/open-im-server#2853]
### OpenIM Server Version

3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Issue Description and Steps to Reproduce

我使用是AWS的EKS部署的，启动api的服务的时候报错

### Screenshots Link

![1](https://github.com/user-attachments/assets/be105f15-1dde-4568-8ddb-8bb2ba4810ea)

**Comment by Houzi202488** [comment]
helm部署的redis；使用的chart:8.4.3；app:7.0.10

**Comment by skiffer-git** [comment]
mage ;
mage start

**Comment by Houzi202488** [comment]
> 法师； 法师开始

什么意思

**Comment by Houzi202488** [comment]
使用的ZK版本是chart:13.6.0；app:3.93

**Comment by skiffer-git** [comment]
Replace Zookeeper with etcd
