### ISSUE TITLE
[DOC]: Some suggestions about webhooks documentation

### ISSUE THREAD

**Issue by ylx19931228** [openimsdk/open-im-server#2859]
在webhooks的文档中，有以下问题。实际开发中有很多疑惑。
1.  有关参数部分。没有明确标注参数类型，参数范围。
2.  返回值的部分，应答包示例中。以下对象没有对象明细。
         修改消息内容的回调、离线状态下消息推送前的回调、在线状态下消息推送前的回调
         offlinePushInfo | *OfflinePushInfo | 修改后的离线推送信息。

3. 建议在webhooks的配置文件中，说明对应。每个类型对应的功能是什么。
![微信图片_20241118124735](https://github.com/user-attachments/assets/72e78145-cc3e-45bf-bb9b-3584410b227e)

**Comment by FGadvancer** [comment]
https://docs.openim.io/restapi/webhooks/example

**Comment by skiffer-git** [comment]
https://docs.openim.io/restapi/webhooks/group/applyJoinGroupBefore

**Comment by ylx19931228** [comment]
![1](https://github.com/user-attachments/assets/4840fe4d-a35b-444a-b641-1a0e4ff0d2db)
![2](https://github.com/user-attachments/assets/65df199c-00ad-4e58-b293-827cf093aaba)

这个字段中,标识的对象中具体属性对应是什么
