### ISSUE TITLE
[BUG] k8s部署后，登陆失败

### ISSUE THREAD

**Issue by imabaymax** [OpenIMSDK/Open-IM-Server#286]
k8s部署后，使用Open-IM-PC-Web-Demo测试链接，在注册完成后，无法登陆，提示
{"errCode":10005,"errMsg":"Post \"http://:10002/auth/user_token\": dial tcp :10002: connect: connection refused"}
config.yaml版本: 2.3.1

**Comment by shoyu666** [comment]
修改：internal/demo/register/login.go
```
        //url := fmt.Sprintf("http://%s:%d/auth/user_token", utils.ServerIP, config.Config.Api.GinPort[0])
        url := fmt.Sprintf("http://%s:%d/auth/user_token", {你的服务ip}, config.Config.Api.GinPort[0])
```

**Comment by wangchuxiao-dev** [comment]
已修复

**Comment by wangchuxiao-dev** [comment]
统一走demo的imAPIURL配置
