### ISSUE TITLE
[Other]: The OpenIM server logs are refreshing too quickly

### ISSUE THREAD

**Issue by getpro** [openimsdk/open-im-server#2886]
### 日志如下

`2024-11-25 06:20:21.420	WARN	[PID:7]        	openim-push              	[3.8.1]                       	[kafka/consumer_group.go:61]                      	consume err                                       	{"topic": [""], "groupID": "", "error": "kafka server: The request attempted to perform an operation on an invalid topic"}
`

这个日志刷新过快，导致其他日志无法查看

open-server 版本：3.8.2

_No response_

**Comment by skiffer-git** [comment]
Why is the topic empty?

**Comment by getpro** [comment]
> Why is the topic empty?

openim-server 从3.7更新到3.8.2 出现的，只更新了openim-server 其他的没有更新

**Comment by getpro** [comment]
找到问题了，升级openim-server 没有更新scripts/create-topic.sh  脚本，里面增加了一个topic的初始化

**Comment by skiffer-git** [comment]
scripts/create-topic.sh
The new version has removed the script. Are you sure you are on the 3.8.2 branch?

**Comment by getpro** [comment]
加上了toOfflinePush topic还是会输出这个日志，openim-server确定是3.8.2的
`2024-11-25 07:25:51.808	WARN	[PID:7]        	openim-push              	[3.8.2]                       	[kafka/consumer_group.go:61]                      	consume err                                       	{"topic": [""], "groupID": "", "error": "kafka server: The request attempted to perform an operation on an invalid topic"}`

**Comment by mo3et** [comment]
The leatest version is remove this script. You can try to restart docker compose.

**Comment by getpro** [comment]
kafka.yml配置文件没更新到最新版本导致的。。
