### ISSUE TITLE
[BUG] no need to specify port and ports in config for RPC services

### ISSUE THREAD

**Issue by morya** [openimsdk/open-im-server#2895]
### OpenIM Server Version

v3.8.0

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

rpc services are started and auto registered into registry ( zookeeper, etcd, k8s etc...),
listen IP and listen port are not that significant enough to be set in config file, it could be auto allocated random by system.

**Comment by morya** [comment]
可能，有点代码坏味道，实现的略微粗糙点

**Comment by morya** [comment]
> there are bug existing, msggateway will fail to start,

ok, it's caused by config file error. no need to fix.

**Comment by icey-yu** [comment]
Thank you for your PR. I believe this solution is quite valuable, but there is still a small issue that needs to be addressed: there is a risk of port conflicts between the various components and the exposed Prometheus scraping ports, as they are started asynchronously. We are currently considering a solution to resolve this issue.
