### ISSUE TITLE
[BUG] open-server api interface request error

### ISSUE THREAD

**Issue by getpro** [openimsdk/open-im-server#2898]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Docker Deployment

### Bug Description and Steps to Reproduce

任意接口请求返回以下错误：
`{
    "errCode": 14,
    "errMsg": "last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 172.19.0.6:10160: connect: connection refused\"; last resolver error: produced zero addresses",
    "errDlt": "14 last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 172.19.0.6:10160: connect: connection refused\"; last resolver error: produced zero addresses"
}`

重启open-server服务后可恢复

**Comment by skiffer-git** [comment]
Is it using etcd?

**Comment by getpro** [comment]
> Is it using etcd?

yes

**Comment by skiffer-git** [comment]
Run docker exec -it openim-server mage check when an issue occurs.
