### ISSUE TITLE
用消息队列来处理发送消息不大好吧？

### ISSUE THREAD

**Issue by williamtse** [OpenIMSDK/Open-IM-Server#290]
对于及时通讯软件是不是不适用，肯定会有延迟的，吧？

**Comment by shoyu666** [comment]
> 1:延迟看你的接受程度。 几毫秒和几百毫秒的延迟可能感受不是特别明显，除非你的用户量很大。
> 2:不同用户量级面临的挑战是不一样的，架构也会随之变化。
> 3:用消息队列是一种基于当前架构的技术选择。不能单纯的认为用消息队列就会高延迟，可以看下kafka的性能指标,压测情况。openim本身的压测情况。ps:客户端网络本身面临的挑战也很大。
> 4:不使用消息队列,必然也会面临没有消息队列的问题。比如客户端网络不好情况下的暂存，mq天然带的消峰。
> 5:万人大群官方也说了，有拉的模式。解决大群的延迟。

综上：
技术选型是一对结合实际情况做的取舍,只有适不适合。抛开用户量，集群规模，架构，优化等因素，只说消息队列不适用于通信软件是比较片面的。

**Comment by williamtse** [comment]
为什么不直接用websocket点对点发送消息？发送失败的话，再进入消息队列做持久化会不会更好？

**Comment by shoyu666** [comment]
yy几句
-    可能考虑到android手机进程不一定在，涉及到保活问题。push可能是大部分情况，push推送的话到达率高一些，特别是手机厂商自己的推送通道。除非是微信这样的体量，可能会跟手机厂商合作，提高自己的到达率。
-    另外单机保持多少websocket链接？集群化必然会涉及A用户在 机器1，B用户在机器2，A给B发消息会跨机器，等一系列问题。
-    这是一个典型的生产消费者场景,先发mq,可以被多种业务逻辑消费。(push,持久,离线)。消费端可以横向扩展，用mq解耦相对简单些。
-    所以关于 “为什么不直接用websocket点对点发送消息” ，跟你问的“ 对于及时通讯软件是不是不适用 ”的问题 有些类似，没有不是A就是B的,都是一种选择.....
-   比如[livekit](https://github.com/livekit/livekit)消息就是websocket发送的，用redis做集群发现，rpc跨机器。但人家的场景是视频聊天室,大部分是在线的情况。。。  **ps**: openim的视频聊天也是基于liveKit的。 [openim 视频聊天实现分析](https://github.com/shoyu666/Open-IM-Server-Call)

**Comment by shoyu666** [comment]
本质就是消息触达的问题，在移动端，特别是android端，有比厂商自带的通道更靠谱的通道么？
h5页面只要打开，链接一般是建立的。收不到一般是没打开页面，你见过浏览器页面都没打开的，就能推送给你信息的应用么？

**Comment by shoyu666** [comment]
刚撸了下代码，离线是push,在线是websocket转发的。
见：internal/push/logic/push_to_client.go  MsgToUser

**Comment by williamtse** [comment]
h5聊天的两个人，连接的是不同的服务器A和B呢？

> 刚撸了下代码，离线是push,在线是websocket转发的。 见：internal/push/logic/push_to_client.go MsgToUser h5打开一般 websocket链接会保持。push推送更多的指客户端

**Comment by hollykunge** [comment]
> h5聊天的两个人，连接的是不同的服务器A和B呢？
> 
> > 刚撸了下代码，离线是push,在线是websocket转发的。 见：internal/push/logic/push_to_client.go MsgToUser h5打开一般 websocket链接会保持。push推送更多的指客户端

你是在转圈圈吗？菜鸡就别问了 看看hello world

**Comment by shoyu666** [comment]
哈哈哈... 好尴尬
离线消息走的推送，在线消息是websocket转发,如果A和B不在一台服务器,就是rpc 服务器之间转发。
消息推送(离线)  和  跨机器转发(在线)，2种场景。

“集群化必然会涉及A用户在 机器1，B用户在机器2，A给B发消息会跨机器“除了推送，有没有其他解决方案？
2种场景，没有说推送是解决跨机器的方案。

**Comment by skiffer-git** [comment]
Distinguish between real-time communication and instant communication
