### ISSUE TITLE
[BUG] 404 page not found

### ISSUE THREAD

**Issue by KylinSpace** [openimsdk/open-im-server#2900]
### OpenIM Server Version

e.g 3.

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

![image](https://github.com/user-attachments/assets/255147a7-c14f-41b7-94d9-afe85334d472)
![image](https://github.com/user-attachments/assets/140b92c3-cba4-4609-9aaf-66da3d190e3a)

 你好
App Server (Chat) 通过源码部署
 10008 chat 服务的接口报错 \"404 page not found\", *network.ApiResponse) failed invalid character 'p' after top-level value: 10006 Internal SDK error"}

服务器端口确认都已经打开。
客户端是flutter_openim_sdk  3.8.0 以及 3.8.2 都试过了。

OpenIM.iMManager.login 正常可以联接上服务器，但是10008的接口都无法访问。

**Comment by skiffer-git** [comment]
What is the specific network request?

**Comment by KylinSpace** [comment]
> What is the specific network request?

http://xxx.xxx.xx:10008/user/get_users_info

Specifically, 404 appears in all 10008 requests.
After I successfully logged in with OpenIM.iMManager.login,
-------------------------------------------------------------------
 all requests via OpenIM.iMManager.userManager or  OpenIM.iMManager.friendshipManager appeared
"url": "http://xx.xxx.231.157:10008/friend/get_black_list", "status": "404 Not Found", "body": "404 page not found"}
I/GoLog (17467): 2024-11-28 07:55:42.652 ERROR [PID:17467] [v3.8.2] [flutter/Android] [network/http_client.go:136] ApiResponse {"operationID": "1732780532484 ", "type": "api code parse", "error": "invalid character 'p' after top-level value"}
or
----------------------------------------------------------------------------------------------------------
"url": "http://xxx.xxx.xxx.157:10008/group/get_recv_group_applicationList", "status": "404 Not Found", "body": "404 page not found"}

Or
-----------------------------------------------------------------------------------------------------------
"1732780532484", "duration": "67ms", "api": "/group/get_recv_group_applicationList", "state": "failed", "error": "api /group/get_recv_group_applicationList json.Unmarshal(\"404 page not found\", *network.ApiResponse) failed invalid character 'p' after top-level value: 10006 Internal SDK error"}

---------------------------------------------------------------------------
I confirmed that the big service is running, 10008, and the port 10008 is open for access.

**Comment by skiffer-git** [comment]
post

**Comment by skiffer-git** [comment]
You should use the Flutter SDK from https://github.com/openimsdk/open-im-sdk-flutter.

**Comment by skiffer-git** [comment]
https://github.com/openimsdk/open-im-flutter-demo

**Comment by KylinSpace** [comment]
thanks    is my mistake
