### ISSUE TITLE
[BUG] webhook User Online Status Callback didn't work

### ISSUE THREAD

**Issue by eswulei** [openimsdk/open-im-server#2912]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

webhook: Callback After Sending Single Chat Message worked well, but User Online Status Callback didn't work. Maybe the same bug in User Offline Status Callback

**Comment by skiffer-git** [comment]
You can try version 3.8.2.
