### ISSUE TITLE
有没有大佬,指点下windows server下如何部署服务端?

### ISSUE THREAD

**Issue by bondliu2020** [OpenIMSDK/Open-IM-Server#292]
有没有大佬,指点下windows server下如何部署服务端?

**Comment by shoyu666** [comment]
> 有没有大佬,指点下windows server下如何部署服务端?

使用下面脚本
https://github.com/OpenIMSDK/Open-IM-Server/pull/291/commits/25fdba243432b09b8d60256edd0ef15b0142e886
