### ISSUE TITLE
The number of read and unread messages in the group chat is 0, and it is not possible to view which members have read and which members have not read

### ISSUE THREAD

**Issue by xiaobeiy** [openimsdk/open-im-server#2931]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

openim-server 3.8.2版本，flutter客户端sdk 3.8.2+1版本。
发送群聊消息成功后，已读人数和未读人数均为0，无法显示哪些群聊成员已读哪些未读。客户端具体体现为：Message中附加信息attachedInfoElem的值为{groupHasReadInfo: {hasReadCount: 0, unreadCount: 0}

**Comment by skiffer-git** [comment]
These are advanced features, available only in the commercial version.
