### ISSUE TITLE
[BUG] About the timeout of uploading images using minio

### ISSUE THREAD

**Issue by ylx19931228** [openimsdk/open-im-server#2932]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

使用minio上传图片失败, docker minio 配置如图
![微信截图_20241206120740](https://github.com/user-attachments/assets/26f89d14-02e2-42a4-b69e-5e847ad5b858)
config/minio.yaml配置如图
![微信截图_20241206120710](https://github.com/user-attachments/assets/e3621d1a-7238-4bc3-bdda-16364737f702)
上传后的结果如图.
![微信图片_20241206120835](https://github.com/user-attachments/assets/d459dce9-6cf7-4c5c-923e-f79c5b57471a)

**Comment by skiffer-git** [comment]
https://docs.openim.io/guides/gettingstarted/dockercompose
# Set the external access address for MinIO service (external IP or domain)
MINIO_EXTERNAL_ADDRESS="http://external_ip:10005"

**Comment by skiffer-git** [comment]
To confirm if MinIO is running correctly, it's recommended not to modify MinIO.

**Comment by ylx19931228** [comment]
minio已确认是正常运行, 目前就是上传不了

**Comment by skiffer-git** [comment]
It's recommended not to modify MinIO.

**Comment by ylx19931228** [comment]
那我目前要如何解决这个问题

**Comment by skiffer-git** [comment]
It is recommended to follow the documentation for deployment, open the relevant ports, and test if everything works correctly by accessing it via IP:11001.

**Comment by ylx19931228** [comment]
thank you.
