### ISSUE TITLE
[BUG] About the rest api user application group interface

### ISSUE THREAD

**Issue by ylx19931228** [openimsdk/open-im-server#2936]
### OpenIM Server Version

3.8.1

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

填写如下参数。ex参数没有作用。
{
 "groupID": "23",
 "reqMessage": "req msg join group",
 "joinSource": 1,
 "inviterUserID": "490",
 "ex": "{\"user\":{\"activeTime\":\"2024-12-04 13:26:10\",\"areaCode\":\"string\",\"avatar\":\"string\",\"birthday\":\"2024-11-14 09:32:48\",\"city\":\"string\",\"cityCode\":\"430200\",\"countryCode\":\"0\",\"createDate\":\"2024-04-29 11:48:40\",\"gender\":0,\"gold\":5751.00,\"id\":469,\"integral\":0,\"intro\":\"string\",\"label\":\"string\",\"lineStatus\":0,\"nickname\":\"strin11g\",\"provinceCode\":\"430000\",\"updateBy\":\"string\",\"updateDate\":\"2024-11-20 18:19:37\",\"userAccountId\":490,\"userRoleId\":1,\"vipExpireData\":\"2024-12-29 18:23:39\",\"vipStatus\":2,\"whiteList\":0}}"
}

从rest api中的获取群组中的用户接口中。没有对该用户的ex参数其作用。

{
	"errCode": 0,
	"errMsg": "",
	"errDlt": "",
	"data": {
		"total": 2,
		"members": [
			{
				"groupID": "22",
				"userID": "1",
				"roleLevel": 100,
				"joinTime": 1731898068910,
				"nickname": "momoyu",
				"faceURL": "",
				"appMangerLevel": 0,
				"joinSource": 2,
				"operatorUserID": "imAdmin",
				"ex": "",
				"muteEndTime": 0,
				"inviterUserID": "imAdmin"
			},
			{
				"groupID": "22",
				"userID": "490",
				"roleLevel": 20,
				"joinTime": 1733535894105,
				"nickname": "金手指",
				"faceURL": "https://copyright.bdstatic.com/vcg/creative/cc9c744cf9f7c864889c563cbdeddce6.jpg@h_1280?e=1728981458&token=UEoD4ICHNwjc4GjoV5q0DLUrw2ppqDpXc6MBLf_S:jysGcn5AnkeDur33f0iY0FCixcI=",
				"appMangerLevel": 0,
				"joinSource": 0,
				"operatorUserID": "imAdmin",
				"ex": "",
				"muteEndTime": 0,
				"inviterUserID": "490"
			}
		]
	}
}

**Comment by skiffer-git** [comment]
The "ex" field for group join requests and the "ex" field for group members are two different concepts.

**Comment by ylx19931228** [comment]
好的, 那使用rest api中的用户修改信息接口将ex字段修改, 是否能把群成员中的ex字段修改?

**Comment by skiffer-git** [comment]
https://docs.openim.io/restapi/apis/groupManagement/setGroupMemberInfo
