### ISSUE TITLE
[建议/想法]希望能开一个子项目.

### ISSUE THREAD

**Issue by smallevil** [OpenIMSDK/Open-IM-Server#296]
这个项目很好,特别是针对社交类,通讯类.基本上这也算是现在大部分app的"标配"功能了.
只是针对一些工具类,或小项目时,还是有点"体积过大".
我是一个独立开发者,会开发一些工具类或非社交类的app.但这些app也会有"实时通知"功能.不是ios那种远程push,就是在线用户的实时通讯.
比如:
我开发一个app,刚上线时是不会加IM这种通讯的,但会有一些"实时通知"的需要,像实时封禁,某一延时(异步)的实时提示,或实时下发一些配置等等.这些不需要用户与用户之间通讯,更多的是服务端对现在"正在线"的用户发送一些"自定议消息".
其实需要的功能很简单,用打开或注册后能加入至少一个"群(订阅)",当有需要时,服务器端可以对某一个用户或某一个"群(订单)"发送一个自定义消息就行了.在线的收到,不在线的不用发送,app端或服务端都不用保存数据,只是在线发送出去就行了.

这个需求在app开发上比IM使用要更广泛.现在也没有类似像样的开源产品,大部分好像都是自己用websocket实现.但对小团队或独立开发来说,websocket的开发或优化也是大麻烦.

这样的产品,不管是任何类型的app或web都有需求,如果以后还能再平滑迁移到openim更好,不能平滑迁移也无所谓.但如果只为了这个"实时通知"直接把openim加到项目里,又会特别"臃肿",维护成本也高不少.所以标题才说如果能有一个基于openim的子项目去实现更好一些.

以上只是我个人开发app过程中遇到的需求,算是给官方提供一种思路吧.

**Comment by jaonzyx** [comment]
workerman应该符合你的需求

**Comment by YiuTerran** [comment]
你这个需求自己搭一个mqtt broker就行…推荐用emqx

**Comment by skiffer-git** [comment]
webhook
