### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by oohusl** [openimsdk/open-im-server#2963]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

macOS (ARM)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

openim-rpc-auth进程、端口监听都正常。chat 1.8.3，mage start报错：

`OpenIM check failed: Post "http://127.0.0.1:10002/auth/get_admin_token": context deadline exceeded`

**Comment by skiffer-git** [comment]
Which configuration item did you modify?

**Comment by oohusl** [comment]
都重启后恢复正常
