### ISSUE TITLE
我应该使用哪个 API 来使某人静音或获得全球禁令?

### ISSUE THREAD

**Issue by ibrahimozdenkotic** [OpenIMSDK/Open-IM-Server#297]
https://doc.rentsoft.cn:8000/swagger/index.html#/, https://doc.rentsoft.cn/#/server_doc/admin?id=类型格式描述
在我发送的链接中的文档中，不需要 api 来使某人静音或全局禁止吗？如何让一个人静音？

**Comment by skiffer-git** [comment]
muted?

**Comment by skiffer-git** [comment]
Does it mean that you will not be prompted when receiving a message?
