### ISSUE TITLE
[DOC]: The multiLoginPolicy field in share.yml does not exist. The document description is wrong and needs to be corrected.

### ISSUE THREAD

**Issue by bitprince** [openimsdk/open-im-server#2970]
## 文档描述
![image](https://github.com/user-attachments/assets/b89f9d05-a97d-44ac-82e9-12e3815a400c)

## 实际情况
![17fa0d1882c47612ce0523897edff9b](https://github.com/user-attachments/assets/da16fc31-dfc3-4d63-a3e1-83efb8eedbcf)

**Comment by skiffer-git** [comment]
we have fixed it
