### ISSUE TITLE
[BUG] redis save error when KickTokens

### ISSUE THREAD

**Issue by 1978mountain** [openimsdk/open-im-server#2998]
### OpenIM Server Version

3.8.2

### Operating System and CPU Architecture

Linux (AMD)

### Deployment Method

Source Code Deployment

### Bug Description and Steps to Reproduce

func (c *tokenCache) BatchSetTokenMapByUidPid(ctx context.Context, tokens map[string]map[string]int) error 
提示
"error": "Error: redis: can't marshal map[string]int (implement encoding.BinaryMarshaler) 
需要转换为map[string]string

**Comment by icey-yu** [comment]
We have fixed it. Thank you for pointing out this issue.
