### ISSUE TITLE
http://121.37.25.71:8081/repository/maven2/  无法使用了 [BUG] <title>

### ISSUE THREAD

**Issue by dev-zl** [OpenIMSDK/Open-IM-Server#302]
http://121.37.25.71:8081/repository/maven2/  无法使用了

**Comment by hrxiang** [comment]
替换成：https://open-im-online.rentsof.cn:51000[/repository/maven2/  新仓库地址

**Comment by dev-zl** [comment]
https://open-im-online.rentsoft.cn:51000/repository/maven2/
