### ISSUE TITLE
[BUG] <title> api 用户登录接口不验证userID，直接返回Token。请问这样设计出于什么考虑？

### ISSUE THREAD

**Issue by T-Manson** [OpenIMSDK/Open-IM-Server#306]
### Code Version:

2.3.0

### screenshot:

文档地址：https://doc.rentsoft.cn:8000/swagger/index.html#/%E9%89%B4%E6%9D%83%E8%AE%A4%E8%AF%81/UserToken
源代码：
<img width="956" alt="image" src="https://user-images.githubusercontent.com/37177471/201069595-e850e894-ecf9-4279-bf10-16619f9c7e21.png">

**Comment by skiffer-git** [comment]
The UserToken api is only called for the server , not for the user
