### ISSUE TITLE
10001ice does not start normally,not initiated port is  please check ../logs/openIM.log   日志显示(openIM.log  )服务正常开启但是检查时发现检查的端口不正常

### ISSUE THREAD

**Issue by MmingY** [OpenIMSDK/Open-IM-Server#307]
docker-compose ps...........................
     Name                   Command               State                                       Ports                                    
---------------------------------------------------------------------------------------------------------------------------------------
etcd             /usr/local/bin/etcd --name ...   Up      0.0.0.0:2379->2379/tcp,:::2379->2379/tcp,                                    
                                                          0.0.0.0:2380->2380/tcp,:::2380->2380/tcp                                     
grafana          /run.sh                          Up                                                                                   
kafka            start-kafka.sh                   Up      0.0.0.0:9092->9092/tcp,:::9092->9092/tcp                                     
minio            /usr/bin/docker-entrypoint ...   Up      0.0.0.0:10005->9000/tcp,:::10005->9000/tcp,                                  
                                                          0.0.0.0:9090->9090/tcp,:::9090->9090/tcp                                     
mongo            docker-entrypoint.sh --wir ...   Up      0.0.0.0:37017->27017/tcp,:::37017->27017/tcp                                 
mysql            docker-entrypoint.sh mysqld      Up      0.0.0.0:13306->3306/tcp,:::13306->3306/tcp,                                  
                                                          0.0.0.0:23306->33060/tcp,:::23306->33060/tcp                                 
node-exporter    /bin/node_exporter               Up      0.0.0.0:9100->9100/tcp,:::9100->9100/tcp                                     
open_im_server   ./docker_start_all.sh            Up                                                                                   
prometheus       /bin/prometheus --web.list ...   Up                                                                                   
redis            docker-entrypoint.sh redis ...   Up      0.0.0.0:16379->6379/tcp,:::16379->6379/tcp                                   
zookeeper        /bin/sh -c /usr/sbin/sshd  ...   Up      0.0.0.0:2181->2181/tcp,:::2181->2181/tcp, 22/tcp, 2888/tcp, 3888/tcp         
check OpenIM, waiting 30s....................
check OpenIM................................
10001ice does not start normally,not initiated port is 
please check ../logs/openIM.log

**Comment by BaiMoHan** [comment]
这个脚本检查有问题，你自己启动后自己查看下端口就行，基本上启动脚本启动过程中没有报错就是启动成功了。不同的系统上自带的检测命令和端口检测机制也有些差异，按照脚本里面的命令在有些linux上是获取不到完整的端口情况的

**Comment by skiffer-git** [comment]
https://doc.rentsoft.cn/#/v2/server_deploy/easy_deploy_new
