### ISSUE TITLE
[BUG] MySQL对应表conversations，unread_count字段不会同步更新

### ISSUE THREAD

**Issue by T-Manson** [OpenIMSDK/Open-IM-Server#319]
### Code Version:

2.3.0

### screenshot:

源码位置：https://github.com/OpenIMSDK/Open-IM-Server/blob/9aaee04a692891644a0c8c8d342b674c8dffab6d/internal/rpc/conversation/conversaion.go#L78
DB数据：
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/37177471/208634532-4bcc06c9-f640-413f-974b-4a93cb0947ce.png">
仅同步了update_unread_count_time列

**Comment by skiffer-git** [comment]
MySQL is used for admin only
