### ISSUE TITLE
[BUG] 较大seq消息先入库并完成推送，可能导致丢消息

### ISSUE THREAD

**Issue by xiaofeige** [OpenIMSDK/Open-IM-Server#320]
阅读代码的过程中，有一个点没看明白，如果用户A同时收到1,2,3三条消息，然后按1,2,3分配了seq， 但是3先完成了入库mongo, 并走到push逻辑，客户端收到后更新了本地最大的seq。1，2消息是不是得不到推送了？

**Comment by skiffer-git** [comment]
The client willsynchronize the missing messages  actively

**Comment by piboye** [comment]
是怎么个等法?  主动获取缺失的消息?  等多久呢?
