### ISSUE TITLE
日志的路径（storageLocation）修改后不生效

### ISSUE THREAD

**Issue by yhuaqiang** [OpenIMSDK/Open-IM-Server#321]
1. 先用默认的配置文件部署了，然后docker-compose down ; rm components -rf
2. 修改配置如下：
![image](https://user-images.githubusercontent.com/5283803/209467951-38566427-ba07-4f78-b845-c8ecda1586ac.png)

![image](https://user-images.githubusercontent.com/5283803/209467935-df249c81-bbf9-4266-af45-df28b7dc748c.png)

3. 然后再次install，components的安装目录是在了data下，但是logs的还是在默认的位置
![image](https://user-images.githubusercontent.com/5283803/209467973-e4227ad3-fb82-48e1-8eb5-1f3ebb984670.png)
4.所有的服务都是能启动成功，就是日志的路径没有修改成功。
![image](https://user-images.githubusercontent.com/5283803/209467843-aa0adfb8-10f5-4ee7-93e7-cde172703f53.png)

**Comment by yhuaqiang** [comment]
而且，好像storageLocation字段不起作用，

**Comment by skiffer-git** [comment]
Please submit issues following the provided template, thank you.
/inivte
