### ISSUE TITLE
[BUG] <管理员发送群消息空值针异常>

### ISSUE THREAD

**Issue by xulirong919** [OpenIMSDK/Open-IM-Server#345]
按照接口文档：https://doc.rentsoft.cn/#/server_doc/admin?id=%e5%8f%91%e9%80%81%e5%8d%95%e8%81%8a%e7%be%a4%e8%81%8a%e6%b6%88%e6%81%af
参数：
{
  "operationID": "aaadd", 
  "sendID": "openIM123456", 
  "recvID": "", 
  "groupID": "666", 
  "senderNickname": "Gordon", 
  "senderFaceURL": "http://www.head.com", 
  "senderPlatformID": 5, 
  "forceList": [
 
  ], 
  "content": {
      "text": "nihao"
  }, 
  "contentType": 101, 
  "sessionType": 2, 
  "isOnlineOnly": true, 
  "offlinePushInfo": {
      "title": "send message", 
      "desc": "", 
      "ex": "", 
      "iOSPushSound": "default", 
      "iOSBadgeCount": true
  }
}
接口返回500 日志打印空值针

### Log File:

日志如下：
[Recovery] 2023/03/08 - 16:58:16 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:260 (0x44ecf5)
/usr/local/go/src/runtime/signal_unix.go:835 (0x44ecc5)
/Open-IM-Server/internal/api/manage/management_chat.go:241 (0x12fb1bb)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0xd785be)
/Open-IM-Server/pkg/utils/cors_middleware.go:22 (0xd785aa)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0xaeb8a1)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/recovery.go:101 (0xaeb88c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0xaea710)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616 (0xaea378)
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572 (0xae9ebc)
/usr/local/go/src/net/http/server.go:2947 (0x71ef0b)
/usr/local/go/src/net/http/server.go:1991 (0x71a126)
/usr/local/go/src/runtime/asm_amd64.s:1594 (0x469ae0)

**Comment by qbmiller** [comment]
看代码 应该是 RpcResp nil了。 也就是msg 模块返回的就有问题了。
可以基于 operationID 去 msg模块看看返回日志

**Comment by skiffer-git** [comment]
grep operationID  logs/* -a
