### ISSUE TITLE
[BUG] 当 etcd endpoint 无效，程序一直卡着不报错

### ISSUE THREAD

**Issue by edram** [OpenIMSDK/Open-IM-Server#347]
### Environment:
OS: Centos 7

### Physical Memory Capacity:
8G

### Code Version:
2.3.8

**Comment by edram** [comment]
类似这个 issue etcd-io/etcd#9877

**Comment by Fy-L** [comment]
> 类似这个 issue [etcd-io/etcd#9877](https://github.com/etcd-io/etcd/issues/9877)

这个issu里面就有解决方法

**Comment by skiffer-git** [comment]
In the new version, we will replace etcd with zookeeper
