### ISSUE TITLE
[BUG]  demo code GetRegister sql error?

### ISSUE THREAD

**Issue by DemoLiang** [OpenIMSDK/Open-IM-Server#349]
### Code Version:
branch main

### Component installation:
Open-IM-Server

### Log File:
source code:
这条SQL语句有问题吧？

### screenshot:

![image](https://user-images.githubusercontent.com/23476007/224001209-da4f2ac3-f3e5-4ff0-ab95-14720eec2a4c.png)

**Comment by qbmiller** [comment]
看起来是的

**Comment by skiffer-git** [comment]
Please refer to the errcode branch code
