### ISSUE TITLE
请问有前端demo测试下吗？

### ISSUE THREAD

**Issue by AnkoGo123** [OpenIMSDK/Open-IM-Server#36]
请问有前端demo测试下吗？

**Comment by skiffer-git** [comment]
Released on November 19

**Comment by AnkoGo123** [comment]
有demo了？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月5日(周五) 晚上7:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OpenIMSDK/Open-IM-Server] 请问有前端demo测试下吗？ (Issue #36)




 
Released on November 19
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
