### ISSUE TITLE
🔥 Are you using OpenIM?

### ISSUE THREAD

**Issue by cubxxw** [openimsdk/open-im-server#379]
### 🙋‍♂️ Are you using OpenIM?
If you are using OpenIM, welcome to share your use case with our community and win some OpenIM swags (T-shirt, mug, badge, etc.)!

https://github.com/OpenIMSDK/Open-IM-Server/assets/86140903/64f07258-220a-4000-a74a-700b3201be4e

### ✨ Why ?
Open source Instant Messaging Server
Instant messaging server. Backend in pure Golang, wire transport protocol is JSON over websocket.
Everything is a message in Open-IM-Server, so you can extend custom messages easily, there is no need to modify the server code.
Using microservice architectures, Open-IM-Server can be deployed using clusters.
By deployment of the Open-IM-Server on the customer's server, developers can integrate instant messaging and real-time network capabilities into their own applications free of charge and quickly, and ensure the security and privacy of business data.

### 👨‍💻‍ How you can help ?
We are very serious saved your information, in the [user case studies](https://github.com/OpenIMSDK/community/blob/main/ADOPTERS.md) has a comprehensive user information, You can submit a PR to ADOPTERS, or you can use the template below to comment.

**✍️ template:**

Submit a comment in this issue to include the following information
+ What your organization or company uses OpenIM for
+ Link to your website
+ Your country
+ Your contact info to reach out to you: blog, email or wechat (at least one).
+ What is your scenario for using OpenIMSDK?
+ Are you running you application in Testing or Production?

Copy the template below:
```bash
## {Organization/Company} 
+ *Application*: 
+ *Website*: doc.rentsoft.cn
+ *Country*: China
+ *Contact*: 
+ *Usage scenario*:  
+ *Status*: Production
```
> **Note**
> Please leave as much information as you can, and we'll send some small gifts.

**Comment by zjmantou1012** [comment]
flutter的demo下载安装后，无法登录账号，Android/iOS版本均可以
