### ISSUE TITLE
🗓️ Biweekly community meeting

### ISSUE THREAD

**Issue by cubxxw** [openimsdk/open-im-server#381]
#### 📝 What does the community meeting involve?
1. The action progress left over from last week's meeting
2. The significant progress in two weeks
3. Review important proposals[Optional]
4. Free talk, share a view.

#### ⛳ How to join us？
+ Subscribe to our [🗓️social calendar](https://calendar.google.com/calendar/embed?src=011a7ab3a894d926ae5d4d1cd8134c4ca9ad42decb9b4077eebaf42e7d1956c5%40group.calendar.google.com&ctz=Asia%2FShanghai)
+ [💬Join slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) is where we get real-time information

#### ⛽ Reinforcement
+ Preparation and summary of the meeting -> [https://github.com/OpenIMSDK/Open-IM-Server/discussions/categories/meeting](https://github.com/OpenIMSDK/Open-IM-Server/discussions/categories/meeting)
+ Links to the conference -> [https://meeting.tencent.com/dm/y6D9zgQbcXmF](https://meeting.tencent.com/dm/y6D9zgQbcXmF)
+ Meeting list and documentation -> [https://docs.google.com/document/d/1nx8MDpuG74NASx081JcCpxPgDITNTpIIos0DS6Vr9GU/edit?usp=sharing](https://docs.google.com/document/d/1nx8MDpuG74NASx081JcCpxPgDITNTpIIos0DS6Vr9GU/edit?usp=sharing)
+ [Request for One-on-One Contact or Technical Support](https://calendly.com/cubxxw/30min)
> **Note**
> We control the comment time of each meeting to be no more than one hour. We care about the efficiency of the meeting. Before the meeting starts, we share our problems in the issue and discuss them in advance. At the end we summarize the meeting and conclude the meeting.

**Comment by cubxxw** [comment]
Google Ical subscription
： https://calendar.google.com/calendar/ical/011a7ab3a894d926ae5d4d1cd8134c4ca9ad42decb9b4077eebaf42e7d1956c5%40group.calendar.google.com/public/basic.ics

**Comment by cubxxw** [comment]
## Step
![image](https://github.com/openimsdk/open-im-server/assets/86140903/e3f18863-7421-4ece-b600-55dcd3562abd)
![image](https://github.com/openimsdk/open-im-server/assets/86140903/97817a67-9079-4d18-ac7c-1c3f77f84f1b)
![image](https://github.com/openimsdk/open-im-server/assets/86140903/02669f7d-9599-4480-8494-429d40de4729)

**filling-in:**
```bash
https://calendar.google.com/calendar/ical/011a7ab3a894d926ae5d4d1cd8134c4ca9ad42decb9b4077eebaf42e7d1956c5%40group.calendar.google.com/public/basic.ics
```

**Comment by hhmm0808** [comment]
I want to join the slack community, this is my slack account  `hhhmmm00808@gmail.com`.

**Comment by cubxxw** [comment]
> I want to join the slack community, this is my slack account `hhhmmm00808@gmail.com`.

You are welcome to join our Slack community by following this link: https://join.slack.com/t/openimsdk/shared_invite/zt-22720d66b-o_FvKxMTGXtcnnnHiMqe9Q. We look forward to having you as part of our team!
