### ISSUE TITLE
[DOCS] There is no core submodule under the main branch

### ISSUE THREAD

**Issue by aliyoge** [OpenIMSDK/Open-IM-Server#427]
### Description

<img width="786" alt="image" src="https://github.com/OpenIMSDK/Open-IM-Server/assets/12035097/2b3e3bdb-2c09-4a66-8c4d-0b36ea728993">

**Comment by cubxxw** [comment]
That's not needed anymore

**Comment by aliyoge** [comment]
git clone https://github.com/OpenIMSDK/Open-IM-Server.git --recursive 
cd cmd/Open-IM-SDK-Core
git checkout main
你们文档里写了的，而且你们打包脚本里面需要打包 core
![image](https://github.com/OpenIMSDK/Open-IM-Server/assets/12035097/dacf15eb-798d-4a20-ad77-d32aabd4b4d3)

**Comment by cubxxw** [comment]
The documentation hasn't been updated

**Comment by cubxxw** [comment]
new: https://www.openim.online/

**Comment by skiffer-git** [comment]
in cmd directory
git clone https://github.com/OpenIMSDK/openim-sdk-core
