### ISSUE TITLE
how to build sdk from openim

### ISSUE THREAD

**Issue by liaozhimingandy** [OpenIMSDK/Open-IM-Server#440]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

❎ No

### Problem Description

Expected to provide a document on how to compile OpenIM core into SDK files for various platforms

### Solution Description

Expected to provide a document on how to compile OpenIM core into SDK files for various platforms

### Benefits

Users can build their own

**Comment by cubxxw** [comment]
Of course, may I kindly inquire about the specific documentation you require and its intended purpose? This information will enable me to provide you with a more precise explanation for the necessity of it.

**Comment by parkerPbq** [comment]
为什么没有中文提问

**Comment by skiffer-git** [comment]
Are you asking about building the SDK through [openim-core](https://github.com/OpenIMSDK/openim-sdk-core)?

**Comment by skiffer-git** [comment]
Please raise this issue in this repository.


https://github.com/OpenIMSDK/openim-sdk-core/issues
