### ISSUE TITLE
Efficient Offline Deployment of OpenIM: Solving Docker Image Pulling Issues with COS

### ISSUE THREAD

**Issue by cubxxw** [OpenIMSDK/Open-IM-Server#447]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

✅ Yes

### Problem Description

OpenIM is an open-source instant messaging solution for enterprise-level communication. It is widely used in various industries due to its high performance, scalability, and security. However, when deploying OpenIM through Docker, users may encounter issues with pulling the necessary images due to DNS contamination. In this article, we will introduce an offline deployment solution for OpenIM that solves this problem.

+ [x] [🎯 OpenIM image docker multi-architecture and offline deployment](https://github.com/OpenIMSDK/Open-IM-Server/issues/432)

## Images list

| Service Name       | Image                                   | Supported Architectures | Ports                   | Download Link                                                |
| ------------------ | --------------------------------------- | ----------------------- | ----------------------- | ------------------------------------------------------------ |
| mysql              | mysql:5.7                               | amd64, arm64v8, arm32v7 | 13306:3306, 23306:33060 | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/mysql.tar |
| mongodb            | mongo:4.0                               | amd64, arm64v8, arm32v7 | 37017:27017             | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/mongo.tar |
| redis              | redis                                   | amd64, arm64v8, arm32v7 | 16379:6379              | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/redis.tar |
| zookeeper          | wurstmeister/zookeeper                  | amd64                   | 2181:2181               | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/zookeeper.tar |
| kafka              | wurstmeister/kafka                      | arm,amd64               | 9092:9092               | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/kafka.tar |
| etcd               | http://quay.io/coreos/etcd              | amd64, arm64v8          | 2379:2379, 2380:2380    | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/etcd.tar |
| minio              | minio/minio                             | amd64, arm64v8, arm32v7 | 10005:9000, 9090:9090   | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/minio.tar |
| open_im_server     | openim/open_im_server:v2.3.8            | amd64                   | N/A                     | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/open_im_server.tar |
| open_im_enterprise | openim/open_im_enterprise:v1.0.3        | amd64                   | N/A                     | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/open_im_enterprise.tar |
| prometheus         | prom/prometheus                         | amd64, arm64v8, arm32v7 | N/A                     | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/prometheus.tar |
| grafana            | grafana/grafana                         | amd64, arm64v8, arm32v7 | N/A                     | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/grafana.tar |
| node-exporter      | http://quay.io/prometheus/node-exporter | amd64, arm64v8, arm32v7 | 9100:9100               | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/node-exporter.tar |

---

> **Note**
> We use etcd as an example to demonstrate the steps ⏬⏬⏬

### Benefits

The offline deployment solution for OpenIM with COS brings several benefits to the user, including:

1. Reliable and efficient deployment: With the offline deployment solution, users can deploy OpenIM without being affected by DNS contamination, which can cause slow image pulling speeds or complete failure to pull the images. This provides a reliable and efficient deployment process for OpenIM.
2. High-speed download channel: By saving the necessary images to a COS, users can download them from a high-speed download channel, which provides faster download speeds compared to the Docker Hub.
3. Cost-effective storage solution: COS provides a cost-effective storage solution for saving the necessary images, which can help users save on storage costs compared to other cloud storage solutions.

### Potential Drawbacks

no

## The Solution

To solve this problem, we recommend using an offline deployment solution for OpenIM. This solution involves saving the necessary images to a cloud object storage (COS) service, such as Tencent Cloud's COS, and then downloading them from the COS to the local machine for deployment. This approach provides a high-speed download channel and avoids the DNS pollution issue.

### Step 1: Save Images to COS

The first step is to save the necessary image into COS. We recommend using Tencent Cloud's COS, as it provides a reliable and cost-effective storage solution. The following is an example of how to save the etcd image to Tencent Cloud's COS:

```bash
https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/etcd.tar
```

### Step 2: Download Images from COS

After saving the images to the COS, users can download them to the local machine for deployment. The following is an example of how to download the etcd image from Tencent Cloud's COS:

```bash
wget https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/etcd.tar
```

### Step 3: Deploy OpenIM

Once the images have been downloaded, users can proceed with the deployment of OpenIM. The following is an example of how to deploy OpenIM using the etcd image:

```bash
docker load -i etcd.tar
```

### Step 4: Deploy OpenIM - docker - compose

> **Note:**
> Note that compose was integrated with docker around version 20, otherwise you need to download docker-compose yourself

```
docker compose up
```

**Comment by 13594439126** [comment]
open_im_server | openim/open_im_server:v2.3.8 | amd64 | N/A | https://openim-1306374445.cos.ap-guangzhou.myqcloud.com/openim/image/amd/off-line/off-line/open_im_server.tar
因为是2.3.8版本，所以不能用git clone https://github.com/OpenIMSDK/Open-IM-Server.git --recursive;版本的源码，
详情查看https://nsddd.notion.site/435ee747c0bc44048da9300a2d745ad3
