### ISSUE TITLE
[Other]: <give this problem a name>

### ISSUE THREAD

**Issue by NinJaSir** [OpenIMSDK/Open-IM-Server#451]
### What would you like to share?

./batch_build_all_service.sde时候，cpu暴涨到100%，本地的机器好点，能撑过去，服务器完全卡死，导致部署出问题
![image](https://github.com/OpenIMSDK/Open-IM-Server/assets/12709954/97287490-5676-4c0d-b977-ef08236e082f)
![image](https://github.com/OpenIMSDK/Open-IM-Server/assets/12709954/38945f4d-f37e-480a-a9cc-32389a2b4aaf)

**Comment by skiffer-git** [comment]
./batch_build_all_service.sh will compile in parallel, which may consume a lot of CPU and memory.
./build_all_service.sh will compile serially, consuming less CPU and memory, but the compilation time may be longer.
