### ISSUE TITLE
请求/auth/user_register报errCode：400是什么原因

### ISSUE THREAD

**Issue by Liu-Peter** [OpenIMSDK/Open-IM-Server#46]
![err](https://user-images.githubusercontent.com/28050706/140478719-fc07e7b4-6347-4d6a-8821-3e411f9d973e.png)

**Comment by FGadvancer** [comment]
Post not use &(this is Get),please put args into body raw.
![image](https://user-images.githubusercontent.com/46924906/140488312-e7993d09-4e7a-44d8-ad6f-cedb5028d3cd.png)
