### ISSUE TITLE
GetUserOnlineStatus  function has not been implemented

### ISSUE THREAD

**Issue by landryXu** [OpenIMSDK/Open-IM-Server#472]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [OpenIMSDK Slack](https://join.slack.com/t/openimsdk/shared_invite/zt-1tmoj26uf-_FDy3dowVHBiGvLk9e5Xkg) and got positive feedback

### Is this feature request related to a problem?

None

### Problem Description

![image](https://github.com/OpenIMSDK/Open-IM-Server/assets/17511698/c6efbd69-e636-4cb5-b177-2af015f874f3)

### Solution Description

At present, the interface of V3 version is not perfect. The above screenshot is an interface for obtaining the user's online status. Currently, there is no business implementation code

### Benefits

This function is more important to our business, we need to know the user's online status

**Comment by FGadvancer** [comment]
This function has existed on vrealease3.1 branch
