### ISSUE TITLE
Bug: force_logout api

### ISSUE THREAD

**Issue by hanzhixiao** [OpenIMSDK/Open-IM-Server#487]
### What happened?

{
    "errCode": 500,
    "errMsg": "ServerInternalError",
    "errDlt": "==> github.com/OpenIMSDK/Open-IM-Server/internal/rpc/auth.(*authServer).forceKickOff()@116: : : grpc: the client connection is closing: ServerInternalError"
}
err is shown when force_logout api is called.

### What did you expect to happen?

user is kicked off normally.

### How can we reproduce it (as minimally and precisely as possible)?

Call force_logout api twice.

### version

v3dev

### Cloud provider

<details>
windows
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by wangchuxiao-dev** [comment]
this bug has fixed
