### ISSUE TITLE
配置中的token过期时间单位与jwt中没有对应上

### ISSUE THREAD

**Issue by tzwsoho** [OpenIMSDK/Open-IM-Server#53]
https://github.com/OpenIMSDK/Open-IM-Server/blob/7f2270844e538907f325f2639d13e8e68baa25ec/src/utils/jwt_token.go#L31

这里ttl的时间单位是“天数”，但配置里面用的是“秒数”

https://github.com/OpenIMSDK/Open-IM-Server/blob/7f2270844e538907f325f2639d13e8e68baa25ec/config/config.yaml#L141-L143

已经提交了pr：
#52

**Comment by FGadvancer** [comment]
This err due to code merging, the latest version has been updated, please re-pull
