### ISSUE TITLE
有无计划将kafka更换成pulsar?

### ISSUE THREAD

**Issue by qinxin0720** [OpenIMSDK/Open-IM-Server#55]
在单机模式中，可以减少组件数量。

另外，kafka没有官方的docker镜像，使用第三方的镜像无法保证安全性。

**Comment by ou-bing** [comment]
apache pulsar 用 K8s 部署也更加简单，要是消息队列可以自由选择就更完美了🤔

**Comment by cmdares** [comment]
目前pulsar的态势非常好，鼓励官方考虑pulsar承担kafka的角色。
亦或考虑使用国产的开源的emqx替代相关的组件。
