### ISSUE TITLE
发送消息导致服务崩溃

### ISSUE THREAD

**Issue by smokesea** [OpenIMSDK/Open-IM-Server#56]
2021/11/10 14:40:55 [ handle_func.go : 32 ] [Basic Info Authentication Success reqFuncName  SendMessage data  {"recvID":"d5645454518","groupID":null,"onlineUserOnly":false,"message":"{\"clientMsgID\":\"03fe998e50949a7a6fcd316fc37736b0\",\"serverMsgID\":\"\",\"createTime\":1636526455552711420,\"sendTime\":1636526455552711420,\"sessionType\":0,\"sendID\":\"d5645454517\",\"recvID\":\"\",\"msgFrom\":100,\"contentType\":101,\"platformID\":5,\"forceList\":null,\"senderNickName\":\"张三\",\"senderFaceUrl\":\"\",\"groupID\":\"\",\"content\":\"abc\",\"seq\":0,\"isRead\":false,\"status\":1,\"remark\":\"\",\"pictureElem\":{\"sourcePath\":\"\",\"sourcePicture\":{\"uuid\":\"\",\"type\":\"\",\"size\":0,\"width\":0,\"height\":0,\"url\":\"\"},\"bigPicture\":{\"uuid\":\"\",\"type\":\"\",\"size\":0,\"width\":0,\"height\":0,\"url\":\"\"},\"snapshotPicture\":{\"uuid\":\"\",\"type\":\"\",\"size\":0,\"width\":0,\"height\":0,\"url\":\"\"}},\"soundElem\":{\"uuid\":\"\",\"soundPath\":\"\",\"sourceUrl\":\"\",\"dataSize\":0,\"duration\":0},\"videoElem\":{\"videoPath\":\"\",\"videoUUID\":\"\",\"videoUrl\":\"\",\"videoType\":\"\",\"videoSize\":0,\"duration\":0,\"snapshotPath\":\"\",\"snapshotUUID\":\"\",\"snapshotSize\":0,\"snapshotUrl\":\"\",\"snapshotWidth\":0,\"snapshotHeight\":0},\"fileElem\":{\"filePath\":\"\",\"uuid\":\"\",\"sourceUrl\":\"\",\"fileName\":\"\",\"fileSize\":0},\"mergeElem\":{\"title\":\"\",\"abstractList\":null,\"multiMessage\":null},\"atElem\":{\"text\":\"\",\"atUserList\":[],\"isAtSelf\":false},\"locationElem\":{\"description\":\"\",\"longitude\":0,\"latitude\":0},\"customElem\":{\"data\":\"\",\"description\":\"\",\"extension\":\"\"},\"quoteElem\":{\"text\":\"\",\"quoteMessage\":null}}"} recv jsonMsg:  {"reqFuncName":"SendMessage","operationID":"1tvam1343n6455449","uid":"d5645454517","data":"{\"recvID\":\"d5645454518\",\"groupID\":null,\"onlineUserOnly\":false,\"message\":\"{\\\"clientMsgID\\\":\\\"03fe998e50949a7a6fcd316fc37736b0\\\",\\\"serverMsgID\\\":\\\"\\\",\\\"createTime\\\":1636526455552711420,\\\"sendTime\\\":1636526455552711420,\\\"sessionType\\\":0,\\\"sendID\\\":\\\"d5645454517\\\",\\\"recvID\\\":\\\"\\\",\\\"msgFrom\\\":100,\\\"contentType\\\":101,\\\"platformID\\\":5,\\\"forceList\\\":null,\\\"senderNickName\\\":\\\"张三\\\",\\\"senderFaceUrl\\\":\\\"\\\",\\\"groupID\\\":\\\"\\\",\\\"content\\\":\\\"abc\\\",\\\"seq\\\":0,\\\"isRead\\\":false,\\\"status\\\":1,\\\"remark\\\":\\\"\\\",\\\"pictureElem\\\":{\\\"sourcePath\\\":\\\"\\\",\\\"sourcePicture\\\":{\\\"uuid\\\":\\\"\\\",\\\"type\\\":\\\"\\\",\\\"size\\\":0,\\\"width\\\":0,\\\"height\\\":0,\\\"url\\\":\\\"\\\"},\\\"bigPicture\\\":{\\\"uuid\\\":\\\"\\\",\\\"type\\\":\\\"\\\",\\\"size\\\":0,\\\"width\\\":0,\\\"height\\\":0,\\\"url\\\":\\\"\\\"},\\\"snapshotPicture\\\":{\\\"uuid\\\":\\\"\\\",\\\"type\\\":\\\"\\\",\\\"size\\\":0,\\\"width\\\":0,\\\"height\\\":0,\\\"url\\\":\\\"\\\"}},\\\"soundElem\\\":{\\\"uuid\\\":\\\"\\\",\\\"soundPath\\\":\\\"\\\",\\\"sourceUrl\\\":\\\"\\\",\\\"dataSize\\\":0,\\\"duration\\\":0},\\\"videoElem\\\":{\\\"videoPath\\\":\\\"\\\",\\\"videoUUID\\\":\\\"\\\",\\\"videoUrl\\\":\\\"\\\",\\\"videoType\\\":\\\"\\\",\\\"videoSize\\\":0,\\\"duration\\\":0,\\\"snapshotPath\\\":\\\"\\\",\\\"snapshotUUID\\\":\\\"\\\",\\\"snapshotSize\\\":0,\\\"snapshotUrl\\\":\\\"\\\",\\\"snapshotWidth\\\":0,\\\"snapshotHeight\\\":0},\\\"fileElem\\\":{\\\"filePath\\\":\\\"\\\",\\\"uuid\\\":\\\"\\\",\\\"sourceUrl\\\":\\\"\\\",\\\"fileName\\\":\\\"\\\",\\\"fileSize\\\":0},\\\"mergeElem\\\":{\\\"title\\\":\\\"\\\",\\\"abstractList\\\":null,\\\"multiMessage\\\":null},\\\"atElem\\\":{\\\"text\\\":\\\"\\\",\\\"atUserList\\\":[],\\\"isAtSelf\\\":false},\\\"locationElem\\\":{\\\"description\\\":\\\"\\\",\\\"longitude\\\":0,\\\"latitude\\\":0},\\\"customElem\\\":{\\\"data\\\":\\\"\\\",\\\"description\\\":\\\"\\\",\\\"extension\\\":\\\"\\\"},\\\"quoteElem\\\":{\\\"text\\\":\\\"\\\",\\\"quoteMessage\\\":null}}\"}"}]
panic: interface conversion: interface {} is nil, not string

**Comment by skiffer-git** [comment]
"groupID":null   -> "groupID":""

**Comment by smokesea** [comment]
> "groupID":null -> "groupID":""

已经看了代码，我赶脚那部分的处理是不是加点保护的好。如果仅仅因为协议层面一点问题导致服务的崩溃会是个非常严重的问题。多谢回复
