### ISSUE TITLE
Bug: <Send message interface exception>

### ISSUE THREAD

**Issue by xzy66s** [OpenIMSDK/Open-IM-Server#593]
### What happened?

When I call the /msg/send_msg interface, the incoming contentType is 1203. What the service returned to me was error code 1001, and the error message was not support err contentType

### What did you expect to happen?

The service should execute correctly when I have the parameters correct

The following contentType should work normally: 1201, 1203, 1501, 1505

### How can we reproduce it (as minimally and precisely as possible)?

Call the /msg/send_msg interface and pass in one of contentType 1201, 1203, 1501, 1505

### version

<details>
```console
$ {name} version
# 3.0.0
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by wangchuxiao-dev** [comment]
1201, 1203, 1501, 1505 is notification contentType should not be send here
