### ISSUE TITLE
Bug: the deployment failed and port 10005 is not open

### ISSUE THREAD

**Issue by BanTanger** [OpenIMSDK/Open-IM-Server#598]
### What happened?

see log for details：

```bash
configFolderPath: 
use config /Open-IM-Server/config/config.yaml
use config /Open-IM-Server/config/notification.yaml
cron task start, config 0 2 * * 3
mongo: mongodb://root:openIM123@127.0.0.1:37017/openIM_v3?maxPoolSize=100&authSource=admin
panic: ==> github.com/OpenIMSDK/Open-IM-Server/pkg/startrpc.Start()@93: : Get "http://43.128.72.19:10005/openim/?location=": dial tcp 43.128.72.19:10005:
 i/o timeout

goroutine 1 [running]:
main.main()
        /Open-IM-Server/cmd/openim-rpc/openim-rpc-third/main.go:31 +0xd9
```

### What did you expect to happen?

none

### How can we reproduce it (as minimally and precisely as possible)?

Reference the documentation `https://doc.rentsoft.cn/guides/gettingStarted/chatSourceCodeDeployment` to build

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by withchao** [comment]
If the IP configuration is correct, please check whether the server firewall is enabled and whether the Tencent Cloud security group is configured correctly.

**Comment by BanTanger** [comment]
pr #602
