### ISSUE TITLE
Bug: chat ./start_all.sh success but not run

### ISSUE THREAD

**Issue by zhouping-git** [OpenIMSDK/Open-IM-Server#608]
### What happened?

Use the official website source code installation tutorial.

Server can be used normally.
Chat cannot be used normally.

Use source code deployment.

![7d803562973063b9b027dd57adb33a4](https://github.com/OpenIMSDK/Open-IM-Server/assets/72516108/a08aaeae-9db1-46fc-8090-897c535f9830)
![5419fc9c34e81e4ee1cc60a3ae08640](https://github.com/OpenIMSDK/Open-IM-Server/assets/72516108/12c8f67c-67e4-4073-9cc0-60c9ac523f68)
![074e0b7176b4e1b7d601299e2bbf4b0](https://github.com/OpenIMSDK/Open-IM-Server/assets/72516108/9fff6907-df09-47a7-9da6-546a0e04a7ce)
![b96b1f3b35fe3379813cced92dd6a03](https://github.com/OpenIMSDK/Open-IM-Server/assets/72516108/a2cdcdd2-6a42-4f9e-9882-8d3a981f0ebe)

### What did you expect to happen?

The service can be used normally.

### How can we reproduce it (as minimally and precisely as possible)?

Not sure how to reproduce. Because no exception is thrown.

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by skiffer-git** [comment]
https://github.com/OpenIMSDK/chat/tree/release-v1.0

Need to deploy using this repository additionally

**Comment by skiffer-git** [comment]
1. Confirm whether the port is open; 
2. Try using Postman or download the app for testing."

**Comment by zhouping-git** [comment]
> 1. Confirm whether the port is open;
> 2. Try using Postman or download the app for testing."

I confirm that I have opened the port.
The test app has been downloaded, and the call to the registration interface prompts the link timeout. 
@skiffer-git
