### ISSUE TITLE
Bug: <high memory usage>Has the problem of open-Im-server-sdk 's increasing memory usage with increasing runtime been resolved?

### ISSUE THREAD

**Issue by Rick-Do** [OpenIMSDK/Open-IM-Server#609]
### What happened?

As the runtime increases, the memory usage becomes higher and higher。Also at issue #176 in v 2.3.3 。

### What did you expect to happen?

Stable memory usage

### How can we reproduce it (as minimally and precisely as possible)?

Resolve the problem that memory leak on user exit

### version

<details>

V 2.3.3
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
</details>

### Install tools

<details>
</details>

**Comment by skiffer-git** [comment]
The open-Im-server-sdk has been deprecated, and we are preparing to use the pure jssdk version as a replacement

**Comment by Rick-Do** [comment]
Will this issue occur with jssdk？

**Comment by skiffer-git** [comment]
The new jssdk no longer requires jssdk-server (port 10003).
