### ISSUE TITLE
部署环境：windows子系统搭配docker for window, 执行start_all.sh时，openIM.log报mysql数据库连接错误

### ISSUE THREAD

**Issue by panda932** [OpenIMSDK/Open-IM-Server#64]
![image](https://user-images.githubusercontent.com/19890081/141714127-e9d90481-77d4-45c2-8db6-074abcba3600.png)

![image](https://user-images.githubusercontent.com/19890081/141714270-d167599b-bbcc-4c6a-a825-39c7a6fb3d83.png)

![image](https://user-images.githubusercontent.com/19890081/141714211-c7ad844d-24f9-401e-b13d-79d9b35dc0b7.png)

**Comment by CngLeo** [comment]
![image](https://user-images.githubusercontent.com/19890081/141715590-9378fba8-0aba-4fde-8a91-3e4539f81d2d.png)

![938a2dd91857b8f3c207222d2d1f78f](https://user-images.githubusercontent.com/19890081/141715634-c9da7e6a-8367-4be0-bedd-b4f759568e25.png)

**Comment by panda932** [comment]
![image](https://user-images.githubusercontent.com/19890081/142344685-987486bd-acff-4656-959c-f7e570ce23bb.png)

**Comment by ClockworkChen** [comment]
看日志是密码不对，检查下config.yaml里面对mysql密码的配置

**Comment by skiffer-git** [comment]
Use the latest image
