### ISSUE TITLE
[Other]: how to deploy multi im-server

### ISSUE THREAD

**Issue by faceany** [openimsdk/open-im-server#688]
### What would you like to share?

How to deploy multi im-server?
I found 
https://github.com/OpenIMSDK/Open-IM-Server/blob/main/deployments/README.md
and read it ,but can not finished depoloy mulit im-server!

**Comment by faceany** [comment]
anybody know?

**Comment by cubxxw** [comment]
@faceany We have multi-architecture mirrors, but no clustering solution yet (official), we have a lot of cluster examples to show you

**Comment by cubxxw** [comment]
## Link

- https://github.com/OpenIMSDK/k8s-jenkins
- https://github.com/OpenIMSDK/Open-IM-Server-k8s-deploy
- https://github.com/OpenIMSDK/openim-charts
