### ISSUE TITLE
web端 createCustomMessage  这个方法成功和异常都没有进入

### ISSUE THREAD

**Issue by jiafengfeng12345** [OpenIMSDK/Open-IM-Server#69]
传入的参数是{
    "data": "{\"endText\":\"您对本次服务满意嘛?\",\"chatUserId\":\"0005\",\"endType\":\"endThisChat\"}",
    "expand": "",
    "desc": "本次会话结束"
}

**Comment by skiffer-git** [comment]
use 2.2.0
