### ISSUE TITLE
部署环境：windows子系统搭配docker for window

### ISSUE THREAD

**Issue by AppAllBug** [OpenIMSDK/Open-IM-Server#71]
安装Docker部署步骤
执行 ./docker_check_service.sh

运行成功
执行check_all.sh显示有服务失败

**Comment by AppAllBug** [comment]
![852d2b52a560e3b005cd68c5fe1f05b](https://user-images.githubusercontent.com/94432567/141934539-b2cbf68e-3a35-4e4a-a7e8-8abe24204414.png)

**Comment by AppAllBug** [comment]
![Uploading 4%2Z11VRLZ_%G$N5~IOY4D4.png…]()

**Comment by AppAllBug** [comment]
![1212](https://user-images.githubusercontent.com/94432567/141934761-9bdaec13-01f3-4071-92b6-958a86f65d9b.png)

**Comment by AppAllBug** [comment]
![121212](https://user-images.githubusercontent.com/94432567/141934965-8b0def2d-7cc2-4930-9b08-9acf2577b34e.png)

**Comment by AppAllBug** [comment]
![55](https://user-images.githubusercontent.com/94432567/141935058-828e4dad-6b6a-4a0d-9524-5c3318fbc1ff.png)

**Comment by AppAllBug** [comment]
![88](https://user-images.githubusercontent.com/94432567/141935321-deed6913-dc8e-4354-96aa-28c1f81f9a84.png)

**Comment by ChainFans** [comment]
windows下部署成功了吗？

**Comment by shoyu666** [comment]
windows下docker-compose部署完后
      - kafka  成功
      - mysql 成功
      - mongodb 成功
      - redis 成功
      - etcd 成功
      - minio 成功
      - open_im_server 失败
 
此时可以单独删除open_im_server (通过docker desktop)
然后通过源码运行

> 修改相关配置 config.yaml
> win_build_all_service.cmd 编译
> win_start_all_service.cmd  运行

**Comment by skiffer-git** [comment]
Use Linux first
