### ISSUE TITLE
CentOS 7.6.1810 x86_64(Py3.7.9)下Docker部署

### ISSUE THREAD

**Issue by pangxianfei** [OpenIMSDK/Open-IM-Server#72]
![图片](https://user-images.githubusercontent.com/9346931/141942665-c2105dd4-50d8-4d57-8128-e81a125d680c.png)
CentOS 7.6.1810 x86_64(Py3.7.9)下Docker部署，出现的。是不是因为物理机安装mysql,redis,Mongo原因。

**Comment by jianghaibo12138** [comment]
看日志中的信息应该是端口占用了. 可以修改docker-compose的中网络模式映射端口处理端口占用的问题. 
![image](https://user-images.githubusercontent.com/17843033/143733753-fcd63763-d4bf-4aaa-bd27-db199ff97e2e.png)

**Comment by skiffer-git** [comment]
use v2.2.0
