### ISSUE TITLE
好友判定接口/friend/is_friend有问题

### ISSUE THREAD

**Issue by tzwsoho** [OpenIMSDK/Open-IM-Server#74]
https://github.com/OpenIMSDK/Open-IM-Server/blob/95ac2c62e88d90db7764b3c463e7e9be5b12f02d/internal/api/friend/is_friend.go#L33
应该是
https://github.com/tzwsoho/Open-IM-Server/blob/325a50af78d3fc47866cbc9a4dc121814b552ee0/internal/api/friend/is_friend.go#L33

已经提pr：
#73

**Comment by FGadvancer** [comment]
Thanks for submitting pr, merged
