### ISSUE TITLE
Bug: Display expired when logging in and retrieving password with verification code

### ISSUE THREAD

**Issue by DreamerXXT** [OpenIMSDK/Open-IM-Server#750]
### What happened?

When logging in with a verification code, it displays expired and cannot be logged in.
Similarly, I cannot use a verification code to retrieve the password.

### What did you expect to happen?

I hope to enable the verification code login and password retrieval functions to function properly.

### How can we reproduce it (as minimally and precisely as possible)?

1.Select verification code login method
2.Click to send verification code
3.Click logging button

### version

OpenIMSDK v3

### Cloud provider

[cubxxw](https://github.com/cubxxw)
[Xinwei Xiong](https://github.com/cubxxw)

### OS version

Windows 11 x64

### Install tools

<details>
</details>

**Comment by cubxxw** [comment]
<details>
<summary>Details</summary>

this is simple details

</details>
