### ISSUE TITLE
user_token和create_group使用的secret不统一

### ISSUE THREAD

**Issue by xinj2000** [OpenIMSDK/Open-IM-Server#80]
你好，config.yaml里有两处，secret: tuoyun和accessSecret: "open_im_server"，http://x.x.x.x:10000/auth/user_token使用的是secret而http://x.x.x.x:10000/group/create_group使用的是accessSecret，是不是要统一一下？

**Comment by xinj2000** [comment]
现在我使用相同的配置

**Comment by skiffer-git** [comment]
It's up to you
