### ISSUE TITLE
uniapp版本短信验证失败

### ISSUE THREAD

**Issue by ninvfeng** [OpenIMSDK/Open-IM-Server#86]
收到验证码后填写到app上提示: 验证码已失效
看到 pages/login/vercode.vue 中有使用res.verifyCode === 1 判断, 但接口返回没有verifyCode字段
![image](https://user-images.githubusercontent.com/6409949/143207049-6704a29a-277f-4a13-a994-75856e9bbe04.png)

**Comment by ninvfeng** [comment]
应在 Open-IM-Demo-Register/cmd/register/verify.go 添加 data["verifyCode"] = 1
![image](https://user-images.githubusercontent.com/6409949/143208616-37c60057-6b6c-43fe-8a7e-6d3f796368f1.png)

**Comment by skiffer-git** [comment]
Waiting for new version
