### ISSUE TITLE
Websocket 服务崩溃

### ISSUE THREAD

**Issue by tiejia** [OpenIMSDK/Open-IM-Server#87]
使用WebAPI连接WebSocket，会经常出现以下错误，然后导致WebSocket服务无法连接，需要重启才可以。

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x500747]

goroutine 422 [running]:
database/sql.(*Rows).Next(0x0)
        /usr/local/go/src/database/sql/sql.go:2944 +0x27
open_im_sdk/open_im_sdk.(*UserRelated).getAllConversationListModel(0xfb58e0)
        /Open-IM-Server/cmd/Open-IM-SDK-Core/open_im_sdk/data_model.go:404 +0x105
open_im_sdk/open_im_sdk.(*UserRelated).doUpdateConversation(0xc00037ba20, {{0x0, 0x35}, {0xa8d2c0, 0xc0001cb9d0}})
        /Open-IM-Server/cmd/Open-IM-SDK-Core/open_im_sdk/conversation_msg.go:403 +0x62f
open_im_sdk/open_im_sdk.(*UserRelated).doMsgNew(0xc00037ba20, {{0x2, 0x2}, {0x41, 0xc913dd}})
        /Open-IM-Server/cmd/Open-IM-SDK-Core/open_im_sdk/conversation_msg.go:250 +0x22ed
open_im_sdk/open_im_sdk.(*UserRelated).work(0xc0003796f0, {{0xae9e7b, 0x1}, {0xa79e00, 0xc000285650}})
        /Open-IM-Server/cmd/Open-IM-SDK-Core/open_im_sdk/conversation_msg.go:452 +0x2a7
open_im_sdk/open_im_sdk.doListener({0xbb0ad0, 0xc00037ba20})
        /Open-IM-Server/cmd/Open-IM-SDK-Core/open_im_sdk/cmd_interface.go:97 +0xf1
created by open_im_sdk/open_im_sdk.(*UserRelated).initSDK
        /Open-IM-Server/cmd/Open-IM-SDK-Core/open_im_sdk/init_login.go:31 +0x1cf

另外，在msg_gate的error中会有很多以下错误

2021-11-24 18:05:49.567 [ERRO] [PID:201] [FilePath:gate/ws_server.go:72] [OperationID:] [error:websocket: close 1006 (abnormal closure): unexpected EOF] [userIP:192.168.3.209:44738] [userUid:arii1637724047333053917 Web] WS ReadMsg error

**Comment by skiffer-git** [comment]
Pull the latest image
