### ISSUE TITLE
希望opemim增加类似rpc的即时回调通知第三方系统，完成特殊业务需求

### ISSUE THREAD

**Issue by 54huige** [OpenIMSDK/Open-IM-Server#91]
**需求：**
通过rpc或wss等协议任意监听openim里的数据接收和发送，并支持双向通信，既可以监听来自openim里的任意事件或接口，也能触发相关事件或接口。
**理由**
1.熟悉并修改openim风险更大 需要一定的精力熟悉，并承担未知的风险
2.二开后将可能会无法随时更新openim，并伴随未知风险
3.由于openim很稳定，我们借助openim的稳定性，将特殊需求在我们其他系统框架中去实现，这样就可以降低以上说明的风险和避免部分问题，灵活性将大大提高
**参考**
可能我说的不是很清楚 但是有一个项目是 某Q协议项目 他们的实现应该是比较理想的效果，也能更好的完整表达我的想法
这是一个https://github.com/Mrs4s/go-cqhttp 服务框架 可以二开也可以开启wss
github.com/wdvxdr1123/ZeroBot 这个就是基于上述的服务框架通过socket实现的二开，一种解耦的方式实现特殊的需求，希望项目组能考虑一下这种方式

**Comment by Ink-33** [comment]
首先感谢您对go-cqhttp和zerobot的关心。

通过您的叙述，认为您想要在openim中提供一个rpc/wss的通信方式供开发者使用，以实现第三方消息处理与openim本身的解耦合。

不知我的理解是否有误？

_Originally posted by @Ink-33 in https://github.com/Mrs4s/go-cqhttp/issues/1204#issuecomment-981057245_

**Comment by 54huige** [comment]
> 首先感谢您对go-cqhttp和zerobot的关心。
> 
> 通过您的叙述，认为您想要在openim中提供一个rpc/wss的通信方式供开发者使用，以实现第三方消息处理与openim本身的解耦合。
> 
> 不知我的理解是否有误？
> 
> _Originally posted by @Ink-33 in [Mrs4s/go-cqhttp#1204 (comment)](https://github.com/Mrs4s/go-cqhttp/issues/1204#issuecomment-981057245)_

没错，就是一种解耦的方式接入

**Comment by j1g5awi** [comment]
也许您想说的是让 openIM 支持 [onebot](https://github.com/botuniverse/onebot) 协议？

**Comment by 54huige** [comment]
@j1g5awi  不是，没太明白您的意思哈，我就是说 openIM支持rpc这类的通信，这样openim里的数据能主动推给我，我又可以随意主动调用openIM里的各种事件，这样双向通信完成我的监听数据事件等就足够了，这样 不管是怎么对接我都可以自主完成。不需要onebot这边官方作出支持，我就是单纯的希望openim支持一下rpc类的通信而已

**Comment by showurl** [comment]
我认为Open-IM系统已经非常庞大了，建议自己修改。
我修改了一个版本，你可以参考核心服务的逻辑  来进行修改。
[Path-IM-Server](https://github.com/Path-IM/Path-IM-Server)

**Comment by skiffer-git** [comment]
http callback
