### ISSUE TITLE
部署启动./start_all.sh报错

### ISSUE THREAD

**Issue by panda932** [OpenIMSDK/Open-IM-Server#92]
![image](https://user-images.githubusercontent.com/19890081/143538867-a0e9125a-7c7c-476d-beb2-33dbc3aadc3d.png)

**Comment by skiffer-git** [comment]
docker-compose down
git pull
docker-compose pull

chomd +x *.sh
docker-compose up -d

**Comment by panda932** [comment]
感谢你的回复，但按以上操作，这边报错的问题还是存在，贴附完整报错日志。

[openIM.log](https://github.com/OpenIMSDK/Open-IM-Server/files/7607502/openIM.log)

**Comment by panda932** [comment]
> docker-compose down git pull docker-compose pull
> 
> chmod +x *.sh 
> 
[openIM.log](https://github.com/OpenIMSDK/Open-IM-Server/files/7607540/openIM.log)
docker -compose up -d

谢谢你的回复，但按以上操作，此报错的问题还是存在，贴附完整报错。

**Comment by panda932** [comment]
![image](https://user-images.githubusercontent.com/19890081/143556009-22679bbb-5415-4ef6-ae4f-23a7470ca1f6.png)
![image](https://user-images.githubusercontent.com/19890081/143556034-9e929fb9-726c-47d6-a8b0-1407e46b2a39.png)
![image](https://user-images.githubusercontent.com/19890081/143556071-83d5459f-f724-4c23-8db1-9601391453d2.png)
![image](https://user-images.githubusercontent.com/19890081/143556103-8788473f-dc48-43e8-bcff-3b2b88ff269a.png)
![image](https://user-images.githubusercontent.com/19890081/143556196-5aec88ff-122f-4184-b49a-e871eaf2871a.png)
![image](https://user-images.githubusercontent.com/19890081/143556268-b3c4b02b-1ee2-46d0-96fa-30faa9755ffa.png)
[openIM.log](https://github.com/OpenIMSDK/Open-IM-Server/files/7607626/openIM.log)

**Comment by panda932** [comment]
> ![图片](https://user-images.githubusercontent.com/19890081/143556009-22679bbb-5415-4ef6-ae4f-23a7470ca1f6.png) ![图片](https://user-images.githubusercontent.com/19890081/143556034-9e929fb9-726c-47d6-a8b0-1407e46b2a39.png) ![图片](https://user-images.githubusercontent.com/19890081/143556071-83d5459f-f724-4c23-8db1-9601391453d2.png) ![图片](https://user-images.githubusercontent.com/19890081/143556103-8788473f-dc48-43e8-bcff-3b2b88ff269a.png) ![图片](https://user-images.githubusercontent.com/19890081/143556196-5aec88ff-122f-4184-b49a-e871eaf2871a.png) ![图片](https://user-images.githubusercontent.com/19890081/143556268-b3c4b02b-1ee2-46d0-96fa-30faa9755ffa.png) [打开IM.log](https://github.com/OpenIMSDK/Open-IM-Server/files/7607626/openIM.log)

**Comment by FGadvancer** [comment]
docker-compose ps  
tail -20 /logs/openIM.log

**Comment by skiffer-git** [comment]
docker-compose down
rm bin
docker-compose up -d

**Comment by jianghaibo12138** [comment]
看起来是main分支上的pkg/common/config/config.go里面的config.MultiLoginPolicy 是一个struct
![image](https://user-images.githubusercontent.com/17843033/143732258-bc369b27-eda8-41a0-a737-4e17f2094f0c.png)


config/config.yaml 中给的参数是一个int值. 
![image](https://user-images.githubusercontent.com/17843033/143732250-2a967c52-81e2-48f2-b844-35872f60437e.png)

导致的yaml解析异常. 只需要切换到 [v1.0.4](https://github.com/OpenIMSDK/Open-IM-Server/tree/v1.0.4)或者分支[tuoyun](https://github.com/OpenIMSDK/Open-IM-Server/tree/tuoyun)

**Comment by skiffer-git** [comment]
Use the latest image
