### ISSUE TITLE
[BUG] Server Crash

### ISSUE THREAD

**Issue by haoxf** [OpenIMSDK/Open-IM-Server#94]
### Environment:
Mac

### Physical Memory Capacity:
16G

### Docker Image:
lyt1123/open_im_server   d5f922f8c762

### Log File:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x4fe202]

goroutine 8081 [running]:
database/sql.(*Stmt).ExecContext(0x0, {0xbb6f50, 0xc00012e000}, {0xc000019c08, 0x2, 0x2})
 /usr/local/go/src/database/sql/sql.go:2578 +0x82
database/sql.(*Stmt).Exec(...)
 /usr/local/go/src/database/sql/sql.go:2610
open_im_sdk/open_im_sdk.(*UserRelated).setNeedSyncLocalMinSeq(0xc000285340, 0x4)
 /Open-IM-Server/cmd/Open-IM-SDK-Core/open_im_sdk/data_model.go:414 +0x233
open_im_sdk/open_im_sdk.(*UserRelated).getNeedSyncSeq(0xc0000ecf58, 0x1, 0x1)
 /Open-IM-Server/cmd/Open-IM-SDK-Core/open_im_sdk/init_login.go:444 +0x388
open_im_sdk/open_im_sdk.(*UserRelated).heartbeat(0xc000285340)
 /Open-IM-Server/cmd/Open-IM-SDK-Core/open_im_sdk/init_login.go:511 +0xde6
created by open_im_sdk/open_im_sdk.(*UserRelated).login
 /Open-IM-Server/cmd/Open-IM-SDK-Core/open_im_sdk/init_login.go:101 +0x5d7

**Comment by skiffer-git** [comment]
use v2.2.0
