### ISSUE TITLE
Open-IM-Flutter-Demo配合Open-IM-Server一直发不出消息

### ISSUE THREAD

**Issue by fs-sujieming** [OpenIMSDK/Open-IM-Server#95]
项目启动后，点击发消息，后端gateway模块一直输出下面的报错信息
[ERRO] [PID:25655] [FilePath:gate/logic.go:49] [OperationID:] [err:invalid character 'ÿ' in literal false (expecting 'a')] ws json Unmarshal err
请问一下 这个是什么问题？

**Comment by yangtianshi** [comment]
我也碰到这个问题 B收不到A发的消息

**Comment by skiffer-git** [comment]
use v2.2.0
