### ISSUE TITLE
openIM不错，潜力巨大，几个建议希望openIM发展更好。

### ISSUE THREAD

**Issue by 819692112** [OpenIMSDK/Open-IM-Server#97]
基础核心支持：即时消息支持文字、语音、视频。用户支持积分、余额，能交易、兑换、充值、提现，完善交易功能。
其它：用户分享系统，用户社交有私有朋友圈，公开的自媒体空间。功能扩展利用分成式插件市场，官方建立整合广告联盟、交易推广联盟。用户能通过官方的插件市场、联盟系统赢利，官方也有相应提成。形成双赢。

**Comment by nieshaoyu** [comment]
> 基础核心支持：即时消息支持文字、语音、视频。用户支持积分、余额，能交易、兑换、充值、提现，完善交易功能。 其它：用户分享系统，用户社交有私有朋友圈，公开的自媒体空间。功能扩展利用分成式插件市场，官方建立整合广告联盟、交易推广联盟。用户能通过官方的插件市场、联盟系统赢利，官方也有相应提成。形成双赢。

那为啥不直接用微信?

**Comment by 819692112** [comment]
微信是别人的，openim可以自己作项目发展，核心都是即时通讯，同质化openim肯定干不过微信，openim要有自己特色的高频应用。

**Comment by ggdream** [comment]
> 

@819692112 我想这个项目团队做的是一个开源SDK，你所想的是开源一个可直接商用的平台吧...

**Comment by cnlinjie** [comment]
@819692112 别，按你这个建议，这个平台就废了。。

**Comment by 89trillion-ziqiang** [comment]
> @819692112 别，按你这个建议，这个平台就废了。。

赞成， 关了这个issue 吧，这些建议 除了第一条，其他都往邪路上引。
