### ISSUE TITLE
请问有没有windows docker 的部署教程

### ISSUE THREAD

**Issue by ChainFans** [OpenIMSDK/Open-IM-Server#99]
我尝试了在windows docker 部署项目，但是出现了一些问题，找了一些解决方法但是都无效
![image](https://user-images.githubusercontent.com/10971834/144179824-b3988bb0-35c9-4ee6-a5d4-89a61dbf4e6e.png)
![image](https://user-images.githubusercontent.com/10971834/144179857-6b64a9b2-d0f2-4854-9404-c9a26f757c3f.png)

**Comment by ChainFans** [comment]
version: "3"
#fixme  Clone openIM Server project before using docker-compose,project address：https://github.com/OpenIMSDK/Open-IM-Server.git

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
      TZ: Asia/Shanghai
    restart: always


  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    container_name: kafka
    restart: always
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: 127.0.0.1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    #network_mode: "host"
    depends_on:
      - zookeeper

  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
      - 2380:2380
    container_name: etcd
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    environment:
      ETCDCTL_API: 3
    restart: always
    command: /usr/local/bin/etcd --name etcd0 --data-dir /etcd-data --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://0.0.0.0:2380 --initial-cluster etcd0=http://0.0.0.0:2380 --initial-cluster-token tkn --initial-cluster-state new

  open_im_server:
    image: openim/open_im_server
    ports:
      - 10000:10000
      - 17778:17778
      - 10100:10100
      - 10200:10200
      - 10300:10300
      - 10400:10400
      - 10500:10500
      - 10600:10600
      - 10700:10700
      - 30000:30000
    container_name: open_im_server
    volumes:
      - ./logs:/Open-IM-Server/logs
      - ./config/config.yaml:/Open-IM-Server/config/config.yaml
      - ./db/sdk:/Open-IM-Server/db/sdk
      - ./script:/Open-IM-Server/script

    restart: always
    depends_on:
      - kafka
      - etcd
    #network_mode: "host"
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"

**Comment by Jweein** [comment]
window docker 貌似不支持host 的network

**Comment by ChainFans** [comment]
> 

我已经全部更换为了端口ports，可以访问到服务但是报错，报错看上去像是源码编译的问题

**Comment by ChainFans** [comment]
> window docker 貌似不支持host 的network

我已经全部更换为了端口ports，可以访问到服务但是报错，报错看上去像是源码编译的问题

**Comment by ChainFans** [comment]
> window docker 貌似不支持host 的network

我已经全部更换为了端口ports，可以访问到服务但是报错，具体报错上面的图片有

**Comment by Jweein** [comment]
> > window docker 貌似不支持host 的network
> 
> 我已经全部更换为了端口ports，可以访问到服务但是报错，具体报错上面的图片有

im_server 我是直接window 编译成exe自己跑的，顺便可以调试，  kafka mysql mongo 等组件是docker 容器

**Comment by xyctruth** [comment]
我更新了一下docker-compose，我在我本机 mac 使用成功了。你可以尝试下。 #138

**Comment by itltf512116** [comment]
tuoyun分支，deploy文件夹下有个文档，可以试试这个方式

**Comment by shoyu666** [comment]
windows下docker-compose部署完后
- kafka 成功
- mysql 成功
- mongodb 成功
- redis 成功
- etcd 成功
- minio 成功
- open_im_server 失败

此时可以单独删除open_im_server (通过docker desktop)
然后通过源码运行

修改相关配置 config.yaml
win_build_all_service.cmd 编译
win_start_all_service.cmd 运行

**Comment by skiffer-git** [comment]
Linux is recommended
